---
achievements:
  achievements: {}
  shortcuts:
    achievements: achievement
  types:
    community: fa-users
    portal: fa-globe
    fs3: fa-cubes
    story: fa-book
  permissions:
    manage_achievements: Award and remove achievements.
