---
achievements:
  announce_channel: Achievements
  custom_achievements: {}
  shortcuts:
    achievements: achievement
  types:
    community: fa-users
    comp: fa-hand-holding-heart
    portal: fa-globe
    fs3: fa-cubes
    story: fa-book
    spell: fa-magic
    potion: fa-flask
    death: fa-skull-crossbones
    plot: fa-book-open
    meme: fa-award
  achievements:
    object_meme:
      type: meme
      message: Participated in the Object Meme
    vignette_challenge:
      type: meme
      message: Participated in a Vignette Challenge
