---
channels:
  approved_channels:
  - Chat
  - RP Requests
  - Big Scene
  - Achievements
  clear_history_cron:
    hour:
    - 4
    minute:
    - 47
  default_channels:
  - Questions
  end_marker: "]"
  shortcuts:
    chan: channel
    channels: channel
    comlist: channel
    clist: channel
    channel/describe: channel/desc
    channel/gag: channel/mute
    channel/ungag: channel/unmute
    channel/add: channel/create
    channel/on: channel/join
    channel/off: channel/leave
    addcom: channel/join
    delcom: channel/leave
    comtitle: channel/title
    channel/name: channel/rename
  start_marker: "["
  ooc_lounge_channel: ''
  recall_timeout_days: 1
