---
chargen:
  allow_web_submit: true
  app_category: APP
  app_hold_status: HOLD
  app_resubmit_status: OPEN
  app_review_commands:
  - app %{name}
  - profile %{name}
  - bg %{name}
  - hooks %{name}
  - sheet %{name}
  approval_message: Congratulations!  Your application has been approved.  Check out
    the [Getting Started](/wiki/guides:getting_started) guide for help finding a place to
    live, getting into RP, and more. We are glad to have you!
  arrivals_category: New Arrivals
  demographics_blurb: "Set the basic information about your character here."
  groups_blurb: "[Schools](/wiki/schools) reflect the type of spells a magic user is able to do. A magic user may have an affinity for a single School, or they may possess an affinity for two, one lesser and one greater. \n\nSetting your School(s) here will set your Major School to level 2 and your Minor School to level 1. If you choose only a Major School, you can raise it to level 3 on the Action Skills tab."
  bg_blurb: "You don't need to write a novel. Just cover the basics: who you are, why are you here, and is there anything noteworthy about you. Be sure to explain any unusual skills.\n\n
  * What are the major events in your character's life?
  * Where are they from, what do they do for a living?
  * Why have they come to Grand Lake? If they were drawn by the dreams, what might motivate them to stay? How will they make that work?\n
  *New characters cannot have been living within magic's influence before approval - though they can be local characters returning home.*\n\n
  **Magic and Coming to Grand Lake**\n
  Magic has been slowly trickling back into the world since early 2019.\n\n
Although Grand Lake seems to have an abnormally high population of magic users, not all character will be natives. Those who are not are drawn to Grand Lake via dreams. Vague at first, the dreams grow increasingly explicit about the location. They feature images of the Rocky Mountains and Grand Lake, along with an unmistakable sense that answers lie there. They don't reveal further details - only that Grand Lake is the place to come, with a hint that there might be answers - and others experiencing the same thing - there. "
  desc_blurb: You can set both your main description, visible when people look at
    you, and a short description that shows your character at a glance.
  hooks_blurb: "RP Hooks are interesting things about your character that others can
    hook into for RP. This could be an odd personality quirk, a reputation your character
    has, or anything else that might inspire someone to connect with you. Looking
    around at other character's sheets can be a good way to get inspiration for RP
    Hooks.\n\nYour RP Hooks will also show in the welcome message posted to the forum, so everyone gets a snapshot of who your character is."
  hooks_required: true
  icon_blurb: "Upload an optional picture for your character icon. Square images work best."
  lastwill_blurb: "If you would like to register a preference on what happens if you ever idle out, you can fill out your lastwill here.  You could leave your character's fate up to someone else, or specify that they be killed off or sent away.\n\nYou can fill out or change your lastwill at any time on game using the `lastwill` command."
  post_approval_message: Please make sure they have a profile image for their log icon.
  rejection_message: "Sorry, your character could not be approved at the present time for the reasons listed.  You can make changes to your app by visiting [Create a Character](/chargen) on the web portal. \n\nFeel free to leave comments in this request or to ask for help on the **New Characters** channel if you have any questions.\n\n-----------"
  rank_blurb: "Don't use ranks."
  shortcuts:
    chargen: cg
    cg/back: cg/prev
    cg/previous: cg/prev
    bg/approve: app/approve
    bg/reject: app/reject
    bg/submit: app/submit
    bg/unsubmit: app/unsubmit
    hooks: hook
    hook/delete: hook/remove
    hook/add: hook/set
  stages:
    start:
      tutorial: "Use the web portal CG."
  welcome_message: "Please welcome [%{name}](https://spiritlakemu.com/char/%{name}), our latest character to be approved! \n\nMajor
    School: %{major school} \nMinor School: %{minor school}\n\nRP Hooks:\n%{rp_hooks}"
