date_and_time:
    
    short_date_format: "%m/%d/%Y"
    # European style:
    # short_date_format: "%d-%m-%Y"
    
    long_date_format: "%a %b %d, %Y %l:%M%P"
    # European style (24hr clock):
    #long_date_format: "%d-%m-%Y %k%M"
    
    
    time_format: "%l:%M%P"
    # European style (24hr clock):
    #long_date_format: "%k%M"
    
    # NOTE: Must match the order of fields in short_date_format
    date_entry_format_help: "mm/dd/yyyy"
    # European style
    # date_entry_format_help: "yyyy-mm-dd"
    
    date_and_time_entry_format_help: "mm/dd/yyyy hh:mm<am or pm>"