---
describe:
  always_show_idle_in_rooms: false
  exit_end_bracket: "]"
  exit_start_bracket: "["
  glance_format: "%{height_title} height, %{age} year-old %{gender_noun} with %{hair}
    hair and %{eyes} eyes."
  shortcuts:
    l: look
    desc: describe
    outfits: outfit
    outfit/create: outfit/set
    outfit/add: outfit/set
    outfit/remove: outfit/delete
    detail/add: detail/set
    detail/create: detail/set
    detail/remove: detail/delete
    view/add: detail/set
    view/create: detail/set
    view/remove: detail/delete
    view: look
    vistas: vista
    vista/add: vista/set
    vista/create: vista/set
    vista/remove: vista/delete
  tag_colors:
    admin: "%xb"
    beginner: "%xg"
    web: "%xh%xx"
  permissions:
    desc_anything: Edit descs on any object.
    desc_places: Edit descs on rooms and exits
