events:
    calendar_timezone: "EST"
    
    # NOTE: The calendar ID and API key are configured in the game/config/secrets.yml file
    shortcuts:
        "events" : "event"
        "event/add" : "event/create"
        "event/remove" : "event/delete"
        
    event_alert_cron:
        minute: 
            - 0
            - 15
            - 30
            - 45