---
forum:
  shortcuts:
    bbs: forum
    bbread: forum
    bbscan: forum/scan
    bbpost: forum/post
    bbnext: forum/new
    bbnew: forum/new
    bbcatchup: forum/catchup
    bbedit: forum/edit
    bbreply: forum/reply
    bbcomment: forum/reply
    bbremove: forum/delete
    bbmove: forum/move
    bbs/remove: forum/delete
    bbs/read: forum
    bbnewgroup: forum/createboard
    bbcleargroup: forum/deleteboard
    bbarchive: forum/archive
    bbs/desc: forum/describe
    bbs/newgroup: forum/createboard
    bb/new: forum/new
  achievements:
    forum_reply:
      type: community
      message: Replied to a forum post.
    forum_post:
      type: community
      message: Created a forum post.
  permissions:
    manage_forum: Create and modify forum categories and posts.
