---
fs3combat:
  weapon special groups:
    Ranged:
    - agility
    - diamond
    - fire
    - grow
    - ice
    - lightning
    - shrink
    - transform
    - vitality
    - speed boost
    Melee:
    - agility
    - diamond
    - fire
    - grow
    - ice
    - lightning
    - shrink
    - sparring
    - strength
    - transform
    - vitality
    - speed boost
    Spell:
    - agility
    - shrink
    - strength
    - speed boost
    - grow      
  weapon specials:
    Sparring:
      description: Padded sparring equipment
      lethality: -50

  weapons:

    #RANGED
    Crossbow:
      description: Crossbow
      skill: Archery
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      ammo: 0
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: -2
      special_group: Ranged
    Flash Grenade:
      description: 'Hand Grenade which blinds/deafens most targets for 5 secs '
      skill: Athletics
      lethality: 0
      penetration: 8
      weapon_type: Suppressive
      recoil: 0
      damage_type: Stun
      accuracy: 5
      init_mod: 0
      special_group: Ranged
    Frag Grenade:
      description: Hand Grenade explodes on impact, doing shrapnel damage
      skill: Athletics
      lethality: 0
      penetration: 8
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
      special_group: Ranged
    Longbow:
      description: Longbow
      skill: Archery
      lethality: 0
      penetration: 4
      weapon_type: Ranged
      ammo: 0
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Ranged
    Shrapnel:
      description: Random Shrapnel
      skill: 3
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Pistol:
      description: Pistol
      skill: Firearms
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      ammo: 0
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      allowed_specials:
      special_group: Ranged
    Recurve Bow:
      description: Basic bow and arrows
      skill: Archery
      lethality: 0
      penetration: 4
      weapon_type: Ranged
      ammo: 0
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Ranged
    Rifle:
      description: Hunting Rifle
      skill: Firearms
      lethality: 0
      penetration: 6
      weapon_type: Ranged
      ammo: 0
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      allowed_specials:
      special_group: Ranged
    Shotgun:
      description: Shotgun meant for hunting
      skill: Firearms
      lethality: 5
      penetration: 4
      weapon_type: Ranged
      ammo: 0
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      allowed_specials:
      special_group: Ranged
    Tazer:
      description: Stun gun
      skill: Firearms
      lethality: 70
      penetration: 10
      weapon_type: Ranged
      ammo: 0
      recoil: 0
      damage_type: Stun
      accuracy: 0
      init_mod: 0
      special_group: Ranged
    #MELEE
    Antlers:
      description: Antlers
      skill: Melee
      lethality: -10
      penetration: 2
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Axe:
      description: Axe of any type
      skill: Melee
      lethality: 0
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Car:
      description: Hitting things with a car.
      skill: Alertness
      lethality: 5
      penetration: 4
      weapon_type: Melee
      ammo: 0
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      allowed_specials:
      special_group: Melee
    Club:
      description: Mace/club/baton/chair leg etc
      skill: Melee
      lethality: -10
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Horns:
      description: Horns
      skill: Melee
      lethality: -10
      penetration: 2
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Knife:
      description: Knife or dagger
      skill: Melee
      lethality: -5
      penetration: 4
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Spear:
      description: Spear or long stabby weapon of any type. For thrusting, not throwing.
      skill: Melee
      lethality: 0
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Sword:
      description: Sword of any type
      skill: Melee
      lethality: 0
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Unarmed:
      description: Unarmed
      skill: Brawl
      lethality: -20
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee

    #CREATURES
    Beak:
      description: Bites from a beak
      skill: Melee
      lethality: -15
      penetration: 3
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: -1
      init_mod: 0
      special_group: Melee
    Bug Bite:
      description: Mild bug bites
      skill: Melee
      lethality: -25
      penetration: 2
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Claws:
      description: Animal or creature claws
      skill: Melee
      lethality: -5
      penetration: 3
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Poison Stinger:
      description: Poison Insect stinger
      skill: Melee
      lethality: 0
      penetration: 4
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Sharp Claws:
      description: Upper level animal or creature claws
      skill: Melee
      lethality: 0
      penetration: 6
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Stinger:
      description: Insect stinger
      skill: Melee
      lethality: -10
      penetration: 3
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Teeth:
      description: Animal or creature teeth
      skill: Melee
      lethality: -5
      penetration: 4
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee

    #MAGIC ITEMS
    Skofnung:
      description: Ragnar's magical sword
      is_magic: true
      skill: Melee
      lethality: 10
      penetration: 12
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
