---
fs3combat:
  armor:
    None:
      description: In case you need to take off armor
      is_magic: false
      defense: 0
      protection:
        Nowhere: 0
    Tough Hide:
      description: Low level animal hide
      is_magic: false
      defense: 1
      protection:
        Chest: 4
        Rear Left Leg: 4
        Read Right Leg: 4
        Front Left Leg: 4
        Front Right Leg: 4
        Abdomen: 4
        Head: 3
        Neck: 3
        Groin: 2
    Very Tough Hide:
      description: Animal hide on par with plate armor
      is_magic: false
      defense: 1
      protection:
        Chest: 9
        Rear Left Leg: 8
        Rear Right Leg: 8
        Front Left Leg: 8
        Front Right Leg: 8
        Left Leg: 8
        Right Leg: 8
        Tail: 8
        Right Wing: 8
        Left Wing: 8
        Abdomen: 9
        Head: 7
        Neck: 6
        Groin: 5
    Extremely Tough Hide:
      description: Animal hide on par with uppper level magic armor
      is_magic: false
      defense: 1
      protection:
        Chest: 14
        Rear Left Leg: 12
        Rear Right Leg: 12
        Front Left Leg: 12
        Front Right Leg: 12
        Left Leg: 12
        Right Leg: 12
        Tail: 13
        Right Wing: 12
        Left Wing: 12
        Abdomen: 14
        Head: 11
        Neck: 10
        Groin: 10
    Tactical:
      description: Military-Grade Kevlar Vest and Helmet
      is_magic: false
      defense: 0
      protection:
        Head: 7
        Neck: 5
        Chest: 8
        Abdomen: 7
    Chainmail:
      description: Chainmail shirt & gambeson
      is_magic: false
      defense: 0
      protection:
        Chest: 8
        Abdomen: 7
        Left Arm: 8
        Right Arm: 8
      allowed_specials:
      - Leather Helmet
      - Metal Helmet
      - Chainmail Coif
    Plate:
      description: Full plate armor with no helmet
      is_magic: false
      defense: -1
      protection:
        Chest: 9
        Abdomen: 8
        Left Arm: 9
        Right Arm: 9
        Right Leg: 7
        Left Leg: 7
      allowed_specials:
      - Leather Helmet
      - Metal Helmet
      - Chainmail Coif
    Leather:
      description: Leather armor
      is_magic: false
      defense: 0
      protection:
        Chest: 7
        Abdomen: 6
        Left Arm: 7
        Right Arm: 7
      allowed_specials:
      - Leather Helmet
      - Metal Helmet
      - Chainmail Coif
    Police:
      description: Police-Grade Kevlar Vest
      is_magic: false
      defense: 0
      protection:
        Chest: 7
        Abdomen: 6
      allowed_specials:
      - Modern Helmet

#SPELLS
  #LEVEL 2
    Natural Defenses:
      description: Level 2 Nature spell
      is_magic: false
      defense: 0
      protection:
        Head: 4
        Neck: 4
        Chest: 4
        Abdomen: 4
        Left Leg: 4
        Right Leg: 4
        Groin: 4
        Left Arm: 4
        Right Arm: 4
        Left Hand: 4
        Right Hand: 4
        Left Foot: 4
        Right Foot: 4
  #LEVEL 3
    Bark Skin:
      description: Level 3 Nature spell
      is_magic: true
      defense: 0
      protection:
        Head: 6
        Neck: 6
        Chest: 6
        Abdomen: 6
        Left Leg: 6
        Right Leg: 6
        Groin: 6
        Left Arm: 6
        Right Arm: 6
        Left Hand: 6
        Right Hand: 6
        Left Foot: 6
        Right Foot: 6
  #LEVEL 4
    Crystalline:
      description: Level 4 Earth spell
      is_magic: true
      defense: 0
      protection:
        Head: 11
        Neck: 11
        Chest: 11
        Abdomen: 11
        Left Leg: 11
        Right Leg: 11
        Groin: 11
        Left Arm: 11
        Right Arm: 11
        Left Hand: 11
        Right Hand: 11
        Left Foot: 11
        Right Foot: 11
    Exoskeleton:
      description: Level 4 Corpus spell
      is_magic: true
      defense: 0
      protection:
        Head: 9
        Neck: 9
        Chest: 9
        Abdomen: 9
        Left Leg: 9
        Right Leg: 9
        Groin: 9
        Left Arm: 9
        Right Arm: 9
        Left Hand: 9
        Right Hand: 9
        Left Foot: 9
        Right Foot: 9
    Ice:
      description: Level 4 Water spell
      is_magic: true
      defense: 0
      protection:
        Head: 8
        Neck: 8
        Chest: 8
        Abdomen: 8
        Left Leg: 8
        Right Leg: 8
        Groin: 8
        Left Arm: 8
        Right Arm: 8
        Left Hand: 8
        Right Hand: 8
        Left Foot: 8
        Right Foot: 8
    Rock Skin:
      description: Level 4 Earth spell
      is_magic: true
      defense: 0
      protection:
        Head: 8
        Neck: 8
        Chest: 8
        Abdomen: 8
        Left Leg: 8
        Right Leg: 8
        Groin: 8
        Left Arm: 8
        Right Arm: 8
        Left Hand: 8
        Right Hand: 8
        Left Foot: 8
        Right Foot: 8
    Telekinetic:
      description: Level 4 Will spell
      is_magic: true
      defense: 0
      protection:
        Head: 11
        Neck: 11
        Chest: 11
        Abdomen: 11
        Left Leg: 11
        Right Leg: 11
        Groin: 11
        Left Arm: 11
        Right Arm: 11
        Left Hand: 11
        Right Hand: 11
        Left Foot: 11
        Right Foot: 11
  #LEVEL 5
    #WILD SHAPE
    Crocodile:
      description: Wild Shape Crocodile
      is_magic: true
      defense: 0
      protection:
        Head: 4
        Neck: 4
        Chest: 4
        Abdomen: 4
        Left Leg: 4
        Right Leg: 4
        Groin: 4
        Left Arm: 4
        Right Arm: 4
        Left Hand: 4
        Right Hand: 4
        Left Foot: 4
        Right Foot: 4
    Hrafn:
      description: Wild Shape Hrafn
      is_magic: true
      protection:
        Head: 0
        Neck: 0
        Chest: 0
        Abdomen: 0
        Left Leg: 0
        Right Leg: 0
        Groin: 0
        Left Arm: 0
        Right Arm: 0
        Left Hand: 0
        Right Hand: 0
        Left Foot: 0
        Right Foot: 0
      defense: 1
    Lynx:
      description: Wild Shape Lynx
      is_magic: true
      protection:
        Head: 0
        Neck: 0
        Chest: 0
        Abdomen: 0
        Left Leg: 0
        Right Leg: 0
        Groin: 0
        Left Arm: 0
        Right Arm: 0
        Left Hand: 0
        Right Hand: 0
        Left Foot: 0
        Right Foot: 0
      defense: 2
    Moth:
      description: Wild Shape Moth
      is_magic: true
      protection:
        Head: 0
        Neck: 0
        Chest: 0
        Abdomen: 0
        Left Leg: 0
        Right Leg: 0
        Groin: 0
        Left Arm: 0
        Right Arm: 0
        Left Hand: 0
        Right Hand: 0
        Left Foot: 0
        Right Foot: 0
      defense: 10
    #LEVEL 6
    Jenu:
      description: Level 6 Nature spell
      is_magic: true
      defense: 3
      protection:
        Head: 0
    Glacial Ice:
      description: Level 6 Water spell
      is_magic: true
      defense: 1
      protection:
        Head: 12
        Neck: 12
        Chest: 12
        Abdomen: 12
        Left Leg: 12
        Right Leg: 12
        Groin: 12
        Left Arm: 12
        Right Arm: 12
        Left Hand: 12
        Right Hand: 12
        Left Foot: 12
        Right Foot: 12
    Diamond:
      description: Level 6 earth spell
      is_magic: true
      defense: 0
      protection:
        Head: 14
        Neck: 14
        Chest: 14
        Abdomen: 14
        Left Leg: 14
        Right Leg: 14
        Groin: 14
        Left Arm: 14
        Right Arm: 14
        Left Hand: 14
        Right Hand: 14
        Left Foot: 14
        Right Foot: 14
    Glacial Ice:
      description: Level 6 Water spell
      is_magic: true
      defense: 0
      protection:
        Head: 12
        Neck: 12
        Chest: 12
        Abdomen: 12
        Left Leg: 12
        Right Leg: 12
        Groin: 12
        Left Arm: 12
        Right Arm: 12
        Left Hand: 12
        Right Hand: 12
        Left Foot: 12
        Right Foot: 12
    Iron Body:
      description: Level 6 Corpus spell
      is_magic: true
      defense: 0
      protection:
        Head: 11
        Neck: 11
        Chest: 11
        Abdomen: 11
        Left Leg: 11
        Right Leg: 11
        Groin: 11
        Left Arm: 11
        Right Arm: 11
        Left Hand: 11
        Right Hand: 11
        Left Foot: 11
        Right Foot: 11
    Ironwood Skin:
      description: Level 6 Nature spell
      is_magic: true
      defense: 0
      protection:
        Head: 14
        Neck: 14
        Chest: 14
        Abdomen: 14
        Left Leg: 14
        Right Leg: 14
        Groin: 14
        Left Arm: 14
        Right Arm: 14
        Left Hand: 14
        Right Hand: 14
        Left Foot: 14
        Right Foot: 14
    Transmutation:
      description: Level 6 Will spell
      is_magic: true
      defense: 0
      protection:
        Head: 14
        Neck: 14
        Chest: 14
        Abdomen: 14
        Left Leg: 14
        Right Leg: 14
        Groin: 14
        Left Arm: 14
        Right Arm: 14
        Left Hand: 14
        Right Hand: 14
        Left Foot: 14
        Right Foot: 14
    Storm:
      description: Level 6 Air spell
      is_magic: true
      defense: 3
      protection:
        Head: 11
        Neck: 11
        Chest: 11
        Abdomen: 11
        Left Leg: 11
        Right Leg: 11
        Groin: 11
        Left Arm: 11
        Right Arm: 11
        Left Hand: 11
        Right Hand: 11
        Left Foot: 11
        Right Foot: 11
#LEVEL 7
    Demon Form:
      description: Level 7 Corpus spell
      is_magic: true
      defense: 1
      protection:
        Head: 12
        Neck: 12
        Chest: 12
        Abdomen: 12
        Left Leg: 12
        Right Leg: 12
        Groin: 12
        Left Arm: 12
        Right Arm: 12
        Left Hand: 12
        Right Hand: 12
        Left Foot: 12
        Right Foot: 12
    Verdurous:
      description: Level 7 Nature spell
      is_magic: true
      defense: 2
      protection:
        Head: 12
        Neck: 12
        Chest: 12
        Abdomen: 12
        Left Leg: 12
        Right Leg: 12
        Groin: 12
        Left Arm: 12
        Right Arm: 12
        Left Hand: 12
        Right Hand: 12
        Left Foot: 12
        Right Foot: 12
  armor specials:
    Modern Helmet:
      description: A modern combat or police helmet
      is_magic: false
      protection:
        Head: 4
    Leather Helmet:
      description: A leather helmet
      is_magic: false
      protection:
        Head: 3
    Metal Helmet:
      description: A leather helmet
      is_magic: false
      protection:
        Head: 4
    Chainmail Coif:
      description: A chainmail coif that covers your head and neck, with a helmet
        atop.
      is_magic: false
      protection:
        Head: 5
        Neck: 4
    #ITEM ARMOR SPECIALS
    Dragon Visage:
      description: Magical item
      is_magic: false
      defense: 1
    Huxian's Gift:
      description: Magical item
      is_magic: true
      defense: 3
    Ring of Nolawyn:
      description: Magical item
      is_magic: true
      defense: 1
    Tarian Y Tir:
      description: Magical Item
      protection:
        Left Arm: 7
        Left Hand: 7
        Chest: 7
        Abdomen: 7
        Groin: 7
