---
fs3combat:
  weapons:
    Flash Grenade:
      description: Flashbang Hand Grenade which blinds/deafens human targets for 5
        secs.  No effect on Centurions.
      skill: Athletics
      lethality: 0
      penetration: 8
      weapon_type: Suppressive
      is_automatic: false
      recoil: 0
      damage_type: Stun
      accuracy: 5
      has_shrapnel: false
      init_mod: 0
    Frag Grenade:
      description: Fragmentation Hand Grenade
      skill: Athletics
      lethality: 0
      penetration: 8
      weapon_type: Explosive
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Grenade Launcher:
      description: Grenade Launcher
      skill: Gunnery
      lethality: 0
      penetration: 8
      weapon_type: Explosive
      is_automatic: false
      ammo: 4
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Mine:
      description: Mine or other anti-personnel explosive
      skill: Demolitions
      lethality: 20
      penetration: 8
      weapon_type: Explosive
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Missile:
      description: Guided Anti-Vehicle Missile
      skill: Gunnery
      lethality: 80
      penetration: 17
      weapon_type: Ranged
      is_automatic: false
      ammo: 2
      recoil: 0
      damage_type: Physical
      accuracy: 3
      has_shrapnel: false
      init_mod: 0
    Talons:
      description: Unguided Anti-Vehicle Rockets
      skill: Gunnery
      lethality: 0
      penetration: 9
      weapon_type: Ranged
      is_automatic: false
      ammo: 20
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Rocket:
      description: Unguided Anti-Personnel Rocket
      skill: Gunnery
      lethality: 40
      penetration: 8
      weapon_type: Explosive
      is_automatic: false
      ammo: 4
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Shaped Charge:
      description: Anti-Vehicle explosive
      skill: Demolitions
      lethality: 15
      penetration: 25
      weapon_type: Explosive
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
    Shrapnel:
      description: Random Shrapnel
      skill: 3
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Lmg:
      description: Light machinegun/SAW
      skill: Firearms
      lethality: 0
      penetration: 6
      weapon_type: Ranged
      is_automatic: true
      ammo: 100
      recoil: 4
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
      - Bipod
    Pistol:
      description: Pistol
      skill: Firearms
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      is_automatic: false
      ammo: 10
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
    Rifle:
      description: Assault Rifle
      skill: Firearms
      lethality: 0
      penetration: 6
      weapon_type: Ranged
      is_automatic: true
      ammo: 20
      recoil: 3
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
      - Scope
    Sniper Rifle:
      description: Sniper Rifle
      skill: Firearms
      lethality: 0
      penetration: 8
      weapon_type: Ranged
      is_automatic: false
      ammo: 10
      recoil: 0
      damage_type: Physical
      accuracy: 2
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
      - Scope
    Shotgun:
      description: Shotgun using solid shot
      skill: Firearms
      lethality: 10
      penetration: 3
      weapon_type: Ranged
      is_automatic: false
      ammo: 8
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Buckshot
    Smg:
      description: Sub-machinegun
      skill: Firearms
      lethality: 0
      penetration: 6
      weapon_type: Ranged
      is_automatic: true
      ammo: 30
      recoil: 4
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
    Tazer:
      description: Stun gun
      skill: Firearms
      lethality: 70
      penetration: 10
      weapon_type: Ranged
      is_automatic: false
      ammo: 5
      recoil: 0
      damage_type: Stun
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Club:
      description: Mace/club/baton
      skill: Melee
      lethality: -10
      penetration: 0
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Knife:
      description: Knife
      skill: Melee
      lethality: -5
      penetration: 4
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Unarmed:
      description: Unarmed
      skill: Melee
      lethality: -20
      penetration: 0
      weapon_type: Melee
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Sparring
    Ecm:
      description: ECM Package
      skill: Gunnery
      lethality: 0
      penetration: 0
      weapon_type: Suppressive
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Hmg:
      description: Heavy machinegun.
      skill: Firearms
      lethality: 20
      penetration: 8
      weapon_type: Ranged
      is_automatic: true
      ammo: 100
      recoil: 6
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
      allowed_specials:
      - Ap
      - Bipod
    Kew:
      description: KEW Assault Cannon.  This is a chain gun and always burst fires,
        so that's factored into the damage.
      skill: Gunnery
      lethality: 0
      penetration: 9
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
    Cannon:
      description: Tank cannon.
      skill: Gunnery
      lethality: 0
      penetration: 23
      weapon_type: Ranged
      is_automatic: false
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: false
      init_mod: 0
  weapon specials:
    Ap:
      description: Armor Piercing Rounds
      penetration: 2
    Bipod:
      description: Bipod Brace
      recoi: -3
    Scope:
      description: Sniper scope
      accuracy: 2
    Buckshot:
      description: Shotgun pellets
      accuracy: 3
      penetration: -2
    Sparring:
      description: Padded sparring equipment
      lethality: -50
