---
fs3combat:
  hitloc:
    Deathcap:
      areas:
        Trunk:
        - Left Leg
        - Right Leg
        - Left Arm
        - Right Arm
        - Left Arm
        - Head
        - Head
        - Trunk
        - Trunk
        - Trunk
        Left Leg:
        - Trunk
        - Trunk
        - Right Foot
        - Right Leg
        - Right Leg
        - Left Foot
        - Left Foot
        - Left Leg
        - Left Leg
        - Left Leg
        Right Leg:
        - Trunk
        - Left Foot
        - Left Leg
        - Left Leg
        - Trunk
        - Trunk
        - Right Foot
        - Right Leg
        - Right Leg
        - Right Leg
        Left Hand:
        - Trunk
        - Trunk
        - Trunk
        - Left Arm
        - Left Arm
        - Left Arm
        - Left Arm
        - Left Hand
        - Left Hand
        - Left Hand
        Right Hand:
        - Trunk
        - Trunk
        - Right Arm
        - Right Arm
        - Right Arm
        - Right Arm
        - Right Arm
        - Right Hand
        - Right Hand
        - Right Hand
        Left Arm:        
        - Head
        - Trunk
        - Trunk
        - Trunk
        - Left Hand
        - Left Hand
        - Left Hand
        - Left Arm
        - Left Arm
        - Left Arm
        Right Arm:
        - Right Arm
        - Right Arm
        - Right Arm
        - Head
        - Trunk
        - Trunk
        - Trunk
        - Right Hand
        - Right Hand
        - Right Hand
        Head:
        - Right Arm
        - Right Arm
        - Left Arm
        - Left Arm
        - Trunk
        - Trunk
        - Trunk
        - Head
        - Head
        - Head
      vital_areas:
      - Trunk
      critical_areas:
      - Head
    Humanoid:
      areas:
        Chest:
        - Left Leg
        - Right Leg
        - Left Arm
        - Right Arm
        - Abdomen
        - Abdomen
        - Head
        - Chest
        - Chest
        - Chest
        Left Leg:
        - Chest
        - Right Foot
        - Right Leg
        - Right Leg
        - Abdomen
        - Abdomen
        - Left Foot
        - Left Leg
        - Left Leg
        - Left Leg
        Right Leg:
        - Chest
        - Left Foot
        - Left Leg
        - Left Leg
        - Abdomen
        - Abdomen
        - Right Foot
        - Right Leg
        - Right Leg
        - Right Leg
        Groin:
        - Abdomen
        - Abdomen
        - Abdomen
        - Left Leg
        - Right Leg
        - Left Leg
        - Right Leg
        - Groin
        - Groin
        - Groin
        Left Hand:
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Left Arm
        - Left Arm
        - Left Arm
        - Left Hand
        - Left Hand
        - Left Hand
        Right Hand:
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Right Arm
        - Right Arm
        - Right Arm
        - Left Hand
        - Left Hand
        - Left Hand
        Left Arm:
        - Head
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Left Hand
        - Left Hand
        - Left Arm
        - Left Arm
        - Left Hand
        Right Arm:
        - Head
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Right Hand
        - Right Hand
        - Right Arm
        - Right Arm
        - Right Hand
        Head:
        - Right Arm
        - Right Arm
        - Left Arm
        - Chest
        - Chest
        - Neck
        - Neck
        - Head
        - Head
        - Head
        Neck:
        - Right Arm
        - Right Arm
        - Left Arm
        - Chest
        - Chest
        - Head
        - Head
        - Neck
        - Neck
        - Neck
        Abdomen:
        - Left Leg
        - Right Leg
        - Left Leg
        - Right Leg
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
      vital_areas:
      - Chest
      - Abdomen
      critical_areas:
      - Head
      - Neck
      - Groin
    Plant:
      areas:
        Stem:
        - Stem
        - Stem
        - Stem
        - Stem
        - Left Vines
        - Left Vines
        - Flower
        - Flower
        - Right Vines
        - Right Vines
        Right Vines:
        - Right Vines
        - Left Vines
        - Left Vines
        - Flower
        - Flower
        - Right Vines
        - Right Vines
        - Right Vines
        - Right Vines
        - Stem
        Left Vines:
        - Left Vines
        - Left Vines
        - Left Vines
        - Left Vines
        - Left Vines
        - Flower
        - Flower
        - Right Vines
        - Right Vines
        - Stem
        Flower:
        - Flower
        - Flower
        - Flower
        - Left Vines
        - Left Vines
        - Left Vines
        - Right Vines
        - Right Vines
        - Stem
        - Stem
      vital_areas:
      - Stem
      critical_areas:
      - Flower
    Quadraped:
      areas:
        Chest:
        - Rear Left Leg
        - Rear Right Leg
        - Front Left Leg
        - Front Right Leg
        - Abdomen
        - Abdomen
        - Head
        - Chest
        - Chest
        - Chest
        Rear Left Leg:
        - Chest
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        Rear Right Leg:
        - Chest
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        - Abdomen
        - Abdomen
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        Groin:
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Right Leg
        - Rear Left Leg
        - Rear Right Leg
        - Groin
        - Groin
        - Groin
        Front Left Leg:
        - Head
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Front Left Leg
        - Front Left Leg
        - Front Left Leg
        - Front Left Leg
        Front Right Leg:
        - Head
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
        - Front Right Leg
        - Front Right Leg
        - Front Right Leg
        - Front Right Leg
        Head:
        - Front Right Leg
        - Front Right Leg
        - Front Left Leg
        - Chest
        - Chest
        - Neck
        - Neck
        - Head
        - Head
        - Head
        Neck:
        - Front Right Leg
        - Front Right Leg
        - Front Left Leg
        - Chest
        - Chest
        - Head
        - Head
        - Neck
        - Neck
        - Neck
        Abdomen:
        - Rear Left Leg
        - Rear Right Leg
        - Rear Left Leg
        - Rear Right Leg
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
      vital_areas:
      - Chest
      - Abdomen
      critical_areas:
      - Head
      - Neck
      - Groin
    Serpent:
      areas:
        Head:
        - Right Flank
        - Right Flank
        - Right Flank
        - Left Flank
        - Left Flank
        - Left Flank
        - Head
        - Head
        - Head
        - Head
        Right Flank:
        - Tail
        - Tail
        - Tail
        - Head
        - Head
        - Left Flank
        - Left Flank
        - Right Flank
        - Right Flank
        - Right Flank
        Left Flank:
        - Tail
        - Tail
        - Tail
        - Head
        - Head
        - Right Flank
        - Right Flank
        - Left Flank
        - Left Flank
        - Left Flank
        Tail:
        - Right Flank
        - Right Flank
        - Right Flank
        - Left Flank
        - Left Flank
        - Left Flank
        - Tail
        - Tail
        - Tail
        - Tail
      vital_areas:
      - Head
      critical_areas:
      - Left Flank
    Tree:
      areas:
        Trunk:
        - Trunk
        - Trunk
        - Trunk
        - Trunk
        - Right Branches
        - Right Branches
        - Left Branches
        - Left Branches
        - Upper Branches
        - Upper Branches
        Right Branches:
        - Right Branches
        - Right Branches
        - Right Branches
        - Left Branches
        - Left Branches
        - Upper Branches
        - Upper Branches
        - Upper Branches
        - Trunk
        - Trunk
        Left Branches:
        - Left Branches
        - Left Branches
        - Left Branches
        - Upper Branches
        - Upper Branches
        - Upper Branches
        - Right Branches
        - Right Branches
        - Trunk
        - Trunk
        Upper Branches:
        - Upper Branches
        - Upper Branches
        - Upper Branches
        - Left Branches
        - Left Branches
        - Left Branches
        - Right Branches
        - Right Branches
        - Trunk
        - Trunk
      vital_areas: []
      critical_areas: []
    Target:
      areas:
        Bullseye:
        - Ring 3
        - Ring 3
        - Ring 3
        - Ring 3
        - Ring 2
        - Ring 2
        - Ring 2
        - Ring 1
        - Ring 1
        - Bullsye
      vital_areas: []
      critical_areas: []
    Insect:
      areas:
        Left Leg:
        - Thorax
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        Right Leg:
        - Thorax
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        Rear Left Leg:
        - Thorax
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        Rear Right Leg:
        - Thorax
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        - Abdomen
        - Abdomen
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        Front Left Leg:
        - Head
        - Thorax
        - Thorax
        - Thorax
        - Abdomen
        - Abdomen
        - Front Left Leg
        - Front Left Leg
        - Front Left Leg
        - Front Left Leg
        Front Right Leg:
        - Head
        - Thorax
        - Thorax
        - Abdomen
        - Abdomen
        - Abdomen
        - Front Right Leg
        - Front Right Leg
        - Front Right Leg
        - Front Right Leg
        Head:
        - Front Right Leg
        - Front Right Leg
        - Front Left Leg
        - Thorax
        - Thorax
        - Head
        - Head
        - Head
        Abdomen:
        - Rear Left Leg
        - Rear Right Leg
        - Rear Left Leg
        - Rear Right Leg
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
      vital_areas:
      - Abdomen
      critical_areas:
      - Thorax
    FlyingInsect:
      areas:
        Left Leg:
        - Thorax
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        Right Leg:
        - Thorax
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        Rear Left Leg:
        - Thorax
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Abdomen
        - Abdomen
        - Abdomen
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        Rear Right Leg:
        - Thorax
        - Rear Left Leg
        - Rear Left Leg
        - Rear Left Leg
        - Abdomen
        - Abdomen
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        - Rear Right Leg
        Front Left Leg:
        - Head
        - Thorax
        - Thorax
        - Thorax
        - Abdomen
        - Abdomen
        - Front Left Leg
        - Front Left Leg
        - Front Left Leg
        - Front Left Leg
        Front Right Leg:
        - Head
        - Thorax
        - Thorax
        - Abdomen
        - Abdomen
        - Abdomen
        - Front Right Leg
        - Front Right Leg
        - Front Right Leg
        - Front Right Leg
        Right Wing:
        - Head
        - Thorax
        - Thorax
        - Abdomen
        - Abdomen
        - Right Wing
        - Right Wing
        - Right Wing
        - Front Right Leg
        - Front Right Leg
        Left Wing:
        - Head
        - Thorax
        - Thorax
        - Abdomen
        - Abdomen
        - Left Wing
        - Left Wing
        - Left Wing
        - Front Left Leg
        - Front Left Leg
        Head:
        - Front Right Leg
        - Front Right Leg
        - Front Left Leg
        - Front Left Leg
        - Thorax
        - Thorax
        - Thorax
        - Head
        - Head
        - Head
        Abdomen:
        - Rear Left Leg
        - Rear Right Leg
        - Rear Left Leg
        - Rear Right Leg
        - Chest
        - Chest
        - Chest
        - Abdomen
        - Abdomen
        - Abdomen
      vital_areas:
      - Abdomen
      critical_areas:
      - Thorax
