---
fs3combat:
  damage_mods:
    HEAL: 0
    FLESH: 0.25
    IMPAIR: 2
    INCAP: 7
  damage_table:
    GRAZE: 20
    FLESH: 70
    IMPAIR: 95
  healing_cron:
    hour:
    - 0
    minute:
    - 47
  healing_points:
    HEAL: 0
    FLESH: 7
    IMPAIR: 10
    INCAP: 7
  pc_knockout_bonus: 1
