---
fs3combat:
#---------------
# WEAPONS
#---------------
  weapons:
    #---------------
    # SPELL WEAPONS
    #---------------
    # LEVEL 2
    Sling Barb:
      description: Level 2 Creation spell
      is_magic: true
      skill: Creation
      lethality: 0
      penetration: 3
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    # LEVEL 3
    Flame Dart:
      description: Level 3 Aether spell
      is_magic: true
      skill: Aether
      lethality: 15
      penetration: 3
      weapon_type: Ranged
      recoil: 0
      damage_type: Fire
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Ice Talons:
      description: Level 3 Entropy spell
      is_magic: true
      skill: Brawl
      lethality: 0
      penetration: 4
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Body
      magic_damage_type: Cold
    Stone Slam:
      description: Level 3 Creation spell
      is_magic: true
      skill: Creation
      lethality: 0
      penetration: 4
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    # LEVEL 4
    Ice Armor:
      description: Level 4 Entropy spell
      is_magic: true
      skill: Brawl
      lethality: 0
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Body
    Ice Blast:
      description: Level 4 Entropy spell
      is_magic: true
      skill: Entropy
      lethality: 15
      penetration: 5
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
      magic_damage_type: Cold
    Lightning Ball:
      description: Level 4 Aether spell
      is_magic: true
      skill: Aether
      lethality: 0
      penetration: 6
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Stone Skin:
      description: Level 4 Creation spell
      is_magic: true
      skill: Brawl
      lethality: 0
      penetration: 4
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Body
    # LEVEL 5
    Breathless:
      description: Level 5 Aether spell
      is_magic: true
      skill: Aether
      lethality: -20
      penetration: 50
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
      magic_damage_type: Bypass
    Fireball:
      description: Level 5 Aether spell
      is_magic: true
      skill: Aether
      lethality: 10
      penetration: 6
      weapon_type: Ranged
      recoil: 0
      damage_type: Fire
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Gravity Crush:
      description: Level 5 Entropy spell
      is_magic: true
      skill: Entropy
      lethality: 10
      penetration: 8
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    #LEVEL 6
    Cone Of Cold:
      description: Level 6 Entropy spell
      is_magic: true
      skill: Entropy
      lethality: -5
      penetration: 8
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
      magic_damage_type: Cold
    Flares:
      description: Level 6 Aether spell
      is_magic: true
      skill: Aether
      lethality: 5
      penetration: 7
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      special_group: Spell
      magic_damage_type: Fire
    Lightning Bolt:
      description: Level 6 Aether spell
      is_magic: true
      skill: Aether
      lethality: 15
      penetration: 9
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Stalagmite:
      description: Level 6 Creation spell
      is_magic: true
      skill: Creation
      lethality: 10
      penetration: 8
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      special_group: Spell
  #LEVEL 7
    Exploding Earth:
      description: Level 7 Entropy spell
      is_magic: true
      skill: Entropy
      lethality: -10
      penetration: 7
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 2
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Pyre:
      description: Level 7 Aether spell
      is_magic: true
      skill: Aether
      lethality: 15
      penetration: 9
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      special_group: Spell
      magic_damage_type: Fire
    Poison Puffs:
      description: Level 7 Creation spell
      is_magic: true
      skill: Creation
      lethality: -15
      penetration: 50
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: -1
      special_group: Spell
    Stone Daggers:
      description: Level 7 Creation spell
      is_magic: true
      skill: Creation
      lethality: 10
      penetration: 9
      weapon_type: Ranged
      is_automatic: true
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    #LEVEL 8
    Meteor:
      description: Level 8 Creation spell
      is_magic: true
      skill: Creation
      lethality: 10
      penetration: 10
      weapon_type: Explosive
      is_automatic: true
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Ice Storm:
      description: Level 8 Entropy spell
      is_magic: true
      skill: Entropy
      lethality: 10
      penetration: 10
      weapon_type: Explosive
      is_automatic: true
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
      magic_damage_type: Cold
    Lightning Strike:
      description: Level 8 Aether spell
      is_magic: true
      skill: Aether
      lethality: 20
      penetration: 11
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      special_group: Spell
    Suffocate:
      description: Level 8 Aether spell
      is_magic: true
      skill: Aether
      lethality: 0
      penetration: 50
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
      magic_damage_type: Bypass
  #---------------
  # GENERAL SPELL WEAPONS
  #---------------
    Cold Shrapnel:
      description: Shrapnel that does cold damage
      skill: 3
      lethality: 0
      penetration: 4
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      is_magic: true
    Physical Shrapnel:
      description: Shrapnel that does Physical damage
      skill: 3
      lethality: 0
      penetration: 4
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      is_magic: true
    Fire Shrapnel:
      description: Shrapnel that does Fire damage
      skill: 3
      lethality: 0
      penetration: 4
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      is_magic: true
    Spell:
      description: Spell with no stats to make it easier to grab special stats.
      is_magic: true
      skill: Athletics
      lethality: 0
      penetration: 0
      weapon_type: Ranged
      recoil: 0
      damage_type: Stun
      accuracy: 0
      init_mod: 0
    Stun (Aether):
      description: Stun spell
      is_magic: true
      skill: Aether
      lethality: 0
      penetration: 0
      weapon_type: Stun
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Arcane):
      description: Stun spell
      is_magic: true
      skill: Arcane
      lethality: 0
      penetration: 0
      weapon_type: Stun
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Creation):
      description: Stun spell
      is_magic: true
      skill: Creation
      lethality: 0
      penetration: 0
      weapon_type: Stun
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Entropy):
      description: Stun spell
      is_magic: true
      skill: Entropy
      lethality: 0
      penetration: 0
      weapon_type: Stun
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
#---------------
# WEAPON SPECIAL GROUPS
#---------------
  weapon special groups:
    Body:
    - sparring
    - strength
    - weaken
    Ranged:
    - death touched
    - fire
    - ice
    - lightning
    - scope
    - weaken
    Melee:
    - death touched
    - fire
    - ice
    - lightning
    - sparring
    - strength
    - weaken
    Spell:
    - nothing

#---------------
# WEAPON SPECIALS
#---------------
  weapon specials:
    Sparring:
      description: Padded sparring equipment
      lethality: -50
    #---------------
    # MAGIC ITEMS
    #---------------
    Guilt-Weighted Gloves:
      description: Magic item
      is_magic: true
      lethality: 5
    #---------------
    # SPELLS
    #---------------
    Lightning:
      description: Level 4 Aether spell
      is_magic: true
      lethality: 5
      penetration: 1
      init_mod: 2
    Death Touched:
      description: Level 4 Entropy Spell
      is_magic: true
      lethality: 20
    Fire:
      description: Level 4 Aether spell
      is_magic: true
      lethality: 10
      accuracy: 1
    Ice:
      description: Level 4 Entropy spell
      is_magic: true
      lethality: 10
      penetration: 1
      magic_damage_type: Cold
    Strength:
      description: Level 4 Creation spell
      is_magic: true
      lethality: -5
      penetration: 2
    Weaken:
      description: Level 4 Entropy spell
      is_magic: true
      lethality: -15
      penetration: -1