---
fs3skills:
  advantages:
  - name: Rank
    desc: Rank or social status.
  - name: Resources
    desc: Wealth and other tangible possessions.
  advantages_blurb: 'Advantages represent important things your character possesses
    that are not skills.  Advantages are rated from 1-3. See <a href="https://aresmush.com/fs3/fs3-3/chargen.html#advantages"
    target="_blank">FS3: Advantages</a> for details.'
  use_advantages: false
