---
fs3skills:
  language_blurb: "Languages represent your ability to speak and read other languages. If a language that you would like is not currently listed, please speak to admin.\n\n
    Languages have a descriptive rating: Incapable, Beginner, Conversational, Fluent.   See [FS3: Languages](https://aresmush.com/fs3/fs3-3/chargen.html#languages) for details. To remove a language, set its rating to Unskilled."
  languages:
  - name: American Sign Language
    desc:
  - name: Arabic
    desc:
  - name: Arapaho
    desc:
  - name: Cantonese
    desc:
  - name: Danish
    desc:
  - name: English
    desc:
  - name: Finnish
    desc:
  - name: French
    desc:
  - name: German
    desc:
  - name: Greek
    desc:
  - name: Hebrew
    desc:
  - name: Hindi
    desc:
  - name: Irish
    desc:
  - name: Italian
    desc:
  - name: Japanese
    desc:
  - name: Latin
    desc:
  - name: Mandarin
    desc:
  - name: Portugese
    desc:
  - name: Russian
    desc:
  - name: Samoan
    desc:
  - name: Soitos
    desc:
  - name: Spanish
    desc:
  - name: Swedish
    desc:
  - name: Tagalog
    desc:
  - name: Ute
    desc:
  starting_languages:
  - English
