---
fs3combat:
  weapon specials:
    #LORE HOOKS
    Aos Si Coin:
      description: A magical lucky coin. Owned by Ethan.
      init_mod: 1
    Scythe Of Isis:
      description: A magical Scythe. Owned by Danielle.
      attack: 2
    Zhujiang's Hairpin:
      description: A magical hair pin. Owned by Adelaide.
      accuracy: 1
    #SPELLS
    # Agility:
    #   description: Level 4 Corpus spell
    #   is_magic: true
    #   init_mod: 1
    Diamond:
      description: Level 4 Earth spell
      is_magic: true
      penetration: 2
    Fire:
      description: Level 4 Fire spell
      is_magic: true
      lethality: 10
      accuracy: 1
    Grow:
      description: Level 4 Corpus spell
      is_magic: true
      lethality: 15
      penetration: 5
    Guilt-Weighted Gloves:
      description: Magic item
      is_magic: true
      lethality: 5
    Huxian's Gift:
      description: Magical item
      is_magic: true
      accuracy: 3
      init_mod: 3
    Ice:
      description: Level 4 Ice spell
      is_magic: true
      lethality: 15
      penetration: -1
    Lightning:
      description: Level 4 Air spell
      is_magic: true
      lethality: 5
      penetration: 1
      init_mod: 2
    Shrink:
      description: Level 4 Corpus spell
      is_magic: true
      lethality: -20
      penetration: -5
      init_mod: 1
    # Speed Boost:
    #   description: Level 6 Corpus spell
    #   is_magic: true
    #   init_mod: 2
    Strength:
      description: Level 3 Corpus spell
      is_magic: true
      lethality: -5
      penetration: 5
    Transform:
      description: Level 4 Will spell
      is_magic: true
      accuracy: 1
      lethality: 5
      penetration: 1
    Vitality:
      description: Level 4 Corpus spells
      is_magic: true
      lethality: 10

  weapons:
    Cold Shrapnel:
      description: Shrapnel that does cold damage
      skill: 3
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Fire Shrapnel:
      description: Shrapnel that does fire damage
      skill: 3
      lethality: 0
      penetration: 5
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    #LORE HOOKS
    Hell's Revenant:
      description: A magical single-edged Chinese longsword with a cleaver-like tip. Owned by Calgary.
      skill: Melee
      lethality: 0
      penetration: 6
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
      is_owned: true
    Dragon Visage:
      description: A tang dao, a type of Chinese saber similar in shape and size to a katana. Owned by Elke.
      skill: Melee
      lethality: 0
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
      is_owned: true
    Scythe Of Isis:
        description: An ancient bronze scythe with a long, crescent blade fitted to a slightly curved handle. Owned by Danielle.
        skill: Melee
        lethality: 0
        penetration: 5
        weapon_type: Melee
        recoil: 0
        damage_type: Physical
        accuracy: 0
        init_mod: 0
        special_group: Melee
        is_owned: true
    #General
    Spell:
      description: Spell with no stats to make it easier to grab special stats.
      is_magic: true
      skill: Athletics
      lethality: 0
      penetration: 0
      weapon_type: Suppressive
      recoil: 0
      damage_type: Stun
      accuracy: 0
      init_mod: 0
    Stun (Air):
      description: Stun spell
      is_magic: true
      skill: Air
      lethality: 0
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Corpus):
      description: Stun spell
      is_magic: true
      skill: Corpus
      lethality: 0
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Earth):
      description: Stun spell
      is_magic: true
      skill: Earth
      lethality: 0
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Fire):
      description: Stun spell
      is_magic: true
      skill: Fire
      lethality: 0
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Nature):
      description: Stun spell
      is_magic: true
      skill: Nature
      lethality: 0
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Spirit):
      description: Stun spell
      is_magic: true
      skill: Spirit
      lethality: 0
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Water):
      description: Stun spell
      is_magic: true
      skill: Water
      lethality: 0
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
    Stun (Will):
      description: Stun spell
      is_magic: true
      skill: Will
      lethality: 0
      penetration: 0
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
  #Level 1
  #Level 2
    Chill Touch:
      description: Level 2 Water spell
      is_magic: true
      skill: Brawl
      lethality: -10
      penetration: 4
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Brawl
    Fling:
      description: Level 2 Will spell
      is_magic: true
      skill: Will
      lethality: -15
      penetration: 3
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Natural Weaponry:
      description: Level 2 Nature spell
      is_magic: true
      skill: Brawl
      lethality: -10
      penetration: 4
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Brawl
    Sling Barb:
      description: Level 2 Nature spell
      is_magic: true
      skill: Nature
      lethality: -15
      penetration: 3
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
  #Level 3
    Earth Bolt:
      description: Level 3 Earth spell
      is_magic: true
      skill: Earth
      lethality: -10
      penetration: 4
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 2
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Stone Fists:
      description: Level 3 Earth spell
      is_magic: true
      skill: Brawl
      lethality: 0
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Brawl
    Flame Dart:
      description: Level 3 Fire spell
      is_magic: true
      skill: Fire
      lethality: -5
      penetration: 5
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Hot Hands:
      description: Level 3 Fire spell
      is_magic: true
      skill: Brawl
      lethality: -5
      penetration: 6
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 3
      init_mod: 0
      special_group: Brawl
    Ice Talons:
      description: Level 3 Water spell
      is_magic: true
      skill: Brawl
      lethality: -5
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Brawl
    Laser Zap:
      description: Level 3 Fire spell
      is_magic: true
      skill: Fire
      lethality: -5
      penetration: 5
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Mind Bolt:
      description: Level 3 Spirit spell
      is_magic: true
      skill: Spirit
      lethality: 0
      penetration: 0
      weapon_type: Suppressive
      is_automatic: true
      recoil: 0
      damage_type: Stun
      accuracy: 3
      init_mod: 0
      special_group: Spell
    Stone Slam:
      description: Level 3 Earth spell
      is_magic: true
      skill: Earth
      lethality: -5
      penetration: 5
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Thorn Growth:
      description: Level 3 Nature spell
      is_magic: true
      skill: Nature
      lethality: -10
      penetration: 4
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
  #Level 4
    Acid Spit:
      description: Level 4 Nature spell
      is_magic: true
      skill: Nature
      lethality: 0
      penetration: 7
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Breathless:
      description: Level 4 Air spell
      is_magic: true
      skill: Air
      lethality: -20
      penetration: 50
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Cone Of Cold:
      description: Level 4 Water spell
      is_magic: true
      skill: Water
      lethality: -5
      penetration: 6
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 0
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Exoskeleton:
      description: Level 4 Corpus spell
      is_magic: true
      skill: Melee
      lethality: 0
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Flame Burst:
      description: Level 4 Fire spell
      is_magic: true
      skill: Fire
      lethality: 0
      penetration: 7
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Ice Armor:
      description: Level 4 Water spell
      is_magic: true
      skill: Brawl
      lethality: 0
      penetration: 6
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Brawl
    Ice Blast:
      description: Level 4 Water spell
      is_magic: true
      skill: Water
      lethality: 15
      penetration: 5
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Jenu:
      description: Form for Half Shift spell
      is_magic: true
      skill: Athletics
      lethality: 5
      penetration: 5
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Brawl
    Lightning Bolt:
      description: Level 4 Air spell
      is_magic: true
      skill: Air
      lethality: 0
      penetration: 7
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Telekinetic Burst:
      description: Level 4 Will spell
      is_magic: true
      skill: Will
      lethality: -5
      penetration: 8
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Rock Skin:
      description: Level 4 Earth spell
      is_magic: true
      skill: Brawl
      lethality: 5
      penetration: 6
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Brawl
    Water Whip:
      description: Level 4 Water spell
      is_magic: true
      skill: Water
      lethality: 0
      penetration: 7
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
  #Level 5
    Blow Object:
      description: Level 5 Air spell
      is_magic: true
      skill: Air
      lethality: 12
      penetration: 9
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Earth Shudder:
      description: Level 5 Earth spell
      is_magic: true
      skill: Earth
      lethality: 0
      penetration: 0
      weapon_type: Suppressive
      is_automatic: true
      recoil: 0
      damage_type: Stun
      accuracy: 3
      init_mod: 0
      special_group: Spell
    Exploding Ice:
      description: Level 5 Water spell
      is_magic: true
      skill: Water
      lethality: 5
      penetration: 8
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 1
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Flares:
      description: Level 5 Fire spell
      is_magic: true
      skill: Fire
      lethality: 7
      penetration: 9
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      special_group: Spell
    Slick Ground:
      description: Level 5 Water spell
      is_magic: true
      skill: Water
      lethality: 0
      penetration: 0
      weapon_type: Suppressive
      is_automatic: true
      recoil: 0
      damage_type: Stun
      accuracy: 3
      init_mod: 0
      special_group: Spell
    Stalagmite:
      description: Level 5 Earth spell
      is_magic: true
      skill: Earth
      lethality: 10
      penetration: 10
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 1
      init_mod: 0
      special_group: Spell
    Telekinetic Crush:
      description: Level 5 Will spell
      is_magic: true
      skill: Will
      lethality: 6
      penetration: 10
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Vine Thrash:
      description: Level 5 Nature spell
      is_magic: true
      skill: Nature
      lethality: 10
      penetration: 7
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 1
      has_shrapnel: false
      init_mod: 0
      special_group: Spell
  #Level 6
    Demon Tails:
      description: Level 6 Corpus spell
      is_magic: true
      skill: Melee
      lethality: 12
      penetration: 10
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      has_shrapnel: true
      special_group: Melee
    Glacial Ice Armor:
      description: Level 6 Water spell
      is_magic: true
      skill: Brawl
      lethality: 10
      penetration: 8
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Iron Body:
      description: Level 6 Corpus spell
      is_magic: true
      skill: Brawl
      lethality: 5
      penetration: 6
      weapon_type: Melee
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Melee
    Mass Hemorrhage:
      description: Level 6 Corpus spell
      is_magic: true
      skill: Corpus
      lethality: -15
      penetration: 50
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Poison Puffs:
      description: Level 6 Nature spell
      is_magic: true
      skill: Nature
      lethality: -15
      penetration: 50
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Pyre:
      description: Level 6 Fire spell
      is_magic: true
      skill: Fire
      lethality: 15
      penetration: 12
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Shatter:
      description: Level 6 Ice spell
      is_magic: true
      skill: Water
      accuracy: 1
      lethality: 18
      penetration: 10
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      init_mod: 0
      special_group: Spell
    Stone Daggers:
      description: Level 6 Earth spell
      is_magic: true
      skill: Earth
      lethality: 15
      penetration: 12
      weapon_type: Ranged
      is_automatic: true
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
  #Level 7
    Exploding Earth:
      description: Level 7 Earth spell
      is_magic: true
      skill: Earth
      lethality: 15
      penetration: 13
      weapon_type: Explosive
      is_automatic: true
      recoil: 0
      damage_type: Stun
      accuracy: 1
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Ice Storm:
      description: Level 7 Water spell
      is_magic: true
      skill: Water
      lethality: 15
      penetration: 13
      weapon_type: Explosive
      is_automatic: true
      recoil: 0
      damage_type: Stun
      accuracy: 1
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Lightning Strike:
      description: Level 7 Air spell
      is_magic: true
      skill: Air
      lethality: 20
      penetration: 13
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
    Mass Telekinetic Burst:
      description: Level 7 Will spell
      is_magic: true
      skill: Will
      lethality: 15
      penetration: 13
      weapon_type: Explosive
      is_automatic: true
      recoil: 0
      damage_type: Stun
      accuracy: 1
      init_mod: 0
      special_group: Spell
    Suffocate:
      description: Level 7 Air spell
      is_magic: true
      skill: Air
      lethality: 5
      penetration: 50
      weapon_type: Ranged
      recoil: 0
      damage_type: Physical
      accuracy: 0
      init_mod: 0
      special_group: Spell
  #Level 8
    Firestorm:
      description: Level 8 Fire spell
      is_magic: true
      skill: Fire
      lethality: 45
      penetration: 20
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 4
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Land Of Ice:
      description: Level 8 Water spell
      is_magic: true
      skill: Water
      lethality: 45
      penetration: 20
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 4
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Massive Quake:
      description: Level 8 Earth spell
      is_magic: true
      skill: Earth
      lethality: 45
      penetration: 20
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 4
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
    Tempest:
      description: Level 8 Air spell
      is_magic: true
      skill: Air
      lethality: 45
      penetration: 2
      weapon_type: Explosive
      recoil: 0
      damage_type: Physical
      accuracy: 4
      has_shrapnel: true
      init_mod: 0
      special_group: Spell
