---
fs3skills:
  advantages_cost: 2
  allow_incapable_action_skills: false
  free_backgrounds: 6
  free_languages: 3
  max_ap: 40
  max_attr_rating: 4
  max_attrs_at_or_above:
    '3': 4
    '4': 2
  max_points_on_action: 28
  max_points_on_advantages: 12
  max_points_on_attrs: 12
  max_skill_rating: 7
  max_skills_at_or_above:
    '5': 3
    '6': 2
    '7': 1
  min_backgrounds: 2
  starting_skills:
    Everyone:
      skills:
        Alertness: 2
        Athletics: 2
        Composure: 2
        Firearms: 2
        Medicine: 2
        Melee: 2
        Standard: 3
  unusual_skills:
  - Celtan
  - Scorpian
  - Sagittaran
  - Gemenese
  - Demolitions
