---
fs3skills:
  allow_advantages_xp: false
  days_between_learning: 30
  dots_beyond_chargen_max: 17
  max_xp_hoard: 12
  periodic_xp: 3
  skills_requiring_training:
  - Archery
  - Brawl
  - Firearms
  - Medicine
  - Melee
  xp_costs:
    language:
      '0': 1
      '1': 4
      '2': 12
    action:
      '0': 1
      '1': 1
      '2': 2
      '3': 3
      '4': 6
      '5': 8
      '6': 8
      '7': 12
    background:
      '0': 1
      '1': 4
      '2': 8
    attribute:
      '1': 1
      '2': 4
      '3': 8
    advantages:
      '0': 1
      '1': 4
      '2': 12
  xp_cron:
    day_of_week:
    - Sat
    hour:
    - 4
    minute:
    - 0
  attr_dots_beyond_chargen_max: 17
  action_dots_beyond_chargen_max: 17
