---
idle:
  arrivals_category: New Arrivals
  days_before_idle: 21
  default_contact: Admin
  idle_category: Announcements
  idle_exempt_roles:
  - admin
  - builder
  - coder
  - guest
  monthly_reminder: It's time to run the idle sweep. Don't forget to deal with any
    rooms that reaped characters may have owned, and check their secrets for possible
    re-use.
  monthly_reminder_cron:
    date:
    - 1
    - 15
    hour:
    - 01
    minute:
    - 0
  monthly_reminder_title: Idle Sweep
  reminder_category: MISC
  roster_welcome_msg: Welcome!  You may wish to check your %xcnotes%xn and web portal
    profile page for any notes left by the prior player.  Check out the [Getting Started](/wiki/getting_started) guide for some tips on getting started on Spirit Lake.
  roster_fields:
  - field: name
    width: 20
    title: Name
  - field: demographic
    width: 10
    title: Gender
    value: gender
  - field: group
    width: 17
    title: Major School
    value: Major School
  - field: group
    width: 17
    title: Minor School
    value: Minor School
  shortcuts:
    idle/add: idle/action
    roster/update: roster/add
    roster/contact: roster/add
    roster/notes: roster/note
    idle/notes: idle/note
  use_roster: true
  idle_warn_msg: You haven't played in awhile and your character is in danger of idling
    out.
