---
jobs:
  active_statuses:
  - NEW
  - OPEN
  - ASANA
  archive_cron:
    day_of_week:
    - Sun
    hour:
    - 4
    minute:
    - 18
  archive_job_days: 10
  archived_status: ARCHIVED
  categories:
    APP:
      color: "%xm"
      roles:
      - app staff
    BUILD:
      color: "%xr"
      roles:
      - builder
    BUG:
      color: "%xy"
      roles:
      - coder
    CODE:
      color: "%xy"
      roles:
      - coder
    ALERT:
      color: "%xy"
    LH:
      color: "%x38"
      roles:
      - storyteller
    MISC:
      color: "%xh"
    PLOT:
      color: "%xc"
      roles:
      - storyteller
    PRP:
      color: "%x32"
      roles:
      - storyteller
    REQ:
      color: "%xw"
    SYS:
      color: "%xh"
    SPELL:
      color: "%xb"
      roles:
      - storyteller
    LUCK:
      color: "%xc"
      roles:
      - storyteller
    PLAYER:
      color: "%xy"
  closed_status: DONE
  closed_statuses:
  - DONE
  - ARCHIVED
  default_status: NEW
  luck_category: LUCK
  open_status: OPEN
  request_category: REQ
  shortcuts:
    jobs/mine: job/filter mine
    jobs/active: job/filter active
    jobs: job
    requests: request
    request/comment: request/respond
    job/comment: job/discuss
    job/submit: job/create
    job/reply: job/respond
    job/open: job/handle
    job/mine: job/filter mine
    job/active: job/filter active
    job/deletecomment: job/deletereply
    job/all: job/filter all
    request/all: request/filter all
    request/active: request/filter active
    job/unread: job/filter unread
  status:
    NEW:
      color: "%xg"
    OPEN:
      color: "%xb"
    HOLD:
      color: "%xx%xh"
    ASANA:
      color: "%xm"
    DONE:
      color: "%xy"
    ARCHIVED:
      color: "%xx%xh"
  system_category: SYS
  trouble_category: ALERT
  permissions:
    access_jobs: Allows non-admins to access jobs in categories allowed for their
      roles.
  responses:
  - name: Welcome Basket What Potion
    text: Sure, let me know what 'for fun' potion you'd like from the list in the [welcome basket page](https://spiritlakemu.com/wiki/welcome_basket).
  - name: Welcome Basket Recieved
    text: "Potions added! Type `potions` to see them in your potion inventory, and see `help potions` for more help.\n\nYou are now in possession of a [Welcome Basket](https://spiritlakemu.com/wiki/welcome_basket). The small gift basket has been artfully arranged and filled with a small variety of local goods such as hand cream and lip balm. Several potions are tucked in as well, including a Medium Heal potion, a Telekinetic Armor potion, and one labeled 'Just for Fun!' It also holds reading material filled with important information about getting involved in the Weird:\n\n
      * A welcome pamphlet from the Council containing the [magical charter](https://spiritlakemu.com/wiki/weird_docs:charter) by which all mages must abide.\n
      * A spiral-bound printed edition of the most current [Guide to the Weird](https://spiritlakemu.com/wiki/weird_docs:a_guide_to_the_weird_2nd_ed), as well as the [Magical Primer](https://spiritlakemu.com/wiki/weird_docs:magic_primer_and_spellbook).\n\nBe sure to check out the reading, as it will offer a lot of helpful information, which you now have ICly."
