---
jobs:
  categories:
    APP:
      color: "%xm"
      roles:
      - app staff
    BUILD:
      color: "%xr"
      roles:
      - builder
    BUG:
      color: "%xy"
      roles:
      - coder
    CODE:
      color: "%xy"
      roles:
      - coder
    ALERT:
      color: "%xy"
    MISC:
      color: "%xh"
    PLOT:
      color: "%xc"
      roles:
      - storyteller
    REQ:
      color: "%xw"
    SECRET:
      color: "%xc"
      roles:
      - storyteller
    SYS:
      color: "%xh"
    SPELL:
      color: "%xb"
      roles:
      - storyteller
    LUCK:
      color: "%xc"
      roles:
      - storyteller
    PLAYER:
      color: "%xy"
  closed_status: DONE
  default_status: NEW
  luck_category: LUCK
  request_category: REQ
  shortcuts:
    jobs/mine: job/filter mine
    jobs/active: job/filter active
    jobs: job
    requests: request
    request/comment: request/respond
    job/comment: job/discuss
    job/submit: job/create
    job/reply: job/respond
    job/open: job/handle
    job/mine: job/filter mine
    job/active: job/filter active
    job/deletecomment: job/deletereply
  status:
    NEW:
      color: "%xg"
    OPEN:
      color: "%xb"
    HOLD:
      color: "%xx%xh"
    DONE:
      color: "%xy"
  system_category: SYS
  trouble_category: ALERT
