locale:

    # Main language (aka locale).  en for English.  The name should match the locale
    # names in the game/locales folder.
    locale: en

    # Backup language (aka locale) if text is not available in the main language.
    # For instance if you're running a game in Spanish, and a plugin is not
    # translated, it will use the English (en) text as a backup.
    default_locale: en
