# You probably won't want to edit most of this, except to change the level 
# to DEBUG (for debugging) or INFO (for normal operation)
logger:

  # define all loggers ...
  loggers:
    - name      : ares
      level     : DEBUG
      trace     : 'true'
      outputters:
        - stdout
        - file

  # define all outputters (incl. formatters)      
  outputters:
      - type     : StdoutOutputter
        name     : stdout
        formatter:
          date_pattern: '%Y-%m-%d %H:%M:%S'
          pattern     : '%d %l - %M '
          type        : PatternFormatter
      - type     : RollingFileOutputter
        name     : file
        max_backups : '5'
        maxtime : '86400'
        filename : 'game/logs/log.txt'
        formatter:
          date_pattern: '%Y-%m-%d %H:%M:%S'
          pattern     : '%d %l - %M '
          type        : PatternFormatter      