login:    
    
    allow_web_registration: true
    
    guest_role: "guest"
    
    use_terms_of_service: true

    activity_cron:
        minute: 
            - 00
            
    blacklist_cron:
        day:
            - 15
        hour: 
            - 03
        minute: 
            - 00
                    
    shortcuts:
        "logout" : "quit"
        "con" : "connect"
        "newpassword": "password/reset"
        "conn": "connect"
        "kick": "boot"
        "password/change" : "password/set"
