---
login:
  activity_cron:
    minute:
    - 0
  allow_creation: false
  allow_web_registration: false
  blacklist_cron:
    day:
    - 1
    - 15
    hour:
    - 3
    minute:
    - 0
  creation_not_allowed_message: Sorry, Spirit Lake is full. Watch the website to see
    when we're accepting applications again.
  guest_role: guest
  login_not_allowed_message: Logins for unapproved characters is turned off at the
    moment. Come back later!
  shortcuts:
    logout: quit
    con: connect
    newpassword: password/reset
    conn: connect
    kick: boot
    password/change: password/set
    pcreate: create/reserve
    motd: notice/motd
  use_terms_of_service: false
  portal_requires_registration: false
  guest_disabled_message: ''
