---
login:
  allow_web_registration: true
  guest_role: guest
  use_terms_of_service: false
  activity_cron:
    minute:
    - 0
  blacklist_cron:
    day:
    - 1
    - 15
    hour:
    - 3
    minute:
    - 0
  notice_cleanup_cron:
    # day:
    # - 18
    hour:
    - 07
    minute:
    - 27
  notice_timeout_days: 7
  shortcuts:
    logout: quit
    con: connect
    newpassword: password/reset
    conn: connect
    kick: boot
    password/change: password/set
    motd: notice/motd
  allow_creation: true
  login_not_allowed_message: "Logins for unapproved characters is turned off at the moment, as Spirit Lake is currently full.  Watch the website to see when we're accepting applications again."
  creation_not_allowed_message: "Sorry, Spirit Lake is full. Watch the website to see when we're accepting applications again."
  portal_requires_registration:
  guest_disabled_message: "Sorry, Spirit Lake is full. Watch the website to see when we're accepting applications again."
