---
magic:
  shield_cron:
    hour:
    - 02
    minute:
    - 01
  potion_cron:
    minute:
    - 00
  shortcuts:
    combat/cast: combat/spell
    cast: spell/cast
  lore_hook_prefs:
    None: No Lore Hook at all
    Item: A magical item comes into your posession.
    Pet: A magical creature takes a shine to you and decides to stay.
    Ancestry: Somewhere in your family tree, your bloodline became crossed with that of a Magical Creature.
    Storyteller: Let Storytellers decide your Lore Hook.
  achievements:
    potions_made:
      type: potion
      message: Made %{count} potions.
    potions_used:
      type: potion
      message: Used %{count} potions.
    spells_learned:
      type: spell
      message: Learned %{count} spells.
    spells_discarded:
      type: spell
      message: Discarded %{count} spells.
    spells_cast:
      type: spell
      message: Cast %{count} spells.
    equipped_magic_item:
      type: spell
      message: "Equipped a magic item."
