---
randomscene:
  scenarios:
  - "A moose has wandered into town."
  - "That baby is really cute."
  - "That smells delicious."
  - "Proposal."
  - "Medical emergency."
  - "The lights have gone out."
  - "Get lost."
  - "Officer, that's not mine."
  - "Sirens wail in the distance"
  - "Is it me, or has it suddenly gone cold in here?"
  - "Letters from home."
  - "A weird smell is coming from the alley."
  - "Too rich for my blood."
  - "Hey gorgeous"
  - "Wishing star."
  - "A case of mistaken identity."
  - "This line is long."
  - "Unseasonal weather"
  - "This place is filthy."
  - "Lost bet."
  - "An alarm sounds somewhere."
  - "This cop is obviously drunk."
  - "Too much nature."
  - "Decorating."
  - "This routine job just got a hell of a lot less routine."
  - "What movie are you watching?"
  - "I think my computer was just hacked."
  - "It caught on fire!"
  - "A pipe is leaking."
  - "Uncontrollable laughter."
  - "Roadblock"
  - "Ripoff."
  


  npcs:
  - "A bachelorette party"
  - "A belligerent student"
  - "A dashing amputee"
  - "A delighted tourist"
  - "A lost child"
  - "A naive tourist"
  - "A pair of affectionate lovers"
  - "A pair of teenaged twins"
  - "A pamphlet-sporting activist"
  - "A posturing teen bully"
  - "A professional dogwalker"
  - "A self-proclaimed brilliant poet"
  - "A small calico kitten"
  - "A snooty waiter"
  - "A survey-taker"
  - "An elementary school field trip"
  - "An escaped dog"
  - "An excited street artist"
  - "An improv basketball team"
  - "An overexcited antiques dealer"
  - "An overwhelmed instructor"
  - "One of the bartenders"
  - "A cynical local"
  - "A snobbish realtor"
  - "A harried park ranger"
  actions:
  - "picks a pocket"
  - "gets into a fist fight"
  - "flips out at their companion"
  - "stalks"
  - "debuts an aria"
  - "hosts a dance contest"
  - "releases an unlikely animal"
  - "intercepts a scandalous communication"
  - "loses his/her last dollar"
  - "paints graffitti"
  - "runs out on his/her bill"
  - "insults a grouchy passerby"
  - "flirts outrageously"
  - "headbutts a dudebro"
  - "has food poisoning"
  - "is caught cheating at cards"
  - "blocks access to transportation"
  - "breaks into a business"
  - "breaks up a fight"
  - "creates a distraction for a shoplifter"
  - "does interpretive dance"
  - "faints dramatically"
  - "flees"
  - "gives you attitude"
  - "has a stalker"
  - "is begging for food"
  - "is dying to use a restroom"
  - "is getting handsy"
  - "is in an advertisement"
  - "is lost"
  - "keeps screaming"
  - "makes public displays of affection"
  - "mistakes you for someone else"
  - "plays instruments for money"
  - "preaches their religion"
  - "refuses to leave"
  - "refuses to pay"
  - "sets a fire"
  - "spills his/her groceries"
  - "tries to hire you"
  - "wants you to sign a petition"
  - "won't stop hitting on you"
  - "can't control his/her dog"
  - "drops his/her coffee"
  - "litters"
  words:
  - "adorable"
  - "adventurous"
  - "aggressive"
  - "agreeable"
  - "alert"
  - "amused"
  - "angry"
  - "annoyed"
  - "anxious"
  - "arrogant"
  - "ashamed"
  - "attractive"
  - "awful"
  - "approve"
  - "accept"
  - "accuse"
  - "act"
  - "admire"
  - "admit"
  - "agree"
  - "alert"
  - "answer"
  - "argue"
  - "arrange"
  - "ask"
  - "attack"
  - "avoid"
  - "beautiful"
  - "bewildered"
  - "bloody"
  - "brooding"
  - "bored"
  - "blushing"
  - "busy"
  - "barrel roll"
  - "baste"
  - "believe"
  - "break"
  - "build"
  - "burn"
  - "buy"
  - "before"
  - "bullied"
  - "bill"
  - "calm"
  - "careful"
  - "cautious"
  - "charming"
  - "cheerful"
  - "clever"
  - "comfortable"
  - "combative"
  - "concerned"
  - "cooperative"
  - "courageous"
  - "crazy"
  - "creepy"
  - "crowded"
  - "cruel"
  - "curious"
  - "call"
  - "capable"
  - "carry"
  - "change"
  - "choose"
  - "clean"
  - "climb"
  - "collect"
  - "commit"
  - "compare"
  - "complain"
  - "confess"
  - "consider"
  - "contribute"
  - "control"
  - "cook"
  - "copy"
  - "correct"
  - "cry"
  - "crush"
  - "dangerous"
  - "dark"
  - "defiant"
  - "delighted"
  - "depressed"
  - "determined"
  - "disgusted"
  - "disturbed"
  - "dispossessed"
  - "dizzy"
  - "doubtful"
  - "damage"
  - "dance"
  - "deal"
  - "demand"
  - "deliver"
  - "deny"
  - "describe"
  - "discover"
  - "disorder"
  - "drink"
  - "drive"
  - "drudge"
  - "eager"
  - "easy"
  - "embarrassed"
  - "energetic"
  - "enthusiastic"
  - "envious"
  - "evil"
  - "excited"
  - "expensive"
  - "eat"
  - "enable"
  - "encourage"
  - "enjoy"
  - "examine"
  - "explain"
  - "fair"
  - "faithful"
  - "famous"
  - "fancy"
  - "fierce"
  - "foolish"
  - "fragile"
  - "friendly"
  - "frightened"
  - "fail"
  - "fall"
  - "fight"
  - "find"
  - "fix"
  - "fly"
  - "future"
  - "feeble"
  - "follow"
  - "force"
  - "forget"
  - "forgive"
  - "gentle"
  - "glamorous"
  - "good"
  - "graceful"
  - "grieving"
  - "grotesque"
  - "grumpy"
  - "give"
  - "happy"
  - "helpless"
  - "hilarious"
  - "hate"
  - "help"
  - "hide"
  - "hit"
  - "hope"
  - "hurt"
  - "impossible"
  - "innocent"
  - "inquisitive"
  - "itchy"
  - "identify"
  - "imagine"
  - "improve"
  - "influence"
  - "inform"
  - "idolize"
  - "introduce"
  - "invite"
  - "jealous"
  - "jittery"
  - "join"
  - "jump"
  - "kick"
  - "kill"
  - "knock"
  - "lazy"
  - "lonely"
  - "lucky"
  - "laugh"
  - "lead"
  - "learn"
  - "leave"
  - "lend"
  - "link"
  - "listen"
  - "lecture"
  - "lose"
  - "love"
  - "massage"
  - "message"
  - "mesmerize"
  - "modern"
  - "muddy"
  - "mysterious"
  - "make"
  - "middle"
  - "mettle"
  - "meddle"
  - "muster"
  - "miss"
  - "move"
  - "naughty"
  - "nervous"
  - "nice"
  - "no"
  - "nutty"
  - "need"
  - "notice"
  - "noble"
  - "nonsense"
  - "obedient"
  - "obnoxious"
  - "old-fashioned"
  - "outrageous"
  - "obtain"
  - "offer"
  - "optimistic"
  - "panic"
  - "poise"
  - "pleasant"
  - "poor"
  - "powerful"
  - "precious"
  - "pretend"
  - "prickly"
  - "proud"
  - "puzzled"
  - "pass"
  - "past"
  - "perform"
  - "pay"
  - "pick"
  - "plan"
  - "play"
  - "promise"
  - "prove"
  - "present"
  - "quaint"
  - "qualm"
  - "quizzical"
  - "quiet"
  - "quash"
  - "rage"
  - "relieved"
  - "repulsive"
  - "rich"
  - "read"
  - "realize"
  - "recognize"
  - "reflect"
  - "remember"
  - "repeat"
  - "replace"
  - "reply"
  - "report"
  - "represent"
  - "reveal"
  - "religious"
  - "romantic"
  - "run"
  - "scary"
  - "search"
  - "selfish"
  - "sexy"
  - "shy"
  - "silly"
  - "sore"
  - "stormy"
  - "strange"
  - "save"
  - "sass"
  - "sell"
  - "send"
  - "serene"
  - "sensual"
  - "serve"
  - "share"
  - "shoot"
  - "show"
  - "sing"
  - "sleep"
  - "slink"
  - "slick"
  - "smile"
  - "stand"
  - "start"
  - "stay"
  - "steal"
  - "stop"
  - "study"
  - "succeed"
  - "suffer"
  - "suggest"
  - "suit"
  - "support"
  - "supply"
  - "survive"
  - "take"
  - "talented"
  - "tart"
  - "tender"
  - "tense"
  - "testy"
  - "thankful"
  - "thoughtful"
  - "thoughtless"
  - "tired"
  - "tough"
  - "troubled"
  - "take"
  - "teach"
  - "tell"
  - "tend"
  - "test"
  - "thank"
  - "think"
  - "throw"
  - "timing"
  - "touch"
  - "train"
  - "travel"
  - "treat"
  - "try"
  - "uncertain"
  - "uninterested"
  - "united"
  - "undone"
  - "useless"
  - "twitch"
  - "victorious"
  - "visual"
  - "vying"
  - "vocal"
  - "visit"
  - "vent"
  - "vote"
  - "violation"
  - "vital"
  - "vibrate"
  - "viral"
  - "voyeur"
  - "vacant"
  - "vapid"
  - "wander"
  - "weary"
  - "wicked"
  - "wild"
  - "witty"
  - "wrong"
  - "wait"
  - "walk"
  - "want"
  - "warn"
  - "wash"
  - "wear"
  - "win"
  - "wish"
  - "wonder"
  - "worry"
  - "write"
  - "yes"
