---
roles:
  admin_list_roles:
  - admin
  - app staff
  - storyteller
  default_roles:
  - everyone
  restricted_roles:
  - admin
  - coder
  shortcuts:
    roles: role
    staff: admin
    role/add: role/assign
