---
scenes:
  achievements:
    word_count:
      type: story
      message: Wrote %{count} words in scenes.
    scene_participant:
      type: story
      message: Participated in %{count} scenes.
  delete_unshared_scenes: false
  idle_scene_timeout_days: 4
  include_pose_separator: false
  ooc_color: "%xc"
  related_scenes_filter_days: 90
  room_cleanup_cron:
    minute:
    - 15
    - 45
  scene_types:
  - Social
  - Event
  - Vignette
  shortcuts:
    scenes: scene
    scene/close: scene/stop
    scene/date: scene/icdate
    scene/end: scene/stop
    scene/name: scene/title
    scene/info: scene
    scene/rename: scene/title
    repose/log: repose/all
    repose/reset: repose/clear
    repose/gag: repose/nudge mute
    logs: scene
    log/on: scene/startlog
    log/off: scene/stoplog
    log/clear: scene/clearlog
    log/undo: scene/undo
    scene/proxy: scene/spoof
    scene/amend: scene/replace
    pose/undo: scene/undo
    pose/replace: scene/replace
    scene/deletechar: scene/removechar
    pose/notify: pose/nudge
    pose/remove: pose/drop
    po: pose
    me: pose
    sya: say
    repose/nudge: pose/nudge
    repose/notify: pose/notify
    repose/drop: pose/drop
    repose/order: pose/order
    repose: scene/repose
    scene/set: emit/set
    posebreak: autospace
    pose/skip: pose/drop
    scene/addpose: scene/emit
    scene/pose: scene/emit
    scene/mine: scene/unshared
  trending_scenes_category: Trending Scenes
  trending_scenes_cron:
    hour:
    - 19
    minute:
    - 15
    day_of_week:
    - Mon
  unshared_scene_cleanup_cron:
    day_of_week:
    - Fri
    hour:
    - 22
    minute:
    - 2
  unshared_scene_deletion_days: 20
  unshared_scene_warning_days: 13
  use_custom_char_cards: false
  permissions:
    control_npcs: Pose from NPCs in scenes.
    manage_scenes: Can use scene-related admin tools, like stopping or unsharing scenes.
