---
scenes:
  achievements:
    word_count:
      type: story
      message: Wrote %{count} words in scenes.
      levels:
      - 1000
      - 2000
      - 5000
      - 10000
      - 25000
      - 50000
      - 100000
      - 250000
      - 500000
      - 750000
      - 1000000
      - 1250000
      - 1500000
      - 1750000
      - 2000000
      - 2250000
      - 2500000
      - 2750000
      - 3000000
    scene_participant:
      type: story
      message: Participated in %{count} scenes.
      levels:
      - 1
      - 10
      - 20
      - 50
      - 100
      - 200
      - 300
      - 400
      - 500
      - 600
      - 700
      - 800
      - 900
      - 1000
      - 1500
      - 2000
      - 2500
      - 3000
      - 3500
      - 4000
      - 4500
      - 5000
  content_warnings:
  - graphic violence
  - sexual assault
  - nsfw
  - self-harm
  - suicide
  - bigotry
  - torture
  delete_unshared_scenes: true
  idle_scene_timeout_days: 4
  include_pose_separator: false
  ooc_color: "%xc"
  permissions:
    control_npcs: Pose from NPCs in scenes.
    manage_scenes: Can use scene-related admin tools, like stopping or unsharing scenes.
  delete_scenes_on_idle_out: false
  related_scenes_filter_days: 90
  room_cleanup_cron:
    minute:
    - 15
    - 45
  scene_trash_timeout_days: 14
  scene_types:
  - Social
  - Event
  - Vignette
  shortcuts:
    scenes: scene
    scene/close: scene/stop
    scene/date: scene/icdate
    scene/end: scene/stop
    scene/name: scene/title
    scene/info: scene
    scene/rename: scene/title
    repose/log: repose/all
    repose/reset: repose/clear
    repose/gag: repose/nudge mute
    logs: scene
    log/undo: scene/undo
    scene/proxy: scene/spoof
    scene/amend: scene/replace
    pose/undo: scene/undo
    pose/replace: scene/replace
    scene/deletechar: scene/removechar
    pose/notify: pose/nudge
    pose/remove: pose/drop
    po: pose
    me: pose
    sya: say
    repose/nudge: pose/nudge
    repose/notify: pose/notify
    repose/drop: pose/drop
    repose/order: pose/order
    repose: scene/repose
    scene/set: emit/set
    posebreak: autospace
    pose/skip: pose/drop
    scene/addpose: scene/emit
    scene/pose: scene/emit
    scene/mine: scene/unshared
    scene/create: scene/start
  trending_scenes_category: Trending Scenes
  trending_scenes_cron:
    hour:
    - 19
    minute:
    - 15
    day_of_week:
    - Mon
  unshared_scene_cleanup_cron:
    day_of_week:
    - Fri
    hour:
    - 22
    minute:
    - 2
  unshared_scene_warning_days: 30
  use_custom_char_cards: false
