server:
    # The host name where your game is running (typically localhost)
    hostname: localhost

    # The port number your game will listen on
    port: 7207
    
    # Name of your game.
    name: AresCentral

    # Please select the appropriate category to describe your game:
    # "Historical", "Sci-Fi", "Fantasy", "Modern", "Supernatural", "Social", "Other"
    category: "Social"
    
    # Describe your game.  You may use ansi and other MUSH formatting codes.
    description: "Social hub for all things AresMUSH."