server:
    # The host name for your game.
    hostname: localhost

    # The port number your game will listen on
    port: 7207
    
    # Name of your game.
    name: AresTest

    # Please select the appropriate category to describe your game:
    # "Historical", "Sci-Fi", "Fantasy", "Modern", "Supernatural", "Social", "Other"
    category: Social
    
    # Describe your game.  You may use ansi and other MUSH formatting codes (%r, etc.).
    description: Test site.
    
    # Your game's website
    website: www.aresmush.com