server:
    # The host name for your game.
    hostname: localhost

    # The port number your game will listen on
    port: 4201
    
    # These two ports are used for the game's web interface.  
    # The web server port is the one you connect to directly.  80 is the standard web port, but 
    # that might not be available on some systems.  8181 is usually safe.
    # The web socket port is the one the web client connects to.  It must be different than
    # both the web server and regular port.
    websocket_port: 4202
    webserver_port: 8181