skin:
    
    # Here you can define the lines that are used in numerous commands.
    # You can have as many lines as you wish and use them in your template files, but
    # line1 through line4 have shortcuts that can be used in any poses, text, templates
    # as %l1, %l2, %l3, %l4
    line1: "%x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn"
    line2: "%x!------------------------------------------------------------------------------%xn"
    line3: "%x!----[AresMUSH]----------------------------------------------------------------%xn"
    line4: "%x!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~%xn"
    
    # This confiures the line_with_text() function in code.  You pass in a string, which will
    # be centered to 'width' chars using 'padding', surrounded by the spacers,
    # and put where the word 'text' appears.  You can move the word 'text' around but be sure
    # to leave them in there or it won't work.
    line_with_text: 
        template: "%x!----text-----------------------------------------------%xn"
        padding: "-"
        width: 20
        left_spacer: "["
        right_spacer: "]"