spells:
  #Level 1
  Beginner Telekinesis:
    available: true
    casting_time: 1 round, plus additional rounds to manipulate at GM's discretion
    desc: The caster is able to slowly lift and manipulate 1 pound of material almost as if with their hands. This manipulation is not precise and cannot travel above 2 mph.
    duration: 10 minutes
    effect: Other
    level: 1
    line_of_sight: true
    name: Beginner Telekinesis
    range: Short
    roll: Will
    school: Will
  Deface:
    available: true
    casting_time: 1 round
    desc: "Make simple or cosmetic damage to an object.   \n\n For example, cause a one inch rip or crack, add a small spot of tarnish or dirt, or make a scratch of no more than a few inches."
    effect: Creation
    is_potion: true
    level: 1
    name: Deface
    range: Touch
    roll: Will
    school: Will
  Mend:
    available: true
    casting_time: 1 round
    desc: "Make simple or cosmetic repairs on an object.\n\nFor example, repair a one inch rip or crack, remove a small spot of tarnish or dirt, or fix a scratch of no more than a few inches."
    effect: Creation
    is_potion: true
    level: 1
    name: Mend
    range: Touch
    roll: Will
    school: Will
  #Level 2
  Fling:
    available: true
    casting_time: 1 round
    desc: Fling a small object under half a pound at a target.
    effect: Damage
    fs3_attack: true
    level: 2
    line_of_sight: true
    name: Fling
    range: Short
    school: Will
    target_num: 1
    target_optional: true
    weapon: Fling
    effect: Damage
  Minor Telekinesis:
    available: true
    casting_time: 1 round, plus additional rounds to manipulate at GM's discretion
    desc: The caster is able to slowly lift and manipulate 5 pounds of material almost as if with their hands. This manipulation is not precise and cannot travel above 10 mph.
    duration: 1 hour
    effect: Other
    level: 2
    name: Minor Telekinesis
    range: Short
    roll: Will
    school: Will
  Nudge Aim:
    available: true
    casting_time: 1 round
    desc: Telekinetically shove a single opponent's weapon, making it difficult for them to aim.
    effect: Debuff
    fs3_attack: false
    level: 2
    line_of_sight: true
    name: Nudge Aim
    range: Short
    rounds: 1
    school: Will
    target_num: 1
    target_optional: true
    effect: Debuff
    attack_mod: -1
  #Level 3
  Intermediate Telekinesis:
    available: true
    casting_time: 1 round, plus additional rounds for movement at the GM's discretion
    desc: The caster can lift and move an object weighing up to 100 lbs at will from a distance. This manipulation is not precise and cannot travel above 25 mph.
    duration: 1 hour
    effect: Other
    level: 3
    name: 'Intermediate Telekinesis '
    range: Short
    roll: Will
    school: Will
  Telekinetic Block:
    available: true
    casting_time: 1 round
    desc: 'Deflect attacks directed against you or a single comrade with a telekinetic wall, effectively putting the target in [cover](https://www.aresmush.com/fs3/fs3-3/combat/#stance).'
    duration: 3 rounds
    effect: Defense
    level: 3
    line_of_sight: true
    name: 'Telekinetic Block '
    range: Short
    rounds: 3
    school: Will
    stance: cover
    target_num: 1
    target_optional: true
  Telekinetic Hold:
    available: true
    casting_time: 1 round
    desc: Subdue an enemy with telekinetic strength, disabling them for one round.
    duration: 1 round
    effect: Stun
    fs3_attack: true
    is_stun: true
    rounds: 1
    level: 3
    line_of_sight: true
    name: Telekinetic Hold
    range: Short
    school: Will
    target_num: 1
    target_optional: true
    weapon: Stun (Will)
  #Level 4
  Alter Object:
    available: false
    casting_time: 1 round
    duration: 10 minutes
    desc: "For the duration of the spell, the caster can reshape up to 2 cubic feet of non-living material. The caster can make simple, non-weaponized shapes that animate at their direction out of the material. The density and composition of the material does not change, but its rough shape can be altered, which also allows for repairs or damage to an object. Material returns to its natural, but not necessarily original, state when the spell ends.\n\nIn combat, damaging a weapon enough to disable it takes 3-5 rounds, at the GM's discretion."
    effect: Creation
    is_potion: false
    level: 4
    name: Alter Object
    range: Short
    roll: Will
    school: Will
  Major Telekinesis:
    available: true
    casting_time: 1 round, plus additional rounds for movement at the GM's discretion
    desc: The caster can lift and move an object or person weighing up to 250 lbs at will from a distance. This manipulation is not precise and cannot travel above 35 mph.
    duration: 1 hour
    effect: Other
    level: 4
    name: 'Major Telekinesis '
    range: Short
    roll: true
    school: Will
  Potions (Will):
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    effect: Other
    level: 4
    name: Potions (Will)
    school: Will
    available: true
  Telekinetic Armor:
    armor: Telekinetic
    available: true
    casting_time: 1 round
    desc: A telekinetic shield envelops the caster's body, acting as armor.
    duration: 3 hours
    effect: Armor
    is_potion: true
    level: 4
    name: Telekinetic Armor
    range: Self
    school: Will
  Telekinetic Burst:
    available: true
    casting_time: 1 round
    desc: The caster lashes out with a blunt telekinetic attack, dealing damage to an opponent. On a hit, the opponent is pushed backwards 1-10 ft.
    effect: Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Telekinetic Burst
    range: Short
    school: Will
    target_num: 1
    target_optional: true
    weapon: Telekinetic Burst
  Transform Weapon:
    available: true
    casting_time: 1 round
    desc: Transform any weapon into a more powerful version of itself.
    duration: 3 hours
    effect: Buff
    is_potion: true
    level: 4
    name: Transform Weapon
    range: Touch
    rounds: 100
    school: Will
    weapon_specials: Transform
    weapon: Spell
  #LEVEL 5
  Group Telekinetic Block:
    available: true
    casting_time: 1 round
    desc: "Deflect attacks directed against up to three targets with a telekinetic wall, effectively putting the targets in [cover](https://www.aresmush.com/fs3/fs3-3/combat/#stance)."
    duration: 4 rounds
    effect: Defense
    level: 5
    line_of_sight: true
    name: 'Group Telekinetic Block '
    range: Long
    rounds: 4
    school: Will
    stance: cover
    target_num: 3
    target_optional: true
  Multiple Telekinesis:
    area: 15 yard radius
    available: true
    casting_time: 1 round, plus additional rounds for movement at the GM's discretion
    desc: 'The caster can lift and move up to five objects weighing up to 100 lbs total. The more items they manipulate, the less precise their manipulation is. A single item can be manipulated with good precision, but manipulating three items is imprecise, and more than three items can only be manipulated with rudimentary control such as broad movements through the air. Objects cannot be smaller than 5cm or travel above 25 mph.'
    duration: 1 hour
    effect: Other
    level: 5
    name: Multiple Telekinesis
    range: Short
    roll: true
    school: Will
  Telekinetic Precision:
    available: true
    casting_time: 1 round, plus additional rounds to manipulate at GM's discretion
    desc: "The caster can manipulate a small object with great precision. Objects may range in size from 1 mm  to 5 cm.\n\n Manipulation requires knowledge. The caster cannot use telekinesis to pick locks without lockpicking knowledge, or to load a gun without firearms knowledge."
    duration: 1 hour
    effect: Other
    level: 5
    name: 'Telekinetic Precision '
    range: Short
    roll: true
    school: Will
  #LEVEL 6
  Familiar (Will):
    desc: "A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. \n\nFamiliars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles."
    effect: Other
    level: 6
    name: Familiar (Will)
    roll: true
    school: Will
    casting_time: 3 hours
    range: Short
    line_of_sight: true
    available: true
  Massive Telekinesis:
    area: 15 yard radius
    available: true
    casting_time: 1 round, plus additional rounds for movement at the GM's discretion
    desc: 'The caster can move an object weighing up to 5 tons. This is imprecise, and objects move at a speed inverse to their weight. Smaller objects may move up to 35 mph; larger objects move 15 mph.'
    duration: 1 hour
    effect: Other
    level: 6
    name: 'Massive Telekinesis '
    range: Long
    roll: Will
    school: Will
  Transmutation Armor:
    armor: Transmutation
    available: false
    casting_time: 1 round
    desc: Transforms the caster's clothing into formidable armor.
    duration: 8 hours
    effect: Armor
    level: 6
    name: Transmutation Armor
    notes: This probably shouldn't cover the whole body? Maybe a use for armor specials.
    range: Self
    school: Will
  #LEVEL 7
  Being of Force:
    area: 15 yard radius
    available: false
    casting_time: 10 minutes, plus additional rounds for commands
    desc: "The caster creates a being of pure Will. The being is capable of any Will abilities of level 5 or below. It can be actively directed by its master via a short command of up to four words. A command is in effect until countered by the caster or until the being is dispelled or defeated. Giving a new command takes a turn.\n\nWhile active, the being requires a significant amount of Will energy, and its creator casts Will spells with a -1 modifier.\n\n In combat, the being should be represented by an NPC of level five."
    duration: 30 minutes
    effect: Other
    level: 6
    line_of_sight: true
    name: 'Being of Force '
    range: Short
    roll: Will
    school: Will
  Dimensional Anchor:
    available: true
    casting_time: 2 minutes
    desc: "With the aid of at least one other caster of the appropriate School, become an Anchor for the closing of a dimensional portal. May require additional casters according to the portal''s magical energies. \n\n Travel, perception, and attacks through the targeted interdimensional portal are reduced as the Anchor forces the portal to shrink. Once the spell is completed, the portal is completely closed and the effect is permanent."
    effect: Travel
    level: 7
    name: Dimensional Anchor
    range: Touch
    roll: true
    school: Will
  Energize Dimensional Anchor (Will):
    available: true
    casting_time: 2 minutes
    desc: Provide necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently close an interdimensional portal.
    effect: Travel
    level: 7
    name: Dimensional Anchor
    range: Touch
    roll: true
    school: Will
  Mass Flight:
    available: true
    casting_time: 1 round
    desc: "Confers the power of flight upon up to 3 targeted creatures. Each recipient of the spell must remain within 30 feet of at least one other recipient, or the spell ends for the creature that is separated from the others."
    duration: 30 minutes
    effect: Travel
    level: 7
    line_of_sight: true
    name: Mass Flight
    range: Short
    roll: true
    school: Will
    target_num: 3
    target_optional: true
  Mass Telekinetic Burst:
    area: 15 yard radius
    available: false
    casting_time: 1 round
    desc: 'The caster lashes out with a blunt telekinetic attack, dealing damage to up to three targets. On a hit, the targets are pushed backwards 1-10 ft.'
    effect: AOE Damage
    fs3_attack: true
    level: 7
    line_of_sight: true
    name: Mass Telekinetic Burst
    range: Long
    school: Will
    target_num: 3
    target_optional: true
    weapon: Mass Telekinetic Burst
  Open Local Portal:
    available: true
    casting_time: 5 minutes
    desc: "The caster opens a permanent portal to a location in the same dimensional world they are currently in. They must have two of the following in order to open a portal to a location:\n\n
      * Personal knowledge of the portal's opening point. They have visited it themselves and can remember the location.\n
      * The ability to see someone else''s memory of the location.\n
      * Exact GPS coordinates of the portal's opening point.\n
      * A realistic depiction of the portal's location, created in the last six months. A recent photograph, life-like drawing, painting, etc."
    effect: Travel
    level: 7
    name: Open Local Portal
    range: Touch
    roll: true
    school: Will
  Massive Telekinetic Barrier:
    area: 100 yard sphere
    available: true
    casting_time: 1 round
    desc: An invisible, protective sphere is created in a 50 yard radius from the caster in all directions. Anything that attempts to cross the spell's boundary is deflected and the caster can open and close doorways through the barrier at will.
    duration: 12 hours
    effect: Defense
    level: 8
    name: Massive Telekinetic Barrier
    range: Self
    roll: true
    school: Will
  Microscopic Telekinesis:
    available: false
    casting_time: 1 round, plus additional rounds to manipulate at GM's discretion
    desc: "The caster can manipulate a microscopic object with great precision. Objects may range in size from 1 micrometer  to 1 milimeter.\n\n Manipulation requires knowledge. The caster cannot use telekinesis to vanquish disease without exact medical knowledge, or to repair fine machinery without engineering knowledge."
    duration: 1 hour
    effect: Other
    level: 8
    name: Microscopic Telekinesis
    range: Touch
    roll: true
    school: Will
  Titanic Telekinesis:
    area: 30 yard cube
    available: false
    casting_time: 1 round, plus additional rounds for movement at the GM's discretion
    desc: 'Move an object weighing up to 100 tons. This is imprecise, and objects move at a speed inverse to their weight. Smaller objects may move up to 35 mph; larger objects move a yard per minute.'
    duration: 1 hour
    effect: Other
    level: 8
    name: Titanic Telekinesis
    range: Long
    roll: true
    school: Will
