spells:
  Beckon Tiny Animal:
    available: true
    casting_time: 1 round
    desc: One animal of diminutive size within range is compelled to approach the caster and linger nearby for the duration of the spell. The target retains all animal instincts and any acts of aggression towards it negate the spell.
    duration: 10 minutes
    effect: Other
    level: 1
    name: Beckon Tiny Animal
    range: Short
    roll: true
    school: Nature
  Bioluminescence:
    available: true
    casting_time: 1 round
    desc: The caster causes up to a 3 square foot portion of their body to glow in a single phosphorescent color. The light is dim, equivalent to a small candle flame (12 lumens).
    duration: 10 minutes
    effect: Creation
    is_potion: true
    level: 1
    name: Bioluminescence
    range: Touch
    roll: true
    school: Nature
  Create Bloom:
    available: true
    casting_time: 1 round
    desc: Cause a flowering plant to grow and bloom from a seed.
    duration: 10 minutes
    effect: Creation
    level: 1
    line_of_sight: true
    name: Create Bloom
    range: Short
    roll: true
    school: Nature
  Repel Tiny Animal:
    available: true
    casting_time: 1 round
    desc: One animal of diminutive size within range is compelled to distance themselves from the caster and stay away for the duration of the spell. The target retains all animal instincts and any acts of aggression towards it negate the spell.
    duration: 10 minutes
    effect: Defense
    level: 1
    line_of_sight: true
    name: Repel Tiny Animal
    range: Short
    roll: true
    school: Nature
    #Level 2
  Camouflage:
    available: true
    casting_time: 1 round
    desc: "In a natural environment, the caster grows a camouflaged covering suitable to their location. The caster is effectively [hidden](https://www.aresmush.com/fs3/fs3-3/combat/#stance) while standing still."
    duration: 15 minutes
    effect: Defense
    level: 2
    is_potion: true
    line_of_sight: true
    name: Camouflage
    range: Self
    roll: false
    school: Nature
    stance: Hidden
  Natural Defenses:
    available: true
    desc: The caster grows natural defenses from a specific animal. These take the form of armored skin, spines, etc. Animal is from the same genus each time the spell is cast.
    level: 2
    name: Natural Defenses
    school: Nature
    range: Self
    effect: Armor
    duration: 15 minutes
    is_potion: true
    armor: Natural Defenses
    casting_time: 1 round
  Natural Weaponry:
    available: false
    casting_time: 1 round
    desc: The caster grows natural weaponry from a specific animal for the purpose of attack. These take the form of non-venomous fangs, claws, horns etc. Animal is from the same genus each time the spell is cast.
    duration: 15 minutes
    effect: Buff
    is_potion: true
    level: 2
    name: Natural Weaponry
    school: Nature
    range: Self
    weapon: Natural Weaponry
  Ripen:
    available: true
    casting_time: 1 round
    desc: Encourage an already existing berry, nut, or fruit-bearing plant to produce a small amount of edible food, no more than a handful, even out of season.
    effect: Creation
    level: 2
    line_of_sight: true
    name: Ripen
    range: Touch
    roll: true
    school: Nature
  Shape Flora:
    area: 5 cubic feet
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can cause up to 5 cubic feet of pre-existing flexible vegetation such as vines and grasses to form into simple non-weaponized shapes that animate at their direction. Can include accelerating growth by up to 30 days in the span of a few seconds. Flora returns to its natural - but not necessarily original - state when the spell ends."
    duration: 1 hour
    effect: Creation
    level: 2
    line_of_sight: true
    name: Shape Flora
    range: Short
    roll: true
    school: Nature
  #Level 3
  Bark Skin:
    available: true
    armor: Bark Skin
    desc: "The caster grows defensive bark from a woody plant over their skin. Plant is from the same genus each time the spell is cast."
    effect: Armor
    level: 3
    name: Bark Skin
    is_potion: true
    range: self
    school: Nature
    casting_time: 1 round
  Calm Animal:
    available: true
    casting_time: 1 round
    desc: Render an animal docile and harmless. Acts of aggression towards the animal negate the spell.
    duration: 1 hour
    effect: Defense
    level: 3
    line_of_sight: true
    name: Calm Animal
    range: Short
    roll: true
    school: Nature
    target_num: 1
    target_optional: true
  Entangle:
    available: true
    casting_time: 1 round
    desc: The caster immobolizes one target with vines anchored to the ground or other structural surroundings.
    effect: Stun
    is_stun: true
    level: 3
    line_of_sight: true
    name: Entangle
    range: Short
    school: Nature
    target_num: 1
    target_optional: true
    weapon: Stun (Nature)
    rounds: 1
  Shield Of The Forest:
    available: false
    casting_time: 1 round
    desc: 'Swiftly grow a barrier that protects the caster or their target by placing them in [cover](https://www.aresmush.com/fs3/fs3-3/combat/#stance) for one round.'
    duration: 1 round
    effect: Defense
    level: 3
    line_of_sight: true
    name: Shield of the Forest
    range: Short
    rounds: 3
    school: Nature
    stance: cover
    target_num: 1
    target_optional: true
  Swarm:
    available: true
    casting_time: 1 round
    desc: "Control a group of angry insects, encouraging them to attack a single enemy. Overcome, the enemy is unable to take any action this round. \n\n Behavior of swarm after the caster''s control dissipates is subject to GM discretion."
    effect: Stun
    is_stun: true
    rounds: 1
    level: 3
    name: Swarm
    notes: Configured without the damage aspect.
    range: Short
    school: Nature
    target_num: 1
    target_optional: true
    weapon: Stun (Nature)
  Thorn Growth:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    desc: Ground-covering vegetation grows sharp thorns in an area you can see, doing damage to up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 3
    line_of_sight: true
    name: Thorn Growth
    range: Short
    school: Nature
    target_num: 3
    target_optional: true
    weapon: Thorn Growth
  Track Animal:
    available: false
    casting_time: 1 round
    desc: "The caster can sense whether any animals of a chosen genus has been within 100 yards of their current position within the last hour. If they sense a target, they are able to track the location of an individual animal for the duration of the spell."
    duration: 15 minutes
    effect: Other
    level: 3
    name: Track Animal
    range: Long
    roll: true
    school: Nature
  #Level 4
  Acid Spit:
    available: true
    casting_time: 1 round
    desc: The caster spits out a stream of corrosive acid at a target, dealing damage.
    effect: Communication
    effect: Damage.
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Acid Spit
    range: Short
    school: Nature
    target_num: 1
    target_optional: true
    weapon: Acid Spit
  Animal Friendship:
    available: true
    casting_time: 1 round
    desc: 'The caster may befriend and converse with a single non-sapient creature for a time. The pair forms a mental bond which allows the animal to communicate and provide specific answers to questions within the limits of their experience and intelligence. Outside observers see only the usual animalistic modes of communication, including verbalization and body language. Animals react favorably to the caster, but maintain their animal instincts, intellectual capacity, memory, and priorities.'
    duration: 3 hours
    effect: Communication
    level: 4
    name: Animal Friendship
    range: Short
    roll: true
    school: Nature
    target_num: 1
    target_optional: true
  Half Shift (Jenu):
    available: false
    armor: Jenu
    desc: Half Shift (Jenu)
    level: 4
    name: Half Shift (Jenu)
    school: Nature
    weapon: Jenu
  Half Shift:
    available: false
    casting_time: 1 round
    desc: "The caster transforms up to half their body into a chosen non-sapient creature, giving them a hybrid form that carries advantages of both the creature and their original form.\n\n Creature is from the same genus each time the spell is cast."
    duration: 1 hour
    effect: Transformation
    level: 4
    name: Half Shift
    range: Self
    roll: true
    school: Nature
  Heal Animal:
    available: false
    casting_time: 1 round
    desc: Provide a middling amount of healing magic to a non-sapient target's most severe treatable wound, speeding their healing by up to nearly a week and restoring some of their vigor.
    effect: Heal
    heal_points: 7
    level: 4
    line_of_sight: true
    name: Heal Animal
    range: Short
    school: Nature
    target_num: 1
    target_optional: true
  Thermal Sense:
    area: 10 yards
    available: false
    casting_time: 1 round
    desc: "The caster is able to sense slight changes in the ambient temperature around themselves, sensing where the temperature differs from the ambient temperature of the air or other surroundings. This allows them to roughly perceive objects, people, and other aspects of their environment via thermal imaging within 10 yards of their person.\n\nThermal differences can be sensed despite invisibility, darkness, and other conditions that obscure eyesight, but cannot be sensed beyond cover that blocks heat rays. The caster is not required to make perception checks to notice thermal changes within range."
    duration: 10 minutes
    effect: Other
    level: 4
    name: Thermal Sense
    range: Short
    school: Nature
    target_num: 1
    target_optional: true
  Photosynthesis:
    available: true
    casting_time: 1 round
    desc: The cells in the caster's body are charged by light, allowing them to speed their healing by up to nearly a week and restore some of their vigor. Provides a middling amount of healing magic to the caster's most severe treatable wound.
    effect: Heal
    heal_points: 7
    is_potion: true
    level: 4
    name: Photosynthesis
    range: Self
    school: Nature
    target_num: 1
  Potions (Nature):
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    effect: Other
    level: 4
    name: Potions (Nature)
    school: Nature
    available: true
  Regress Growth:
    available: true
    casting_time: 1 round
    desc: Causes up to three plants each up to 3 cubic feet in size to regress back from mature state to an inert seed, spore or other starting form within a matter of minutes.
    effect: Other
    level: 4
    line_of_sight: true
    name: Regress Growth
    range: Short
    school: Nature

  Vigor Surge:
    available: false
    casting_time: 1 round
    desc: The caster temporarily increases the vigor of an animal of any size. For an hour, the animal has more energy, gains a minor amount of strength, and recovers more quickly from exhaustion or minor injury. With repeated use over weeks, the animal's health will improve permanently within natural limits. The spell cannot prevent injuries or provide any healing to existing injuries.
    effect: Buff
    level: 4
    line_of_sight: true
    name: Vigor Surge
    range: Touch
    roll: true
    school: Nature
    target_num: 0
  Germinate:
    available: false
    casting_time: 1 round
    desc: Grow any kind of plant from a seed that will reach maturity within a matter of minutes. It may bloom, but will not produce fruit without either more time or magic. There must be sufficient and appropriate resources for the plant to grow.
    effect: Creation
    level: 5
    line_of_sight: true
    name: Germinate
    range: Short
    roll: true
    school: Nature
  Wild Shape Moth:
    available: false
    armor: Moth
    desc: Wild Shape desc
    level: 5
    name: Wild Shape
    roll: true
    school: Nature
  Wild Shape Crocodile:
    available: false
    armor: Crocodile
    desc: Wild Shape desc
    level: 5
    name: Wild Shape
    roll: true
    school: Nature
    range: Self
    weapon: Claws
  Wild Shape Bear:
    available: true
    armor: Tough Hide
    desc: Wild Shape desc
    level: 5
    name: Wild Shape
    roll: true
    school: Nature
    range: Self
    weapon: Claws
  Wild Shape Wolf:
    available: true
    armor: Tough Hide
    desc: Wild Shape desc
    level: 5
    name: Wild Shape
    roll: true
    school: Nature
    range: Self
    weapon: Claws
  Wild Shape:
    available: true
    desc: Caster chooses any alternate form from a specified animal genus. They lose the ability to cast spells and speak while in wild shape but can communicate with other animals of that genus. They may revert back to human form at will.
    effect: Transformation
    level: 5
    name: Wild Shape
    roll: true
    school: Nature
    range: Self
    duration: 3 hours
    casting_time: 1 round
    effect: transformation
  Familiar (Nature):
    desc: "A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. \n\nFamiliars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles."
    effect: Other
    level: 6
    name: Familiar
    roll: true
    school: Nature
    casting_time: 3 hours
    range: Short
    line_of_sight: true
    available: true
  Mass Calm Animal:
    available: false
    casting_time: 1 round
    desc: Render up to six animals docile and harmless. Acts of aggression towards the animal negate the spell.
    effect: Defense
    level: 6
    line_of_sight: true
    name: Mass Calm Animal
    range: Short
    roll: true
    school: Nature
  Poison Puffs:
    area: 10 yard radius
    available: false
    casting_time: 1 round
    desc: Grow an area of mushrooms in an area that you can see. As they grow, they release a poisonous gas into the surrounding air, affecting up to 3 targets.
    duration: 1 round
    effect: AOE Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Poison Puffs
    range: Long
    school: Nature
    target_num: 3
    target_optional: true
    weapon: Poison Puffs
  Winged Flight:
    available: true
    casting_time: 1 round
    defense_mod: 1
    desc: "The caster grows wings large enough to carry them in flight.The wings allow them to travel at a speed of up to 65 mph. \n\n Practiced casters can obtain excellent maneuverability with their wings, making it easy for them to engage in combat and giving them an edge to their ability to dodge.\n\n Should the spell duration expire while the caster is still aloft, they plummet to the ground."
    duration: 1 hour
    effect: Travel
    level: 6
    range: Self
    roll: true
    rounds: 100
    school: Nature
  Energize Dimensional Anchor (Nature):
    available: true
    casting_time: 2 minutes
    desc: Provide necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently close an interdimensional portal.
    effect: Travel
    level: 7
    name: Dimensional Anchor
    range: Touch
    roll: true
    school: Nature
  Druid's Wood:
    available: false
    casting_time: 1 round
    desc: The caster may summon a forest, no larger than 600 square yards, populated with the trees, shrubs, and grasses local to the area. The trees may not exceed three hundred feet in height. The plants must have ample space and soil to grow. The plants may be grown in any pattern the caster chooses.
    effect: Other
    level: 7
    line_of_sight: true
    name: Druid's Wood
    range: Long
    roll: true
    school: Nature
  Greater Wild Shape:
    available: true
    casting_time: 1 round
    desc: Caster chooses any alternate form from a specified animal family. They retain the ability to cast spells and speak while in wild shape in addition to being able to communicate with other animals of that family. They may revert back to human form at will.
    duration: 1 hour
    effect: Transformation
    level: 7
    name: Greater Wild Shape
    range: Self
    roll: true
    school: Nature
  Sense Animals:
    available: true
    desc: "The caster extends their senses to all non-sapient creatures within range. While their body lies senseless and incapacitated, they see and feel everything sensed by every non-sapient creature in that area. They can also identify the presence, quantity, and location of sapient creatures.\n\nThe caster can choose to absorb all experiences at a surface level, or focus their attention on up to five individuals at a time for more details."
    effect: Communication
    level: 7
    name: Sense Animals
    roll: true
    school: Nature
  Baleful Polymorph:
    available: true
    casting_time: 1 round
    desc: "A single target, willing or unwilling, is permanently transformed into a harmless animal or plant of caster's choosing and removed from battle. \n\nAt GM discretion, 'Familiar' rules apply concerning the target's communication capabilities such as empathy or telepathy."
    duration: Permanent
    effect: Transformation
    level: 8
    line_of_sight: true
    name: Baleful Polymorph
    range: Short
    roll: true
    school: Nature
    target_num: 1
    target_optional: true
  Massive Thorn Wall:
    area: 1,000 yards long, 25 yards thick, 25 yards tall
    available: false
    casting_time: 1 round
    desc: Create a massive wall of thorns. Can be created in any shape, and the caster can open and close doorways through the wall at will.
    duration: 24 hours
    effect: Defense
    level: 8
    name: Massive Thorn Wall
    range: Long
    roll: true
    school: Nature
