spells:
#---------------
# LEVEL 1
#---------------
  Fire Starter:
    available: true
    casting_time: 1 round
    damage_type: None
    desc: Create or snuff out a flame the size of a lighter.
    duration: 10 minutes
    effect: Other
    level: 1
    line_of_sight: true
    name: Fire Starter
    range: Short
    roll: true
    school: Aether
  Light:
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: Create a beam of light equivilent to 300 lumens (a small LED flashlight).
    duration: 30 minutes
    effect: Other
    level: 1
    line_of_sight: true
    name: Light
    range: Short
    roll: true
    school: Aether
  Spark:
    available: true
    casting_time: 1 round
    desc: The caster creates a small electric current visible between two fingers. The electricity can be used to recharge up to 5% of a communicator battery or power electronics less than 3 volts (2 AA batteries) for the length of the spell. It causes a static shock-like effects in individuals.
    duration: 30 minutes
    effect: Other
    level: 1
    name: Spark
    range: Touch
    roll: true
    school: Aether
    target_num: 1    
  Adjust Volume:
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: "For the duration of the spell, the caster can amplify or decrease the volume of the sound coming from a target. Sounds cannot be made louder than 80 db (a loud truck, a vacuum cleaner), nor can sounds be made softer than 30 db (a quiet whisper)."
    duration: 30 minutes
    effect: Illusion
    level: 2
    name: Adjust Volume
    range: Short
    roll: true
    school: Aether    
#---------------
# LEVEL 2
#---------------
  Cloud Cover:
    area: 5 ft radius
    available: true
    casting_time: 1 round
    damage_type: None
    desc: "Misty vapor gathers around you. It follows you as you move, but can be dispersed by a strong wind. The vapor obscures all sight in a 5 ft radius, effectively making the caster hidden as long as they make no noise and cast no magic."
    duration: 15 minutes
    effect: Defense
    is_potion: true
    level: 2
    name: Cloud Cover
    range: Self
    school: Aether
    target_num: 1
  Dustup:
    attack_mod: -1
    available: true
    casting_time: 1 round
    defense_mod: -1
    desc: "The caster blows a small cloud of dirt around a target, briefly obscuring their vision and making it harder for them to attack or defend."
    duration: 1 round
    effect: Debuff
    level: 2
    line_of_sight: true
    name: Dustup
    range: Short
    rounds: 1
    school: Aether
    target_num: 1
    effect: Debuff    
#---------------
# LEVEL 3
#---------------
  Wind Wall:
    available: true
    casting_time: 1 round
    desc: "Deflect ranged projectile attacks directed against you or a single comrade with gusting winds."
    duration: 3 rounds
    effect: Shield
    is_shield: true
    level: 3
    line_of_sight: true
    name: Wind Wall
    range: Short
    rounds: 3
    school: Aether
    shields_against: All
    target_num: 1
  Shock:
    available: true
    casting_time: 1 round
    damage_type: None
    desc: Shock an opponent with a burst of electricity, stunning them for one round.
    duration: 1 round
    effect: Stun
    is_stun: true
    rounds: 1
    level: 3
    line_of_sight: true
    name: Shock
    range: Short
    school: Aether
    target_num: 1
    weapon: Stun (Aether)    
#---------------
# LEVEL 4
#---------------
  Create Sound:
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: "For the duration of the spell, the caster can vibrate the air to create simple sounds. These sounds can be a single noise, a melody, or a short sentence of up to fifteen, one-syllable words. Sound created cannot be louder than 80 db (a loud truck, a vacuum).\n\nThe sound may be identified as artificial with a roll of the caster's Air vs the observer's Alertness-5. Those with enhanced hearing are more likely to identify the sound as artificial according to its content and range, and GMs may choose to adjust the modification as appropriate."
    duration: 15 minutes
    effect: Illusion
    level: 4
    name: Create Sound
    range: Short
    roll: true
    school: Aether    
  Lightning Bolt:
    available: true
    casting_time: 1 round
    desc: The caster calls a bolt of lightning from the sky, striking a target and causing damage.
    effect: Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Lightning Bolt
    range: Short
    require_target: true
    school: Aether
    weapon: Lightning Bolt
    target_num: 1    
  Lightning Weapon:
    available: true
    casting_time: 1 round
    desc: Augment a pre-existing weapon with crackling electricity, increasing its damage and speed.
    effect: Buff
    duration: 3 hours
    is_potion: true
    level: 4
    name: 'Lightning Weapon '
    notes: Weapon special config'd, but needs the stun portion
    range: Touch
    rounds: 100
    school: Aether
    target_num: 1
    weapon_specials: Lightning
    weapon: Spell    
  Simple Illusion:
    area: 5 cubic feet
    available: true
    casting_time: 1 minute (6 rounds)
    damage_type: Bypass
    desc: "Create a convincing illusion of a single subject that fools most observers. It is able to animate at the caster's discretion. The illusion cannot be larger than 3 cubic yards.\n\n The image may be identified as an illusion with a roll of the caster's Aether vs the observer's Alertness-5. Those with enhanced senses such as smell, hearing, or psionic abilities are more likely to identify the subject as an illusion according to its content and range, and GMs may choose to adjust the modification as appropriate. If the illusion serves to hide the targets in combat, they should change their stance to 'Hidden' and attacks targeting them which require line of sight receive a -3 attack mod."
    duration: 15 minutes
    effect: Illusion
    level: 4
    line_of_sight: true
    name: Simple Illusion
    range: Short
    roll: true
    school: Aether    
#---------------
# LEVEL 5
#---------------
  Breathless:
    area: 10 ft radius
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: 'Draw all oxygen from an area, dousing any flames present and creating oxygen deprivation for an air-breathing creature of your choice caught in its range.'
    duration: 1 round
    effect: Damage
    fs3_attack: true
    level: 5
    name: Breathless
    range: Short
    school: Aether
    target_num: 1
    weapon: Breathless
  # Darkness:
  #   available: false
  #   area: 10 ft radius
  #   casting_time: 1 round
  #   damage_type: Bypass
  #   defense_mod: 3
  #   desc:  "The caster quenches all light within a 10 ft radius area, making anything caught in the darkness hidden and blind. Spell does not put out any sources of light, but stops them from illuminating the area.  Darkened area cannot be moved.\n\nAttacks which require line of sight may target those within the darkness, but hidden targets receive an automatic +3 to defense. Targets should be selected via a random roll (`dice d1<number of targets>`, select alphabetically) and should include any allies. Attacks which do not require line of sight may target hidden creatures with a +3 to attack (to cancel the +3 defense).\n\nBlinded beings may attack at GM discretion with a -3 attack mod (not automatic).\n\nDoes not effect spells, senses and abilities that do not require line of sight."
  #   duration: 15 minutes
  #   effect: Defense
  #   level: 5
  #   line_of_sight: true
  #   name: Darkness
  #   range: Short
  #   rounds: 90
  #   school: Aether
  #   stance: hidden
  #   target_num: 3
  Fireball:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: A ball of fire hurls toward a target, doing damage.
    effect: Damage
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Fireball
    range: Short
    school: Aether
    target_num: 3
    weapon: Fireball
#---------------
# LEVEL 6
#---------------
  Flares:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: Colorful flares explode outwards from central points. The bursts of intense heat sear through anything in their path, affecting up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Flares
    range: Long
    school: Aether
    target_num: 3
    weapon: Flares
  Lightning Bolt:
    available: true
    casting_time: 1 round
    desc: The caster calls a bolt of lightning from the sky, striking a target and causing damage.
    effect: Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Lightning Bolt
    range: Short
    require_target: true
    school: Aether
    weapon: Lightning Bolt
    target_num: 1
  Sonic Blast:
    available: true
    attack_mod: -2
    casting_time: 1 round
    desc: The target is blasted by an intense burst of sound, leaving them disoriented. For a short time, it is more difficult for the them to take their intended actions.
    defense_mod: -2
    duration: 3 rounds
    effect: Debuff
    level: 6
    line_of_sight: true
    name: Sonic Blast
    range: Long
    rounds: 3
    school: Aether
    spell_mod: -2
    target_num: 1    
#---------------
# LEVEL 7
#---------------    
  Complex Illusion:
    area: '10 yard radius'
    available: true
    casting_time: 1 minute
    damage_type: Bypass
    desc: "Create a complicated, convincing visual illusion that fools most observers. The illusion can be quite large, with many moving parts, such as a forest scene or a busy street. Can be used to hide groups.\n\nThe image may be identified as an illusion with a roll of the caster's Fire vs the observer's Alertness-5. Those with enhanced senses such as smell, hearing, or psionic abilities are more likely to identify the subject as an illusion according to its content and range, and GMs may choose to adjust the modification as appropriate."
    duration: 30 minutes
    effect: Illusion
    level: 7
    line_of_sight: true
    name: Complex Illusion
    range: Short
    roll: true
    school: Aether
    target_num: 1
  Complex Sound:
    available: true
    casting_time: 1 minute
    damage_type: Bypass
    desc: "For the duration of the spell, the caster can vibrate the air to create complex sounds. These sounds can be several noises at once, music, or conversational speech. Sound created cannot be louder than 100 db (a loud vehicle, a train whistle, a hand drill).\n\nThe sound may be identified as artificial with a roll of the caster's Air vs the observer's Alertness-5. Those with enhanced hearing are more likely to identify the sound as artificial according to its content and range, and GMs may choose to adjust the modification as appropriate."
    duration: 30 min
    effect: Illusion
    init_mod: 1
    level: 7
    name: Complex Sound
    range: Short
    school: Aether
    target_num: 1  
  Dust Devils:
    attack_mod: -2
    available: true
    casting_time: 1 round
    damage_type: Bypass
    defense_mod: -2
    desc: "The caster sends a gust of air to stir up small clouds of dirt around up to three targets, obscuring their vision and making it harder for them to attack or defend."
    duration: 3 rounds
    effect: Debuff
    level: 7
    line_of_sight: true
    name: Dust Devils
    range: Short
    rounds: 3
    school: Aether
    target_num: 3
    effect: Debuff      
  Pyre:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: 'Gouts of flame are summoned up from the ground, engulfing the target.'
    effect: Damage
    fs3_attack: true
    level: 7
    line_of_sight: true
    name: Pyre
    range: Long
    school: Aether
    target_num: 1
    weapon: Pyre    
#---------------
# LEVEL 8
#---------------
  Lightning Strike:
    available: true
    casting_time: 1 round
    desc: A streak of powerful lightning plunges from the sky to strike a target, doing massive damage.
    effect: Damage
    level: 8
    line_of_sight: true
    fs3_attack: true
    name: Lightning Strike
    range: Long
    school: Aether
    target_num: 1
    weapon: Lightning Strike
  Suffocate:
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: "Draw the air from the lungs of a target, making it impossible for them to breathe. \n\nDoes not affect enemies who do not breathe air."
    effect: Damage
    fs3_attack: true
    level: 8
    line_of_sight: true
    name: Suffocate
    range: Long
    school: Aether
    target_num: 1
    weapon: Suffocate    
#---------------
# LEVEL 9
#---------------
#---------------
# LEVEL 10
#---------------    



#TEST SPELLS
# LEVEL 1
  Gust:
    available: true
    casting_time: 1 round
    desc: Create a brief gust of wind capable of blowing a door shut.
    duration: 10 minutes
    effect: Creation
    level: 1
    name: Gust
    range: Short
    roll: true
    school: Aether
    target_num: 1
  # LEVEL 2
  Cloud Cover:
    area: 5 ft radius
    available: true
    casting_time: 1 round
    desc: "Misty vapor gathers around you. It is stationary once created, and can be dispersed by a strong wind. The vapor obscures all sight in a 5 ft radius, effectively making anyone in its midst [hidden](https://www.aresmush.com/fs3/fs3-3/combat/#stance) while standing still."
    duration: 15 minutes
    effect: Defense
    is_potion: true
    level: 2
    name: Cloud Cover
    range: Self
    rounds: 90
    roll: true
    school: Aether
    target_num: 1
  #LEVEL 4
  Air Blast:
    area: 5 ft radius
    available: true
    casting_time: 1 round
    desc: Create a powerful blast of wind that knocks an enemy back 5 yards, stunning them.
    duration: 1 round
    effect: Stun
    is_stun: true
    rounds: 1
    level: 4
    line_of_sight: true
    name: 'Air Blast '
    range: Short
    school: Aether
    target_num: 1
    weapon: Stun (Aether)
  Breathless:
    area: 10 ft radius
    available: true
    casting_time: 1 round
    desc: 'Draw all oxygen from an area, dousing any flames present and creating oxygen deprivation for up to 3 air-breathing creatures of your choice caught in its range. '
    duration: 1 round
    effect: Damage
    fs3_attack: true
    level: 4
    name: Breathless
    range: Short
    school: Aether
    target_num: 3
    weapon: Breathless
  #LEVEL 5
  Sonic Blast:
    available: true
    attack_mod: -2
    casting_time: 1 round
    desc: The target is blasted by an intense burst of sound, leaving them disoriented. For a short time, it is more difficult for the them to take their intended actions.
    defense_mod: -2
    duration: 3 rounds
    effect: Debuff
    level: 5
    line_of_sight: true
    name: Sonic Blast
    range: Long
    rounds: 3
    school: Aether
    spell_mod: -2
    target_num: 1
#Level 7
  Lightning Strike:
    available: true
    casting_time: 1 round
    desc: A streak of powerful lightning plunges from the sky to strike a target, doing damage.
    effect: Damage
    level: 7
    line_of_sight: true
    fs3_attack: true
    name: Lightning Strike
    range: Long
    roll: true
    school: Aether
    target_num: 1
    weapon: Lightning Strike

  Fire Starter:
    available: true
    casting_time: 1 round
    desc: Create a flame the size of a lighter.
    duration: 10 minutes
    effect: Creation
    level: 1
    line_of_sight: true
    name: Fire Starter
    range: Short
    roll: true
    school: Aether
  Blur Image:
    available: true
    casting_time: 1 round
    defense_mod: 1
    desc: Through a trick of light, the caster bolsters their defense by making themselves more difficult to target for a round.
    duration: 2 rounds
    effect: Buff
    is_potion: true
    level: 2
    name: Blur Image
    range: Self
    rounds: 2
    school: Aether
  Endure Fire:
    available: true
    casting_time: 1 round
    desc: Caster is immune to fire and the negative effects of extreme heat up to 2,012 째F (1,110 째C). Spells that do fire damage may be stopped entirely by Endure Fire; when they are not, the damage inflicted is decreased.
    duration: 10 minutes
    effect: Buff
    is_potion: true
    is_shield: true
    level: 3
    name: Endure Fire
    range: Self
    school: Aether
    shields_against: Fire
    rounds: 60
  Hot Hands:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: Caster can heat their hands to a chosen temperature ranging from a minor warmth to hot enough to deliver minor fire damage via touch.
    duration: 30 minutes
    effect: Weapon
    is_potion: true
    level: 3
    name: Hot Hands
    range: Touch
    school: Aether
    target_num: 1
    weapon: Hot Hands
  Fire Weapon:
    available: true
    casting_time: 1 round
    desc: Augment one specified pre-existing weapon with dancing flames, increasing its damage.
    duration: 3 hours
    effect: Buff
    is_potion: true
    level: 4
    name: Fire Weapon
    range: Touch
    rounds: 100
    school: Aether
    target_num: 1
    weapon_specials: Fire
    weapon: Spell
  Group Endure Fire:
    available: true
    casting_time: 1 round
    desc: Caster is immune to fire and the negative effects of extreme heat up to 2,012 째F (1,110 째C). Spells that do fire damage may be stopped entirely by Endure Fire; when they are not, the damage inflicted is decreased.
    duration: 1 hour
    effect: Buff
    is_shield: true    
    level: 5
    name: Group Endure Fire
    range: Short
    shields_against: Fire
    school: Aether
    rounds: 100
    target_num: 3    