spells:
  Fire Starter:
    available: true
    casting_time: 1 round
    desc: Create a flame the size of a lighter.
    duration: 10 minutes
    effect: Creation
    level: 1
    line_of_sight: true
    name: Fire Starter
    range: Short
    roll: true
    school: Fire
  Light:
    available: true
    casting_time: 1 round
    desc: Create a beam of light equivilent to 300 lumens (a small LED flashlight).
    duration: 10 minutes
    effect: Creation
    level: 1
    line_of_sight: true
    name: Light
    range: Short
    roll: true
    school: Fire
  Snuff Flame:
    available: true
    casting_time: 1 round
    desc: Extinguish a flame the size of a lighter.
    effect: Other
    level: 1
    line_of_sight: true
    name: Fire Starter
    range: Short
    roll: true
    school: Fire
  #Level 2
  Blur Image:
    available: true
    casting_time: 1 round
    defense_mod: 1
    desc: Through a trick of light, the caster bolsters their defense by making themselves more difficult to target for a round.
    duration: 2 rounds
    effect: Buff
    is_potion: true
    level: 2
    name: Blur Image
    range: Self
    rounds: 2
    school: Fire
  Shape Fire:
    area: 5 cubic feet
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can influence up to 5 cubic feet of flames, forming them into simple non-weaponized shapes that animate at their direction. Within the size limit, they can make flames grow or snuff them out entirely. When the spell ends, the flames return to their natural state in their current location."
    duration: 1 hour
    effect: Creation
    level: 2
    line_of_sight: true
    name: Shape Fire
    range: Short
    roll: true
    school: Fire
  Shape Light:
    area: 5 cubic feet
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can cause ambient light to form into simple non-weaponized shapes and colors that animate at their direction. The shapes must form a single continuous image and do not include fine details, although they can be three dimensional and may be as large as 5 cubic feet.  Any intelligent creature can identify images made with this spell as artificial."
    duration: 1 hour
    effect: Illusion
    level: 2
    line_of_sight: true
    name: Shape Light
    range: Short
    roll: true
    school: Fire
  #Level 3
  Endure Fire:
    available: true
    casting_time: 1 round
    desc: Caster is immune to fire and the negative effects of extreme heat up to 2,012 째F (1,110 째C). Spells that do fire damage may be stopped entirely by Endure Fire; when they are not, the damage inflicted is decreased.
    duration: 10 minutes
    effect: Buff
    is_potion: true
    is_shield: true
    level: 3
    name: Endure Fire
    range: Self
    school: Fire
    rounds: 60
  Flame Dart:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: "Launches a single small, flaming projectile at a target, doing damage."
    effect: Damage
    fs3_attack: true
    level: 3
    line_of_sight: true
    name: Flame Dart
    range: Short
    school: Fire
    target_num: 1

    weapon: Flame Dart
  Hot Hands:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: Caster can heat their hands to a chosen temperature ranging from a minor warmth to hot enough to deliver minor fire damage via touch.
    duration: 30 minutes
    effect: Weapon
    is_potion: true
    level: 3
    name: Hot Hands
    range: Touch
    school: Fire
    target_num: 1

    weapon: Hot Hands
  Laser Zap:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: The caster creates an amplified ray of light and focuses the laser on a target to burn them.
    effect: Damage
    fs3_attack: true
    level: 3
    name: Laser Zap
    range: Short
    line_of_sight: true
    school: Fire
    target_num: 1

    weapon: Laser Zap
  #Level 4
  Fire Weapon:
    available: true
    casting_time: 1 round
    desc: Augment one specified pre-existing weapon with dancing flames, increasing its damage.
    duration: 3 hours
    effect: Buff
    is_potion: true
    level: 4
    name: Fire Weapon
    range: Touch
    rounds: 100
    school: Fire
    target_num: 1
    weapon_specials: Fire
    weapon: Spell
  Flame Burst:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: The caster hurls a ball of swirling flames at a single target.
    effect: Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Flame Burst
    range: Short
    school: Fire
    target_num: 1
    weapon: Flame Burst
  Flame Breath:
    available: false
    area: Direct line from caster, 5 yards wide
    casting_time: 1 round
    damage_type: Fire
    desc: The caster blows a plume of fire away from themselves, the flames extending outward in a cone shape and doing minor fire damage to up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Flame Burst
    range: Short
    school: Fire
    target_num: 3
    weapon: Flame Breath
  Potions (Fire):
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    effect: Other
    level: 4
    name: Potions (Fire)
    school: Fire
    available: true
  Pyromancy:
    area: 15 cubic feet
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can create or influence up to 15 cubic feet of fire, moving and shaping it into detailed, non-weaponized shapes that animate at their direction. Within the size limit, they can control the size and heat of the flames, making them grow, dim, or snuff them out entirely. When the spell ends, the flames return to their natural state in their current location."
    duration: 30 min
    effect: Creation
    level: 4
    line_of_sight: true
    name: Pyromancy
    range: Short
    roll: true
    school: Fire
  Simple Illusion:
    area: 5 cubic feet
    available: true
    casting_time: 1 minute (6 rounds)
    desc: "Create a convincing illusion of a single subject that fools most observers. It is able to animate at the caster's discretion. The illusion cannot be larger than 3 cubic yards.\n\n The image may be identified as an illusion with a roll of the caster's Fire vs the observer's Alertness-5. Those with enhanced senses such as smell, hearing, or psionic abilities are more likely to identify the subject as an illusion according to its content and range, and GMs may choose to adjust the modification as appropriate."
    duration: 15 minutes
    effect: Illusion
    level: 4
    line_of_sight: true
    name: Simple Illusion
    range: Short
    roll: true
    school: Fire
  #Level 5
  Flares:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: Colorful flares explode outwards from central points. The bursts of intense heat sear through anything in their path, affecting up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Flares
    range: Long
    school: Fire
    target_num: 3

    weapon: Flares
  Group Endure Fire:
    available: true
    casting_time: 1 round
    desc: Caster is immune to fire and the negative effects of extreme heat up to 2,012 째F (1,110 째C). Spells that do fire damage may be stopped entirely by Endure Fire; when they are not, the damage inflicted is decreased.
    duration: 1 hour
    effect: Buff
    is_shield: true
    level: 5
    name: Group Endure Fire
    range: Short
    school: Fire
    rounds: 100
    target_num: 3
  Invisible:
    available: true
    casting_time: 1 round
    desc: "The caster bends light around the target''s form, making them invisible and effectively [hidden.](https://www.aresmush.com/fs3/fs3-3/combat/#stance) The caster may end the spell at any time."
    duration: 5 minutes
    effect: Defense
    level: 5
    line_of_sight: true
    name: Invisible
    range: Touch
    rounds: 30
    school: Fire
    stance: hidden
    target_num: 1


  #Level 6
  Double Vision:
    available: true
    casting_time: 1 round
    desc: "Through a trick of light, the caster creates a single mirror image of themselves. Until the spell ends, the duplicate image mimics the caster's actions, making it difficult to know which image is real, which bolsters their defense by making them more difficult to hit.\n\nThe mirror image may be identified as an illusion with a roll of the caster's Fire vs the observer's Alertness-5. Those with enhanced senses such as smell, hearing, or psionic abilities are more likely to identify the subject as an illusion according to its content and range, and GMs may choose to adjust the modification as appropriate."
    defense_mod: 3
    duration: 2 minutes
    effect: Defense
    level: 6
    line_of_sight: true
    name: Double Vision
    range: Self
    rounds: 120
    school: Fire
  Familiar (Fire):
    desc: "A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. \n\nFamiliars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles."
    effect: Other
    level: 6
    name: Familiar (Fire)
    roll: true
    school: Fire
    casting_time: 3 hours
    range: Short
    line_of_sight: true
    available: true
  Laser Blast:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: 'The caster creates a powerfully amplified ray of light and focuses the laser on a target to blast them with intense heat.'
    effect: Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Laser Blast
    range: Long
    school: Fire
    target_num: 1

    weapon: Laser Blast
  Pyre:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: 'Gouts of flame are summoned up from the ground, engulfing the target.'
    effect: Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Pyre
    range: Long
    school: Fire
    target_num: 1

    weapon: Pyre
  Complex Illusion:
    area: '10 yard radius'
    available: true
    casting_time: 1 minute
    desc: "Create a complicated, convincing visual illusion that fools most observers. The illusion can be quite large, with many moving parts, such as a forest scene or a busy street. Can be used to hide groups.\n\nThe image may be identified as an illusion with a roll of the caster's Fire vs the observer's Alertness-5. Those with enhanced senses such as smell, hearing, or psionic abilities are more likely to identify the subject as an illusion according to its content and range, and GMs may choose to adjust the modification as appropriate."
    duration: 30 minutes
    effect: Illusion
    level: 7
    line_of_sight: true
    name: Complex Illusion
    range: Short
    roll: true
    school: Fire
    target_num: 1

  Energize Dimensional Anchor (Fire):
    available: true
    casting_time: 2 minutes
    desc: "Provide the necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently open or close an interdimensional portal.\n\nIf cast on an open portal, the caster can sense if the spell's School is the necessary magical energy to enable opening or closing the portal, as well as the magical coordinates of the portal's existence in the magical universe."
    effect: Travel
    level: 7
    name: Energize Dimensional Anchor (Fire)
    range: Touch
    roll: true
    school: Fire
  Light Form:
    available: true
    casting_time: 1 round
    defense_mod: 10
    desc: "The caster's body becomes white light and cannot be hit by attacks.\n\nWhile in light form, the caster can pass through small holes, narrow openings, or transparent objects with anything they were carrying at the time the spell was cast. The form also allows them to cross distances seemingly instantaneously, able to travel up to 4,000 miles total for the duration of the spell."
    duration: 10 rounds
    effect: Transformation
    level: 7
    name: Light Form
    range: Self
    roll: true
    rounds: 10
    school: Fire
    target_num: 1
  Phoenix's Healing Flames:
    available: true
    auto_revive: true
    casting_time: 1 round
    desc: "A knocked out target is overtaken by flames and reduced to ashes. From beneath those ashes, they are revived and able to return to the fight. \n\nA revived target has no wounds and no spell fatigue.\n\n A magic user who knows this spell is automatically consumed and revived when they themselves can no longer fight. This takes 1 round after they are knocked out."
    effect: Revive
    level: 7
    line_of_sight: true
    name: Phoenix's Healing Flames
    notes: This can work, but needs more coding to remove wounds.
    range: Long
    roll: false
    school: Fire
    target_num: 1

  #LEVEL 8
  Firestorm:
    area: Up to 1 square mile
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: Call down a massive storm of fire on a place that you can see. It consumes most things in its path, doing immense damage.
    effect: AOE Damage
    fs3_attack: true
    level: 8
    line_of_sight: true
    name: Firestorm
    range: Massive
    school: Fire
    target_num: 100

    weapon: Firestorm
  Phoenix's Last Flight:
    available: true
    casting_time: 1 round
    desc: "A target who has died in the last 60 seconds is overtaken by flames and reduced to ashes. From beneath those ashes, they are revived. \n\nA revived target is unable to return to the fight without further healing. They are both incapacitated and suffering from spell fatigue.\n\n A magic user who knows this spell is automatically consumed and revived when they themselves fall."
    effect: Resurrection
    is_res: true
    level: 8
    line_of_sight: true
    name: Phoenix's Last Flight"
    notes: Needs coded
    range: Long
    school: Fire
    target_num: 1
