spells:
#---------------
# LEVEL 1
#---------------
  Fire Starter:
    available: true
    casting_time: 1 round
    damage_type: None
    desc: Create or snuff out a flame the size of a lighter.
    duration: 10 minutes
    effect: Manipulation
    level: 1
    line_of_sight: true
    name: Fire Starter
    range: Short
    roll: true
    school: Aether
  Light:
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: Create a beam of light equivilent to 300 lumens (a small LED flashlight).
    duration: 30 minutes
    effect: Manipulation
    level: 1
    line_of_sight: true
    name: Light
    range: Short
    roll: true
    school: Aether
  Spark:
    available: true
    casting_time: 1 round
    desc: The caster creates a small electric current visible between two fingers. The electricity can be used to recharge up to 5% of a communicator battery or power electronics less than 3 volts (2 AA batteries) for the length of the spell. It causes a static shock-like effects in individuals.
    duration: 30 minutes
    effect: Manipulation
    level: 1
    name: Spark
    range: Touch
    roll: true
    school: Aether
    target_num: 1
  Adjust Volume:
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: "For the duration of the spell, the caster can amplify or decrease the volume of the sound coming from a target. Sounds cannot be made louder than 80 db (a loud truck, a vacuum cleaner), nor can sounds be made softer than 30 db (a quiet whisper)."
    duration: 30 minutes
    effect: Manipulation
    level: 2
    name: Adjust Volume
    range: Short
    roll: true
    school: Aether
#---------------
# LEVEL 2
#---------------
  Cloud Cover:
    area: 5 ft radius
    available: true
    casting_time: 1 round
    damage_type: None
    desc: "Misty vapor gathers around you. It follows you as you move, but can be dispersed by a strong wind. The vapor obscures all sight in a 5 ft radius, effectively making the caster hidden as long as they make no noise and cast no magic."
    duration: 15 minutes
    effect: Defense
    is_potion: true
    level: 2
    name: Cloud Cover
    range: Self
    school: Aether
    target_num: 1
  Dustup:
    attack_mod: -1
    available: true
    casting_time: 1 round
    defense_mod: -1
    desc: "The caster blows a small cloud of dirt around a target, briefly obscuring their vision and making it harder for them to attack or defend."
    duration: 1 round
    effect: Debuff
    level: 2
    line_of_sight: true
    name: Dustup
    range: Short
    rounds: 1
    school: Aether
    target_num: 1
    effect: Debuff
#---------------
# LEVEL 3
#---------------
  Aeromancy:
    area: 1 cubic yard
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: "For the duration of the spell, the caster can move and shape up to 1 cubic yard of gaseous substances. The caster can control the flow, density, and dispersion of a gaseous substance to form breathable bubbles in water, draw the oxygen towards or away from a flame, or push poisonous gases, pollution, or vapor away."
    duration: 30 minutes
    effect: Manipulation
    level: 3
    name: Aeromancy
    range: Short
    roll: true
    school:
  Flame Dart:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: Launches a single small, flaming projectile at a target, doing damage.
    fs3_attack: true
    effect: Damage
    level: 3
    line_of_sight: true
    name: Flame Dart
    range: Short
    school: Aether
    target_num: 1
    weapon: Flame Dart
  Pyromancy:
    area: 5 cubic feet
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: "For the duration of the spell, the caster can influence up to 5 cubic feet of flames, forming them into simple non-weaponized shapes that animate at their direction. Within the size limit, they can make flames grow or snuff them out entirely. When the spell ends, the flames return to their natural state in their current location."
    duration: 30 minutes
    effect: Manipulation
    level: 3
    line_of_sight: true
    name: Pyromancy
    range: Short
    roll: true
    school: Aether
  Shock:
    available: true
    casting_time: 1 round
    damage_type: None
    desc: Shock an opponent with a burst of electricity, stunning them for one round.
    duration: 1 round
    effect: Stun
    is_stun: true
    rounds: 1
    level: 3
    line_of_sight: true
    name: Shock
    range: Short
    school: Aether
    target_num: 1
    weapon: Stun (Aether)
  Wind Shield:
    available: true
    casting_time: 1 round
    desc: "Deflect attacks directed against you or a single comrade with gusting winds."
    duration: 3 rounds
    effect: Shield
    is_shield: true
    level: 3
    line_of_sight: true
    name: Wind Shield
    range: Short
    rounds: 3
    school: Aether
    shields_against: All
    target_num: 1
#---------------
# LEVEL 4
#---------------
  Create Sound:
    available: true
    casting_time: 30 seconds
    damage_type: Bypass
    desc: "For the duration of the spell, the caster can vibrate the air to create simple sounds. These sounds can be a single noise, a melody, or a short sentence of up to fifteen, one-syllable words. Sound created cannot be louder than 80 db (a loud truck, a vacuum)."
    duration: 15 minutes
    effect: Illusion
    level: 4
    name: Create Sound
    range: Short
    roll: true
    school: Aether
  Fire Weapon:
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: Augment one specified pre-existing weapon with dancing flames, increasing its damage.
    duration: 3 hours
    effect: Buff
    is_potion: true
    level: 4
    name: Fire Weapon
    range: Touch
    rounds: 100
    school: Aether
    target_num: 1
    weapon_specials: Fire
    weapon: Spell
  Lightning Ball:
    available: true
    casting_time: 1 round
    damage_type: Physical
    desc: Send a small sphere of electrical energy at a target, doing damage.
    fs3_attack: true
    effect: Damage
    level: 4
    line_of_sight: true
    name: Lightning Ball
    range: Short
    school: Aether
    target_num: 1
    weapon: Lightning Ball
  Lightning Weapon:
    available: true
    casting_time: 1 round
    desc: Augment a pre-existing weapon with crackling electricity, increasing its damage and speed.
    effect: Buff
    duration: 3 hours
    is_potion: true
    level: 4
    name: Lightning Weapon
    range: Touch
    rounds: 100
    school: Aether
    target_num: 1
    weapon_specials: Lightning
    weapon: Spell
  Simple Illusion:
    area: 5 cubic feet
    available: true
    casting_time: 30 seconds
    damage_type: Bypass
    desc: "Create a convincing illusion of a single subject that fools most observers. It is able to animate at the caster's discretion. The illusion cannot be larger than 3 cubic yards.\n\n If the illusion serves to hide the targets in combat, they should change their stance to 'Hidden' and attacks targeting them which require line of sight receive a -3 attack mod."
    duration: 15 minutes
    effect: Illusion
    level: 4
    line_of_sight: true
    name: Simple Illusion
    range: Short
    roll: true
    school: Aether
#---------------
# LEVEL 5
#---------------
  Breathless:
    area: 10 ft radius
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: 'Draw all oxygen from an area, dousing any flames present and creating oxygen deprivation for an air-breathing creature of your choice caught in its range.'
    duration: 1 round
    effect: Damage
    fs3_attack: true
    level: 5
    name: Breathless
    range: Short
    school: Aether
    target_num: 1
    weapon: Breathless
  # Darkness:
  #   available: false
  #   area: 10 ft radius
  #   casting_time: 1 round
  #   damage_type: Bypass
  #   defense_mod: 3
  #   desc:  "The caster quenches all light within a 10 ft radius area, making anything caught in the darkness hidden and blind. Spell does not put out any sources of light, but stops them from illuminating the area.  Darkened area cannot be moved.\n\nAttacks which require line of sight may target those within the darkness, but hidden targets receive an automatic +3 to defense. Targets should be selected via a random roll (`dice d1<number of targets>`, select alphabetically) and should include any allies. Attacks which do not require line of sight may target hidden creatures with a +3 to attack (to cancel the +3 defense).\n\nBlinded beings may attack at GM discretion with a -3 attack mod (not automatic).\n\nDoes not effect spells, senses and abilities that do not require line of sight."
  #   duration: 15 minutes
  #   effect: Defense
  #   level: 5
  #   line_of_sight: true
  #   name: Darkness
  #   range: Short
  #   rounds: 90
  #   school: Aether
  #   stance: hidden
  #   target_num: 3
  Fireball:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: A ball of fire hurls toward two targets in its path, doing fire damage.
    effect: AOE Damage
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Fireball
    range: Short
    school: Aether
    target_num: 2
    weapon: Fireball
  Wind Wall:
    available: true
    casting_time: 1 round
    desc: "Deflect attacks directed against up to 3 targets with gusting winds."
    duration: 3 rounds
    effect: Shield
    is_shield: true
    level: 5
    line_of_sight: true
    name: Wind Wall
    range: Short
    rounds: 3
    school: Aether
    shields_against: All
    target_num: 3
#---------------
# LEVEL 6
#---------------
  Flares:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: Colorful flares explode outwards from central points. The bursts of intense heat sear through anything in their path, affecting up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Flares
    range: Long
    school: Aether
    target_num: 3
    weapon: Flares
  Lightning Bolt:
    available: true
    casting_time: 1 round
    desc: The caster calls a bolt of lightning from the sky, striking a target and causing damage.
    effect: Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Lightning Bolt
    range: Short
    require_target: true
    school: Aether
    weapon: Lightning Bolt
    target_num: 1
  Sonic Blast:
    available: true
    attack_mod: -2
    casting_time: 1 round
    desc: The target is blasted by an intense burst of sound, leaving them disoriented. For a short time, it is more difficult for the them to take their intended actions.
    defense_mod: -2
    duration: 3 rounds
    effect: Debuff
    level: 6
    line_of_sight: true
    name: Sonic Blast
    range: Long
    rounds: 3
    school: Aether
    spell_mod: -2
    target_num: 1
#---------------
# LEVEL 7
#---------------
  Complex Illusion:
    area: '10 yard radius'
    available: true
    casting_time: 1 minute
    damage_type: Bypass
    desc: "Create a complicated, convincing visual illusion that fools most observers. The illusion can be quite large, with many moving parts, such as a forest scene or a busy street. Can be used to hide groups."
    duration: 30 minutes
    effect: Illusion
    level: 7
    line_of_sight: true
    name: Complex Illusion
    range: Short
    roll: true
    school: Aether
    target_num: 1
  Complex Sound:
    available: true
    casting_time: 1 minute
    damage_type: Bypass
    desc: "For the duration of the spell, the caster can vibrate the air to create complex sounds. These sounds can be several noises at once, music, or conversational speech. Sound created cannot be louder than 100 db (a loud vehicle, a train whistle, a hand drill)."
    duration: 30 min
    effect: Illusion
    level: 7
    name: Complex Sound
    range: Short
    school: Aether
    target_num: 1
  Dust Devils:
    attack_mod: -2
    available: true
    casting_time: 1 round
    damage_type: Bypass
    defense_mod: -2
    desc: "The caster sends a gust of air to stir up small clouds of dirt around up to three targets, obscuring their vision and making it harder for them to attack or defend."
    duration: 3 rounds
    effect: Debuff
    level: 7
    line_of_sight: true
    name: Dust Devils
    range: Short
    rounds: 3
    school: Aether
    target_num: 3
    effect: Debuff
  Pyre:
    available: true
    casting_time: 1 round
    damage_type: Fire
    desc: 'Gouts of flame are summoned up from the air, engulfing the target.'
    effect: Damage
    fs3_attack: true
    level: 7
    line_of_sight: true
    name: Pyre
    range: Long
    school: Aether
    target_num: 1
    weapon: Pyre
#---------------
# LEVEL 8
#---------------
  Lightning Strike:
    available: true
    casting_time: 1 round
    desc: A streak of powerful lightning plunges from the sky to strike a target, doing massive damage.
    effect: Damage
    level: 8
    line_of_sight: true
    fs3_attack: true
    name: Lightning Strike
    range: Long
    school: Aether
    target_num: 1
    weapon: Lightning Strike
  Suffocate:
    available: true
    casting_time: 1 round
    damage_type: Bypass
    desc: "Draw the air from the lungs of a target, making it impossible for them to breathe. \n\nDoes not affect enemies who do not breathe air."
    effect: Damage
    fs3_attack: true
    level: 8
    line_of_sight: true
    name: Suffocate
    range: Long
    school: Aether
    target_num: 1
    weapon: Suffocate
#---------------
# LEVEL 9
#---------------
#---------------
# LEVEL 10
#---------------

