spells:
  Breath Of Healing:
    available: true
    casting_time: 1 round
    desc: Provide a minute amount of healing magic to a target's most severe treatable wound, speeding their healing by up to a day and restoring some of their vigor.
    effect: Heal
    heal_points: 1
    is_potion: true
    level: 1
    name: Breath of Healing
    range: Touch
    school: Corpus
    target_optional: true
    target_num: 1
  Eye Color:
    available: true
    casting_time: 1 round
    desc: The caster can change the color of their eyes to any naturally occurring hue for a duration of up to one hour.
    duration: 10 minutes
    effect: Transformation
    is_potion: true
    level: 1
    name: Eye Color
    range: Self
    roll: true
    school: Corpus
    target_num: 1
  Graze:
    available: true
    casting_time: 1 round
    desc: Give a touched target a minor injury.
    effect: Damage
    is_potion: true
    level: 1
    name: Graze
    range: Touch
    roll: true
    school: Corpus
    target_num: 1
    target_optional: true
  Minor Allergy:
    available: true
    casting_time: 1 round
    desc: Cause a target to have a mild allergic reaction such as sneezing, a small itchy spot on the skin, mildly itchy eyes, or minor congestion. Treatment with antihistamines or other medicines that affect symptoms are effective against this spell.
    duration: 10 minutes
    effect: Other
    is_potion: true
    level: 1
    name: Minor Allergy
    range: Touch
    roll: true
    school: Corpus
    target_num: 1
    target_optional: true
#Level Two
  Change Hair:
    available: true
    casting_time: 1 round
    desc: "The caster can alter the color, texture, or length of hair for a duration of up to one hour. The spell can add up to an inch to already-existing hair."
    duration: 1 hour
    effect: Transformation
    is_potion: true
    level: 1
    name: Change Hair
    range: Touch
    roll: true
    school: Corpus
    target_num: 1
  Minor Heal:
    available: true
    casting_time: 1 round
    desc: Provide a minor amount of healing magic to a target's most severe treatable wound, speeding their healing by up to a couple of days and restoring some of their vigor.
    effect: Heal
    heal_points: 3
    is_potion: true
    level: 2
    line_of_sight: true
    name: Minor Heal
    range: Short
    school: Corpus
    target_num: 1
    target_optional: true
  Touch Of Enfeeblement:
    attack_mod: -1
    available: true
    casting_time: 1 round
    defense_mod: -1
    desc: 'Target loses their strength, becoming physically weak and fatigued. '
    duration: 1 round
    effect: Debuff
    is_potion: true
    level: 2
    line_of_sight: true
    name: Touch of Enfeeblement
    range: Touch
    rounds: 1
    school: Corpus
    target_num: 1
    target_optional: true
  #Level 3
  Endure Extreme Temperatures:
    available: true
    casting_time: 1 round
    desc: The caster suffers no harm from being in an extremely hot or cold environment, from -20 °F to 200 °F (−129 °C to 93°C).
    duration: 10 minutes
    effect: Buff
    is_potion: true
    level: 3
    name: Endure Extreme Temperatures
    range: Self
    roll: true
    school: Corpus
  Drowsy:
    available: false
    casting_time: 1 round
    desc: Make a target suddenly feel extremely drowsy and cause them to briefly fall asleep. In combat, they are stunned for one round. In other situations, they remain asleep until they are woken or wake naturally.
    duration: Until woken or 20 seconds in situations with disturbances
    effect: Stun
    is_stun: true
    level: 3
    line_of_sight: true
    name: Drowsy
    range: Short
    rounds: 1
    target_num: 1
    target_optional: true
    school: Corpus
  Flesh Wound:
    available: false
    casting_time: 1 round
    damage_desc: Flesh Wound Spell
    damage_inflicted: FLESH
    desc: "Inflict a flesh wound, slowing an enemy down. \n\nSpell ignores target's armor."
    effect: Damage
    level: 3
    name: Flesh Wound
    range: Short
    school: Corpus
    target_num: 1
    target_optional: true
  Medium Heal:
    available: true
    casting_time: 1 round
    desc: Provide a middling amount of healing magic to a target's most severe treatable wound, speeding their healing by up to nearly a week and restoring some of their vigor.
    effect: Heal
    heal_points: 7
    is_potion: true
    level: 3
    line_of_sight: true
    name: Medium Heal
    range: Short
    school: Corpus
    target_num: 1
    target_optional: true
  Remove Cosmetic Scar:
    available: true
    casting_time: 1 round
    desc: "The caster repairs a small area (no more than six square inches) of cosmetic scarring on a target. The spell is unable to affect deeper tissue or heal structural scar damage."
    effect: Heal
    is_potion: true
    level: 3
    name: Remove Cosmetic Scar
    notes: Needs limitations as to how hot and how cold
    range: Touch
    roll: true
    school: Corpus
    target_num: 1
    target_optional: true
  Strength:
    available: true
    casting_time: 1 round
    desc: The caster's strength is increased. They can lift up to an additional 150 lbs, and they hit harder when attacking.
    duration: 1 hour
    effect: Buff
    is_potion: true
    level: 3
    name: Strength
    notes: Should only apply to melee weapons, right?
    range: Self
    rounds: 100
    school: Corpus
    weapon_specials: Strength
    weapon: Spell
  #Level 4
  Agility:
    available: true
    casting_time: 1 round
    defense_mod: 2
    desc: The caster's reflexes are improved, increasing their defensive abilities and their reaction speed.
    duration: 5 rounds
    effect: Buff
    is_potion: true
    level: 4
    name: Agility
    notes: 'Defense mod is static for 5 rounds, but +1 initiative stays in place. '
    range: Self
    rounds: 5
    school: Corpus
    weapon_specials: Agility
    weapon: Spell
  Diagnose:
    available: true
    casting_time: 1 round
    desc: "Caster can diagnose diseases, injuries, and other physical ailments or conditions in a target with accuracy. The caster is able to pinpoint exactly what the conditions are, where they are located, and their scope. While it can sense the symptoms and manifestations of a malady caused by magic, it cannot sense the magical effects or determine the magical cause.\n\nObtaining GM-provided information via the casting of this spell does not cost Luck."
    duration: 5 rounds
    effect: Other
    is_potion: true
    level: 4
    name: Diagnose
    range: Touch
    roll: true
    school: Corpus
    target_optional: true
    target_num: 1
  Exoskeleton:
    armor: Exoskeleton
    available: true
    casting_time: 1 round
    desc: Caster weaponizes and protects their own body by growing an exoskeleton. A bone sword grows as an extension of one hand.
    duration: 3 hours
    effect: Armor
    is_potion: true
    level: 4
    name: Exoskeleton
    range: Self
    school: Corpus
    weapon: Exoskeleton
  Impair:
    available: true
    casting_time: 1 round
    damage_desc: Impair Spell
    damage_inflicted: IMPAIR
    desc: "Inflict an impaired wound, making it difficult for an enemy to use the affected body part. \n\nSpell ignores target's armor."
    effect: Damage
    level: 4
    line_of_sight: true
    name: Impair
    notes: Desc on this probably needs fixed to match others.  Also needs tested to
      see if level is appropriate
    range: Short
    roll: false
    school: Corpus
    target_num: 1
    target_optional: true
  Minor Group Heal:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    desc: 'Provide a minor amount of healing magic to the most severe treatable wound of up to three targets the caster can see, speeding their healing by up to a couple of days and restoring some of their vigor. '
    effect: Heal
    heal_points: 3
    level: 4
    line_of_sight: true
    name: Minor Group Heal
    range: Short
    school: Corpus
    target_num: 3
    target_optional: true
  Potions (Corpus):
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    effect: Other
    level: 4
    name: Potions (Corpus)
    school: Corpus
    available: true
  Vitality Weapon:
    available: true
    casting_time: 1 round
    desc: Augment one specified pre-existing weapon with the forces of life and death themselves. It does slightly more damage, and when cast, a small amount of healing energy is restored to the wielder.
    duration: 3 hours
    effect: Buff
    heal_points: 3
    is_potion: true
    level: 4
    name: Vitality Weapon
    notes: I want this to work so bad, but I'm just not sure it can without a TON  of custom code.  Maybe we can just dumb it down so that casting it gives you  a little healing boost.
    range: Touch
    rounds: 100
    school: Corpus
    target_num: 1
    target_optional: true
    weapon_specials: Vitality
    weapon: Spell
  #Level 5
  Disable:
    available: true
    casting_time: 1 round
    desc: Subdue an enemy by paralyzing their limbs, immobilizing them briefly.
    duration: 2 rounds
    effect: Stun
    is_stun: true
    level: 5
    line_of_sight: true
    name: Disable
    range: Long
    rounds: 2
    target_num: 1
    target_optional: true
    school: Corpus
  Grow Self:
    available: false
    casting_time: 1 round
    desc: "The caster instantly enlarges their own body, multiplying their height and weight by 3. \n\nIf there is insufficient space for growth, the caster increases to the maximum possible size and makes a brawn check to burst any enclosures. \n\nAll equipment worn or carried by a creature is similarly enlarged by the spell.  Any item that leaves the caster's possession instantly returns to its normal size."
    duration: 5 rounds
    effect: TransformationBuff
    level: 5
    name: Grow Self
    range: Self
    roll: true
    rounds: 6
    school: Corpus
    weapon_specials: Grow
    weapon: Spell
  Revive:
    available: true
    casting_time: 1 round
    desc: 'Return a knocked out comrade to the fight.'
    effect: Revive
    is_revive: true
    level: 5
    line_of_sight: true
    name: Revive
    range: Short
    school: Corpus
    target_num: 1
    target_optional: true
  Shrink Self:
    available: true
    casting_time: 1 round
    desc: "The caster\u2019s height and weight is divided by 8. All equipment worn or carried by a creature is similarly reduced by the spell. Any item that leaves the caster\u2019s possession instantly returns to its normal size."
    duration: 5 rounds
    effect: Transformation
    level: 5
    name: Shrink Self
    range: Self
    rounds: 10
    school: Corpus
    weapon_specials: Shrink
    weapon: Spell
  #Level 6
  Familiar (Corpus):
    desc: 'A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. Familiars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles.'
    effect: Other
    level: 6
    name: Familiar (Corpus)
    roll: true
    school: Corpus
    casting_time: 3 hours
    range: Short
    line_of_sight: true
    available: true
  Massive Heal:
    available: true
    casting_time: 1 round
    desc: Provide a massive amount of healing magic to a target's treatable wound, speeding their natural healing by several weeks and restoring some of their vigor.
    effect: Heal
    heal_points: 17
    level: 6
    line_of_sight: true
    name: Massive Heal
    range: Long
    roll: false
    school: Corpus
    target_num: 1
    target_optional: true
  Revenant:
    available: true
    casting_time: 1 round
    desc: A sapient creature who has died in the last 30 seconds is reanimated and bound to do the caster's bidding. Its mind remains dead, but it can perform simple tasks and come to the caster's aid in battle. It cannot cast spells. When the spell ends, the revenant returns to its dead state.
    duration: 10 minutes
    effect: Other
    level: 6
    line_of_sight: true
    name: Revenant
    range: Short
    roll: true
    school: Corpus
  Speed Boost:
    available: false
    attack_mod: 2
    casting_time: 1 round
    defense_mod: 2
    desc: "The target's strength and reflexes are improved, increasing the speed at which they can move. They are able to attack and dodge faster and can run up to 40 mph for the duration of the spell."
    duration: 2 min
    effect: Buff
    level: 6
    name: Speed Boost
    range: Self
    rounds: 12
    school: Corpus
    weapon_specials: Speed Boost
  #Level 7
  Brink Of Death:
    available: true
    casting_time: 1 round
    desc: "Return someone who has died in the last 30 seconds to life at the cost of the caster''s own stamina.  \n\n A revived target is unable to return to the fight without further healing. They are both incapacitated and suffering from spell fatigue.\n\n
    The caster is unable to fight or cast spells for 24 hours.\n\n"
    effect: Resurrection
    is_res: true
    level: 7
    name: Brink Of Death
    range: Touch
    school: Corpus
    target_num: 1
    target_optional: true
  Energize Dimensional Anchor (Corpus):
    available: true
    casting_time: 2 minutes
    desc: Provide necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently close an interdimensional portal.
    effect: Travel
    level: 7
    name: Dimensional Anchor
    range: Touch
    roll: true
    school: Corpus
  Group Revive:
    area: 15 yard radius
    available: true
    casting_time: 1 round
    desc: Return up to three knocked out comrades to the fight.
    effect: Revive
    is_res: false
    is_revive: true
    level: 7
    line_of_sight: true
    name: Group Revive
    range: Long
    roll: false
    school: Corpus
    target_num: 3
    target_optional: true
  Incorporeal:
    available: false
    casting_time: 1 Round
    defense_mod: 20
    desc: "The caster temporarily transforms their physical body into an incorporeal state. For the spell's duration, the caster can enter or pass through solid objects including lifeforms as easily as one might pass through air.\n\n While incorporeal, the caster cannot breathe, effectively limiting their ability to remain incorporeal or act according to how long they can hold their breath. Base speed and mode of movement remain the same."
    duration: 5 minutes
    effect: Travel
    is_res: false
    level: 7
    name: Incorporeal
    range: Self
    roll: false
    school: Corpus
    target_num: 1
  Miasma:
    attack_mod: -3
    available: true
    casting_time: 1 Round
    defense_mod: -3
    desc: "The caster draws contaminants, decay, and disease into a targets' body, filling their throat and mouth with unpalatable noxious vapors. The miasma spreads to up to two targets nearby. All targets feel ill, which saps them of their strength and vitality for a period of time."
    duration: 3 rounds
    effect: Debuff
    level: 7
    line_of_sight: true
    name: Miasma
    range: Long
    rounds: 3
    school: Corpus
    target_num: 3
    target_optional: true
  #Level 8
  Elaborate Shapeshift:
    available: false
    casting_time: 1 round
    desc: "The caster can transform their body or body of a single sapient target. These transformations can be either partial adjustments or more complete changes.\n\n The caster can manipulate the entire appearance of the target, including their apparent age, gender, size and physicality (may effect Brawn and Reflexes stat). The caster can also transform the target into another sapient species. The shapeshift is permanent unless the spell is used again."
    effect: Transformation
    level: 8
    name: Elaborate Shapeshift
    range: Short
    roll: true
    school: Corpus
    target_optional: true
    target_num: 1
  Meld:
    available: false
    casting_time: 1 round
    desc: The caster melds their physical form with an inanimate object with the same or greater mass as their body. While melded, the caster can see and hear what transpires around them, but cannot effect it in any way. They cannot cast magic, speak, or move, and are only detectable through appropriate magic means such as Spirit or Corpus magic.
    duration: 24 hours
    effect: Transformation
    level: 8
    name: Meld
    range: Self
    roll: true
    school: Corpus
  Siphon Of Body:
    available: false
    casting_time: 3 hours
    desc: "A target siphons the magic of those around them in order to increase their power, while simultaneously decreasing the power of others.\n\nThe target receives a bonus to physical abilities that increases as they learn magic (mod=highest spell level), while those within physical range and those with a significant emotional connection to the target receive a negative modifier to physical abilities, up to -2."
    duration: Permanent
    effect: Buff
    level: 8
    line_of_sight: true
    name: Siphon Of Body
    range: Short
    roll: true
    school: Spirit
