spells:
  Huxian's Curse:
    attack_mod: -2
    available: false
    casting_time: 1 round
    defense_mod: -2
    desc: "Attempts made in Asher's presence suffer a negative modifier. "
    duration: 100 rounds
    is_potion: true
    level: 1
    line_of_sight: true
    name: Huxian's Curse
    range: Short
    rounds: 100
    school: Spirit
    spell_mod: -2
    target_num: 20
    target_optional: true
  Locate Object:
    available: true
    casting_time: 1 round
    desc: The caster is able to sense the direction of an object they have physically encountered.
    duration: 10 minutes
    effect: Other
    level: 1
    name: Locate Object
    range: Short
    roll: true
    school: Spirit
  Object Whisper:
    available: true
    casting_time: 1 round
    desc: "Caster hears a random, uncontrollable thought (no more than a short sentence of up to 10 words) from an object held by a sapient creature in the past 48 hours. Successive casts on the same object yield the same sentence. When possible, the sentence should be chosen by a GM or someone other than the caster."
    effect: Communication
    is_potion: true
    level: 1
    line_of_sight: true
    name: Object Whisper
    range: Touch
    roll: true
    school: Spirit
    target_num: 0
  Share Emotion:
    available: true
    casting_time: 1 round
    desc: Share a single dominant emotion with a target within visual range of the caster.
    duration: 10 minutes
    effect: Psionic
    level: 1
    line_of_sight: true
    name: Share Emotion
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Share Image:
    available: true
    casting_time: 1 round
    desc: 'The caster can share a still mental image with another person via telepathy.'
    duration: 10 minutes
    effect: Psionic
    level: 1
    name: Share Image
    range: Long
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  #Level 2
  Beckon:
    available: true
    casting_time: 1 round
    desc: "You create the ghostly image of a hand (or anything small and of the caster) which you can send to find anyone. The hand leads that person back to you if they are willing to follow."
    duration: 1 hour
    effect: Communication
    level: 2
    name: Beckon
    range: Long
    roll: true
    school: Spirit
  Dampen Emotion:
    available: true
    casting_time: 1 round
    desc: "Reduce the strength of the most dominant emotion that the target is feeling. For example, anger may be suppressed into annoyance, joy into serenity, or grief into sadness."
    duration: 10 minutes
    effect: Psionic
    level: 2
    line_of_sight: true
    name: Dampen Emotion
    range: Short
    roll: true
    school: Spirit
    target_optional: true
    target_num: 1
  Restful Sleep:
    available: false
    casting_time: 1 round
    desc: "Cast a spell on a target that helps ease the mind toward sleep. Falling asleep becomes easy. For the duration, sleep is undisturbed by natural dreams, letting the target rest easy. When the spell is ended, sleep becomes natural and continues or is ended according to natural means.\n\n
    Has no noticeable effect on those who do not attempt to sleep."
    duration: 1 hour
    effect: Other
    is_potion: true
    level: 2
    line_of_sight: true
    name: Restful Sleep
    range: Touch
    roll: true
    school: Spirit
    target_optional: true
    target_num: 1
  Telepathic Correspondence:
    available: true
    casting_time: 1 round
    desc: "Cast a spell on a target that enables the caster to hold a telepathic conversation with one person at a time. Initial casting requires concentration, after which this spell remains in effect without requiring maintenance or taking up your action during a round."
    duration: 1 hour
    effect: Psionic
    level: 2
    name: Telepathic Correspondance
    range: Long
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
    #Level 3
  Awaken Terror:
    available: false
    casting_time: 1 round
    desc: Target becomes afraid of the caster and attempts to flee to the nearest place they could safely hide. They will not move in the direction of the caster for the duration of the spell unless forced.
    effect: Stun
    is_stun: true
    rounds: 1
    level: 3
    line_of_sight: true
    name: Awaken Terror
    range: Short
    school: Spirit
    target_num: 1
    target_optional: true
    weapon: Stun (Spirit)
  Charmed:
    available: false
    casting_time: 1 round
    desc: Target becomes charmed by the caster and attempts to move toward them. They are neutral toward all parties and will neither aid nor attack while under the spell. The spell is broken if they are hit by an attack.
    effect: Stun
    is_stun: true
    rounds: 1
    level: 3
    line_of_sight: true
    name: Charmed
    range: Short
    school: Spirit
    target_num: 1
    target_optional: true
    weapon: Stun (Spirit)
  Comprehend Languages:
    available: true
    casting_time: 1 round
    desc: 'The target is able to comprehend any spoken or written language for the duration of the spell. This does not apply to text written in code.'
    duration: 24 hours
    effect: Communication
    is_potion: true
    level: 3
    name: Comprehend Languages
    range: Touch
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Emotional Aura:
    available: true
    casting_time: 1 round
    desc: One target becomes outlined in light visible only to the caster. The color of the light corresponds to the target's current emotional status.
    duration: 1 round
    effect: Psionic
    level: 3
    line_of_sight: true
    name: Emotional Aura
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
    effect: Psionic
  Flagging Spirits:
    available: false
    casting_time: 1 round
    desc: Target loses their will to fight.
    effect: Stun
    fs3_attack: true
    is_stun: true
    rounds: 1
    level: 3
    line_of_sight: true
    name: Flagging Spirits
    range: Short
    school: Spirit
    target_num: 1
    target_optional: true
    weapon: Stun (Spirit)
  Mind Bolt:
    available: false
    casting_time: 1 round
    desc: The caster delivers a minor assault on the thought pathways of any one sapient creature, doing damage.
    effect: Damage
    fs3_attack: true
    level: 3
    line_of_sight: true
    name: Mind Bolt
    range: Short
    school: Spirit
    target_num: 1
    target_optional: true
    weapon: Mind Bolt
  Minor Jinx:
    attack_mod: -1
    available: true
    casting_time: 1 round
    defense_mod: -1
    desc: "The target's chance of botching their intended action increases slightly. "
    duration: 2 rounds
    effect: Debuff
    is_potion: true
    level: 3
    line_of_sight: true
    name: Minor Jinx
    range: Short
    rounds: 2
    school: Spirit
    spell_mod: -1
    target_num: 1
    target_optional: true
  Minor Luck:
    attack_mod: 1
    available: true
    casting_time: 1 round
    defense_mod: 1
    desc: The target's chance of succeeding in their intended action is improved slightly.
    duration: 2 rounds
    effect: Buff
    is_potion: true
    level: 3
    line_of_sight: true
    name: Minor Luck
    range: Short
    rounds: 2
    school: Spirit
    spell_mod: 1
    target_num: 1
    target_optional: true
  Group Comprehend Languages:
    available: true
    casting_time: 1 round
    desc: "Up to 4 targets of the caster's choice are able to comprehend any spoken or written language for the duration of the spell. This does not apply to text written in code."
    duration: 24 hours
    effect: Communication
    is_potion: true
    level: 4
    name: Group Comprehend Languages
    range: Short
    roll: true
    school: Spirit
    target_num: 3
    target_optional: true
  Share Sensation:
    available: false
    casting_time: 1 round
    desc: "The caster shares any specific physical sensation that they are currently feeling with a target."
    effect: Psionic
    level: 3
    name: Share Sensation
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
    effect: Psionic
  #Level 4
  Group Telepathic Correspondence:
    available: false
    casting_time: 1 round
    desc: "Up to 4 targets, including the caster, are able to hold a telepathic conversation together. All targets are part of a single conversation for the duration of the spell. Initial casting requires concentration, after which this spell remains in effect without requiring maintenance or taking up your action during a round."
    duration: 1 hour
    effect: Psionic
    level: 4
    name: Group Telepathic Correspondence
    range: Long
    roll: true
    school: Spirit
    target_num: 4
    target_optional: true
  Mind Shield:
    available: true
    casting_time: 1 round
    desc: "Cast a protective psionic shield on a target. The strength of the shield is determined by the caster's Spirit roll. When the target is targetted by another psionic spell, the opposing caster rolls Spirit vs the strength of the shield to determine whether the spell succeeds, or whether the mind shield holds."
    effect: Defense
    level: 4
    line_of_sight: true
    name: Mind Shield
    range: Short
    school: Spirit
    target_num: 1
    target_optional: true
    duration: 5 minutes (30 rounds)
    rounds: 30
  Potions (Spirit):
    available: true
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    level: 4
    name: Potions (Spirit)
    school: Spirit
  Spell Fatigue Heal:
    available: false
    casting_time: 1 round
    desc: Heal a target of spell fatigue. Cannot be cast on oneself.
    effect: Heal
    is_potion: true
    level: 4
    line_of_sight: true
    name: Spell Fatigue Heal
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Spirit Of Pacifism:
    available: false
    casting_time: 1 round
    desc: So long as the caster does not attack or block, they are not seen as an viable threat or target by aggressors. They are not immune to unintended AoE attacks.
    duration: 10 minutes
    effect: Defense
    is_potion: true
    level: 4
    name: Spirit of Pacifism
    range: Self
    roll: true
    school: Spirit
  Telepathic Reading:
    available: true
    casting_time: 1 round
    desc: Read someone's surface thoughts.
    duration: 30 minutes
    effect: Psionic
    level: 4
    name: Telepathic Reading
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Commune With Local Spirit:
    available: true
    casting_time: 1 round to conjure, 1 round per question.
    desc: "You may contact a [spirit](http://spiritlakemu.com/wiki/creatures#spirits-and-ghosts) and ask it one question per      round. The spirit s knowledge is limited to matters within its immediate area or expertise"
    duration: 15 minutes
    effect: Communication
    level: 5
    name: Commune with Local Spirit
    range: Short
    roll: true
    school: Spirit
    target_num: 1
  Medium Jinx:
    attack_mod: -2
    available: false
    casting_time: 1 round
    defense_mod: -2
    desc: "The target's chance of botching their intended action increases slightly more."
    duration: 3 rounds
    effect: Debuff
    level: 5
    line_of_sight: true
    name: Medium Jinx
    range: Long
    rounds: 3
    school: Spirit
    spell_mod: -2
    target_num: 1
    target_optional: true
  Medium Luck:
    attack_mod: 2
    available: true
    casting_time: 1 round
    defense_mod: 2
    desc: "The target's chance of succeeding in their intended action is improved slightly more."
    duration: 3 rounds
    effect: Buff
    level: 5
    line_of_sight: true
    name: Medium Luck
    range: Long
    rounds: 3
    school: Spirit
    spell_mod: 2
    target_num: 1
    target_optional: true
  Memory Dive:
    available: true
    casting_time: "1+ rounds at GM\u2019s discretion."
    desc: "Search someone\u2019s memory for specific events."
    duration: 30 minutes
    effect: Psionic
    level: 5
    name: Memory Dive
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Pass Unseen:
    available: false
    casting_time: 1 round
    desc: "The caster's presence is completely ignored by all thinking beings or creatures. \n\nThere is no physical change, the mind simply rejects any sensory signs of the caster for the duration of the spell. Large disruptions or sudden violence by the caster will break the spell."
    duration: 10 minutes
    effect: Defense
    level: 5
    name: Pass Unseen
    range: Self
    roll: true
    school: Spirit
  Simple Command:
    available: true
    casting_time: 1 round
    desc: "Implant a single one-word command in a target's mind.They cannot be commanded to harm themselves.\n\n Unprotected minds must follow the command."
    duration: 5 minutes
    effect: Psionic
    level: 5
    line_of_sight: true
    name: Simple Command
    range: Short
    roll: true
    school: Spirit
    target_num: 3
    target_optional: true
  Familiar (Spirit):
    desc: "A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. \n\nFamiliars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles."
    effect: Other
    level: 6
    name: Familiar
    roll: true
    school: Spirit
    casting_time: 3 hours
    range: Short
    line_of_sight: true
    available: true
  Mass Awaken Terror:
    available: false
    desc: Targets become afraid of the caster and attempt to flee to the nearest place they could safely hide. They will not move in the direction of the caster or attack for the duration of the spell unless forced.
    effect: Stun
    is_stun: true
    level: 6
    name: Mass Awaken Terror
    roll: true
    school: Spirit
    target_num: 3
    target_optional: true
  Rewrite Memory:
    available: true
    casting_time: "1 round to cast, additional rounds for rewriting at GM's discretion."
    desc: "Rewrite or remove someone's memory of an event up to 1 hour long."
    duration: 30 minutes
    effect: Psionic
    level: 6
    name: Rewrite Memory
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Sleep:
    available: false
    casting_time: 1 round
    desc: The target becomes overwhelmed by the desire to sleep and falls unconscious. They are only awoken if attacked or if an ally uses a round to attempt to awaken them.
    duration: 15 minutes
    effect: Stun
    is_stun: true
    level: 6
    name: Sleep
    range: Short
    roll: true
    rounds: 90
    school: Spirit
    target_num: 1
    target_optional: true
  Clarity:
    available: true
    casting_time: 1 round
    desc: "The caster extends their senses to all beings within range. While their  body lies senseless and incapacitated, they see and feel everything sensed by every sapient creature in that area. They can also identify the presence, quantity, and location of non-sapient creatures.\n\n
    The caster can choose to absorb all experiences at a surface level, or focus their attention on up to five individuals at a time for more details."
    duration: 15 minutes
    effect: Communication
    level: 7
    name: Clarity
    range: Long
    roll: true
    school: Spirit
  Energize Dimensional Anchor (Spirit):
    available: false
    casting_time: 2 minutes
    desc: "Provide necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently close an interdimensional portal."
    level: 7
    name: Dimensional Anchor
    range: Touch
    roll: true
    school: Spirit
  Dreamtrap:
    available: false
    casting_time: 1 round
    desc: "The caster puts their their target to sleep (if awake) and draws them into a dream. The caster has control of the dream and its events, although they may allow the target's subconscious to fill in details. While in the dream, all encounters seem real, though physical damage in the dream world is imaginary and vanishes upon awakening."
    duration: 2 hours
    effect: Psionic
    level: 7
    name: Dreamtrap
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Rewrite History:
    available: false
    casting_time: "1 round to cast, plus additional rounds at GM's discretion according to complexity of the rewrite."
    desc: "Permanently rewrite the mind of the target, changing or replacing any and all memories. \n\nThe target\u2019s mind, in conjunction with the spell, will fill in the gaps and discrepancies, glossing over irregularities."
    effect: Psionic
    level: 7
    name: Rewrite History
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  #Level 8
  Binding Oath:
    available: false
    casting_time: 1 round
    desc: "The caster specifies a contract which the target agrees to. Upon agreement, the magical oath is sealed./n/n
    Either party breaking the oath results in an instant impairment of their mental facilities and the loss of all memories since the moment the oath was enacted. Their 'Wits' and 'Perception' are lowered to 1, and they are incapable of higher-level mental tasks such as complicated mathematics, science, and reading. Mentally, they will be capable at the level of a three year old./n/n
    Memories return sporadically over the course of six months. Cognitive development a year, eventually returning the oath breaker's mental facilities to what they were before."
    level: 8
    line_of_sight: true
    name: Binding Oath
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Curse Of Twilight:
    available: false
    casting_time: 1 round
    desc: "The target of the spell is forgotten by those who know them. They are not unseen, but are treated as strangers, any reference to who they were denied. Any new connections forged are reset at twilight of each day."
    duration: 1 year and 1 day
    effect: Psionic
    level: 8
    line_of_sight: true
    name: Curse of Twilight
    range: Short
    roll: true
    school: Spirit
    target_num: 1
    target_optional: true
  Heirloom Object:
    available: true
    casting_time: 3 hours
    desc: "The caster is capable of concealing a fragment of their spirit and binding it to an inanimate object. If the caster is killed, their full spirit enters the object after 60 seconds.\n\nUsing this spell does not harm the caster. Though it may contain a portion of the caster's spirit, they have no awareness of the object once leaving its presence. \n\nThe object may be stored anywhere, but there must be an open portal path between the caster and the object within 60 seconds of death in order for the spirit to enter the object. Otherwise, they are killed.\n\nOnce their full spirit has entered the object, the caster exists as a sapient object. They are incapable of movement but retain their spell casting abilities. Any who hold the trinket can freely converse with the caster via telepathy.\n\nIf the object is destroyed, so is that piece of the caster\u2019s spirit. If the object is destroyed after the caster fully inhabits it, the caster dies permanently."
    level: 8
    name: Heirloom Object
    range: Touch
    roll: true
    school: Spirit
