
spells:
  Bubble Dance:
    available: true
    casting_time: 1 round
    desc: "Send a stream of water bubbles dancing according to your will. The size of the bubbles can range from foam to fist-sized."
    duration: 10 minutes
    effect: Creation
    level: 1
    name: Bubble Dance
    range: Short
    roll: true
    school: Water
  Create Water:
    area: 1-5 ft radius
    available: true
    casting_time: 1 round
    desc: "Draw up to 2 gallons of clean drinking water from the moisture in the air\u2014possibly creating a downpour or filling many small receptacles.\n\nThe water is generally reflective of the temperature in which it is created, but it is always liquid on creation. The temperature around it may freeze or heat the water after creation."
    effect: Creation
    level: 1
    name: Create Water
    range: Short
    roll: true
    school: Water
  Create Frost:
    area: 1-3 ft radius
    available: true
    casting_time: 1 round
    desc: "Creates a fine layer of frost on a target the caster touches, covering an area up to 3 square feet."
    effect: Creation
    level: 1
    name: Create Frost
    range: Touch
    roll: true
    school: Water
  Minor Fog:
    area: 5 cubic feet
    available: true
    casting_time: 1 round
    desc: A cloud of fog fills a small area, no greater than five cubic feet. The fog may creep along the ground or cling near the caster's skin.
    duration: 10 minutes
    effect: Creation
    level: 1
    name: Minor Fog
    range: Short
    roll: true
    school: Water
  #Level 2
  Chill Touch:
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Caster can cool their hands to a chosen temperature ranging from a minor chill to cold enough to deliver minor cold damage via touch.
    duration: 30 minutes
    effect: Weapon
    is_potion: true
    level: 2
    name: Chill Touch
    range: Touch
    school: Water
    target_num: 1

    weapon: Chill Touch
  Chilled Limbs:
    attack_mod: -1
    available: true
    casting_time: 1 round
    defense_mod: -1
    desc: "Chill someone's limbs, making it difficult for them to move effectively. "
    duration: 1 round
    effect: Debuf
    level: 2
    line_of_sight: true
    name: Chilled Limbs
    range: Short
    rounds: 1
    school: Water
    target_num: 1

  Shape Water:
    area: 5 cubic feet
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can influence up to 5 cubic feet of preexisting water, moving and shaping it into simple non-weaponized shapes that animates at their direction. The caster can control the flow, density, and dispersion of water to form dry spots, move puddles, or reroute small streams. When the spell ends, the water returns to its natural state in its current location."
    duration: 1 hour
    effect: Creation
    level: 2
    line_of_sight: true
    name: Shape Water
    range: Short
    roll: true
    school: Water
  Shape Ice:
    area: 1 cubic foot
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can create or inpfluence up to 1 cubic foot of ice and form it into simple non-weaponized shapes that animate at their direction. Ice returns to its natural - but not necessarily original - state when the spell ends. If the ice was created from water, it will remain ice until it naturally melts."
    duration: 1 hour
    effect: Creation
    level: 2
    line_of_sight: true
    name: Shape Ice
    range: Short
    roll: true
    school: Water
  #Level 3
  Endure Cold:
    available: true
    casting_time: 1 round
    desc: Caster is immune to the negative effects of extreme cold. Spells that do cold damage may be stopped entirely by Endure Cold; when they are not, the damage inflicted is decreased.
    duration: 10 minutes
    effect: Buff
    is_potion: true
    is_shield: true
    level: 3
    name: Endure Cold
    range: Self
    school: Water
    rounds: 60
  Ice Talons:
    available: true
    casting_time: 1 round
    desc: The caster's fingertips become ice talons capable of inflicting damage. Talons can be broken off and thrown for a ranged attack.
    duration: 1 round
    effect: Creation
    fs3_attack: true
    is_potion: true
    level: 3
    name: Ice Talons
    range: Self
    school: Water
    weapon: Ice Talons
  Water Breathing:
    available: true
    casting_time: 1 round
    desc: Create a bubble of air in water, drawing oxygen from the surrounding water to replenish your breathing supply underwater.
    duration: 1 hour
    effect: Other
    is_potion: true
    level: 3
    name: Water Breathing
    range: Self
    roll: true
    school: Water
  Water Cannon:
    available: true
    casting_time: 1 round
    desc: The caster blasts a target with a powerful water attack, knocking them off their feet and incapacitating them for one round.
    duration: 1 round
    effect: Stun
    is_stun: true
    rounds: 1
    level: 3
    line_of_sight: true
    name: Water Cannon
    range: Short
    school: Water
    target_num: 1

    weapon: Stun (Water)
  Water Walk:
    available: true
    casting_time: 1 round
    desc: The caster may tread on a liquid surface as if on solid ground.
    duration: 1 hour
    effect: Travel
    is_potion: true
    level: 3
    name: Water Walk
    range: Self
    roll: true
    school: Water
    target_num: 1
  #Level 4
  Cone Of Cold:
    area: 5 ft maximum width
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Frigid cold emanaes from the caster's hand and extends outward in a cone shape, doing minor cold damage to up to 3 targets. As the ice hits, it explodes, doing additional shrapnel damage.
    effect: AOE Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Cone Of Cold
    range: Short
    school: Water
    target_num: 3

    weapon: Cone Of Cold
  Ice Armor:
    armor: Ice
    available: true
    casting_time: 1 round
    desc: Caster weaponizes and protects their own body by augmenting it with thick sheets of ice that form into talons capping each finger. Increases defenses slightly and adds a bladed weapon.
    duration: 3 hours
    effect: Armor
    damage_type: Cold
    is_potion: true
    level: 4
    name: Ice Armor
    range: Self
    school: Water
    weapon: Ice Armor
  Ice Blast:
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: The caster sends a chunk of snowy ice hurtling at a single target.
    effect: Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Ice Blast
    range: Short
    school: Water
    target_num: 1

    weapon: Ice Blast
  Ice Weapon:
    available: true
    casting_time: 1 round
    desc: Augment one specified pre-existing weapon with a fine coating of freezing ice. Though less useful against armor, this weapon does incredible damage against unprotected skin, even through normal clothing.
    duration: 3 hours
    effect: Buff
    is_potion: true
    level: 4
    name: Ice Weapon
    range: Touch
    rounds: 100
    school: Water
    weapon_specials: Ice
    weapon: Spell
  Potions (Water):
    available: true
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    effect: Other
    level: 4
    name: Potions (Water)
    school: Water
  Purify Water:
    available: true
    casting_time: 10 minutes
    desc: "The caster can purify up to 30 cubic feet of preexisting water, drawing impurities out of the water, such as pollution, small organisms, pyrogens, dissolved compounds, and suspended particles."
    effect: Other
    level: 4
    name: Purify Water
    range: Short
    roll: true
    school: Water
  Slick Ground:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    desc: Coat the ground in slick ice, making footing difficult up to 3 opponents and giving them a penalty to attack.
    duration: 1 round
    effect: Debuff
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Slick Ground
    range: Long
    school: Water
    target_num: 3

    weapon: Slick Ground
  Water Whip:
    available: true
    casting_time: 1 round
    desc: Caster creates a whip out of water, lashing out at a target and doing damage.
    effect: Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Water Whip
    range: Short
    school: Water
    target_num: 1

    weapon: Water Whip
#Level 5
  Cold Calm:
    available: true
    accuracy_mod:
    casting_time: 1 round
    duration: 1 minute
    desc: The caster imbues themselves with a wintry chill, calming and cooling their body to improve their focus. They move a little slower than normal, but can better anticipate attacks to dodge and have greatly improved accuracy for the duration of the spell.
    defense_mod: 2
    effect: Buff
    level: 5
    name: Cold Calm
    range: Self
    rounds: 6
    school: Water
    weapon_specials: Cold Calm
  Exploding Ice:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Send a ball of ice hurtling at a point the caster can see. It explodes into jagged shards on impact, hitting up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Exploding Ice
    range: Long
    school: Water
    target_num: 3

    weapon: Exploding Ice
  Group Endure Cold:
    available: true
    casting_time: 1 round
    desc: Targets are immune to the negative effects of extreme cold up to -346°F (-210 °C). Spells that do cold damage may be stopped entirely by Endure Cold; when they are not, the damage inflicted is decreased.
    duration: 1 hour
    effect: Travel
    is_shield: true
    level: 5
    name: Group Endure Cold
    range: Short
    school: Water
    target_num: 3

    rounds: 600
  Group Water Walk:
    available: true
    casting_time: 1 round
    desc: The caster conveys the ability to walk on a liquid surface as if it were solid ground on up to 3 targets. Each recipient of the spell must remain within 15 yards of each other, or the spell ends for the target that is separated.
    duration: 1 hour
    effect: Travel
    level: 5
    line_of_sight: true
    name: Group Water Walk
    range: Short
    roll: true
    school: Water

    target_num: 3
  Ice Block:
    available: true
    casting_time: 1 round
    desc: "Deflect attacks directed against up to three targets with a wall of ice effectively putting the targets in [cover](https://www.aresmush.com/fs3/fs3-3/combat/#stance)."
    duration: 5 rounds
    effect: Defense
    level: 5
    line_of_sight: true
    name: Ice Block
    range: Short
    roll: true
    rounds: 5
    school: Water
    stance: cover

    target_num: 3
  Reviving Cold:
    available: true
    casting_time: 1 round
    desc: The caster revives a knocked out target with a cold splash of water, returning them to the fight.
    effect: Revive
    is_revive: true
    level: 5
    line_of_sight: true
    name: Reviving Cold
    range: Short
    school: Water
    target_num: 1

  #LEVEL 6
  Familiar (Water):
    available: true
    desc: "A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. \n\nFamiliars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles."
    effect: Other
    level: 6
    name: Familiar (Water)
    roll: true
    school: Water
    casting_time: 3 hours
    range: Short
    line_of_sight: true
  Glacial Ice Armor:
    available: true
    armor: Glacial Ice
    casting_time: 1 round
    desc: "Caster weaponizes and protects the target's body by augmenting it with dense sheets of ice that form into sharp icicles protruding from their knuckles. Increases defenses and adds a weapon."
    duration: 8 hours
    effect: Armor
    level: 6
    name: Glacial Ice Armor
    range: Touch
    school: Water
    weapon: Glacial Ice

    target_num: 1
  Glacial Ice Weapon:
    available: true
    casting_time: 1 round
    desc: "Augment one specified pre-existing weapon with a freezing coating of sharp ice. Though less useful against armor, this weapon does incredible damage against unprotected skin, even through normal clothing."
    duration: 6 hours
    effect: Buff
    level: 6
    name: Glacial Ice Weapon
    range: Touch
    school: Water
    weapon_specials: Glacial Ice

    target_num: 1
  Hydroplane:
    available: true
    casting_time: 1 round
    desc: "The caster manipulates water, snow, or ice to carry themselves at a speed of up to 60 mph. They are able to ski along the surface of any water, snow, or ice. They can also slide beneath the surface to swim at the same fast speeds, able to breathe in the water for the duration of the spell. Mods to defense and attack may be applied at the GM's discretion according to actions taken while in motion."
    duration: 1 hour
    effect: Travel
    level: 6
    name: Hydroplane
    range: Self
    school: Water
  Liquid Form:
    available: true
    casting_time: 1 round
    defense_mod: 10
    desc: "The caster's body becomes clear liquid and cannot be hit by attacks.\n\n While in liquid form, the caster can pass through small holes or narrow openings, even mere cracks, with anything they were carrying at the time the spell was cast.  "
    duration: 5 rounds
    effect: Transformation
    level: 6
    name: Liquid Form
    range: Self
    roll: true
    rounds: 5
    school: Water
  Shatter:
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Ice encases a portion of a target's body completely, cooling it rapidly and doing immense damage. In extreme cases, limbs may freeze completely, or even shatter.
    effect: Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Shatter
    range: Long
    school: Water
    target_num: 1

    weapon: Shatter
#LEVEL 7
  Energize Dimensional Anchor (Water):
    available: true
    casting_time: 2 minutes
    desc: "Provide the necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently open or close an interdimensional portal.\n\nIf cast on an open portal, the caster can sense if the spell's School is the necessary magical energy to enable opening or closing the portal, as well as the magical coordinates of the portal's existence in the magical universe."
    effect: Travel
    level: 7
    name: Energize Dimensional Anchor (Water)
    range: Touch
    roll: true
    school: Water
  Ice Storm:
    area: 20 yard radius
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Jagged shards of ice fall from the sky, doing damage to up to 3 targets within its range. When they hit, they explode, doing further shrapnel damage.
    duration: 1 round
    effect: AOE Damage
    fs3_attack: true
    level: 7
    line_of_sight: true
    name: Ice Storm
    range: Long
    school: Water
    target_num: 3

    weapon: Ice Storm
  Ice Wall:
    area: 20 yards long, 5 yards thick, 10 yards tall
    available: true
    casting_time: 1 round
    desc: "The caster summons a single, solid wall of ice no greater than 20 yards long, 5 yards thick, 10 yards tall. It remains until melted or destroyed."
    effect: Defense
    fs3_attack: false
    level: 7
    line_of_sight: true
    name: Ice Wall
    range: Long
    roll: true
    school: Water
  Mass Hydroplane:
    available: true
    casting_time: 1 round
    desc: "Confers water breathing and the ability to move through water, snow, and ice upon up to 5 targets. They are able to ski across the surface or swim below the surface of any water or snow at a speeds of up to 30 mph. Each recipient of the spell must remain within 30 yards of at least one other recipient, or the spell ends for the target that is separated from the others."
    duration: 30 minutes
    effect: Travel
    level: 7
    line_of_sight: true
    name: Mass Hydroplane
    range: Short
    school: Water

    target_num: 5
  Greater Purify Water:
    available: false
    casting_time: 15 minutes
    desc: "The caster can purify up to 150 cubic feet of preexisting water, drawing impurities out of the water, such as pollution, small organisms, pyrogens, dissolved compounds, suspended particles and magical contaminations."
    effect: Other
    level: 7
    line_of_sight: true
    name: Greater Purify Water
    range: Short
    roll: true
    school: Water
  Waters Of Renewal:
    available: true
    auto_revive: true
    casting_time: 1 round
    desc: "A knocked out target is deluged by waters and soaked through. From beneath the water, they are revived and able to return to the fight. \n\nA revived target has no wounds and no spell fatigue.\n\n A magic user who knows this spell is automatically drenched and revived when they themselves can no longer fight. This takes 1 round after they are knocked out."
    effect: Revive
    level: 7
    line_of_sight: true
    name: Waters of Renewal
    notes: This can work, but needs more coding to remove wounds.
    range: Long
    school: Water
    target_num: 1

  #Level 8
  Land Of Ice:
    area: Up to 1 square mile
    available: false
    casting_time: 1 round
    damage_type: Cold
    desc: Rapidly drop the temperature of an area you can see, causing all moisture to freeze. Jagged balls of ice form in mid air and explode, adding to the damage done to anyone in its path.
    effect: AOE Damage
    fs3_attack: true
    level: 8
    line_of_sight: true
    name: Land Of Ice
    range: Massive
    school: Water
    target_num: 100

    weapon: Land Of Ice
