spells:
  Create Water:
    area: 1-5 ft radius
    available: true
    casting_time: 1 round
    desc: "Draw up to 2 gallons of clean drinking water from the moisture in the air\u2014possibly creating a downpour or filling many small receptacles.\n\nThe water is generally reflective of the temperature in which it is created, but it is always liquid on creation. The temperature around it may freeze or heat the water after creation."
    effect: Creation
    level: 1
    name: Create Water
    range: Short
    roll: true
    school: Water
  Create Frost:
    area: 1-3 ft radius
    available: true
    casting_time: 1 round
    desc: "Creates a fine layer of frost on a target the caster touches, covering an area up to 3 square feet."
    effect: Creation
    level: 1
    name: Create Frost
    range: Touch
    roll: true
    school: Water
  Minor Fog:
    area: 5 cubic feet
    available: true
    casting_time: 1 round
    desc: A cloud of fog fills a small area, no greater than five cubic feet. The fog may creep along the ground or cling near the caster's skin.
    duration: 10 minutes
    effect: Creation
    level: 1
    name: Minor Fog
    range: Short
    roll: true
    school: Water
  #Level 2
  Chill Touch:
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Caster delivers minor cold damage via touch.
    effect: Damage
    fs3_attack: true
    is_potion: true
    level: 2
    name: Chill Touch
    range: Touch
    school: Water
    target_num: 1
    target_optional: true
    weapon: Chill Touch
  Chilled Limbs:
    attack_mod: -1
    available: false
    casting_time: 1 round
    defense_mod: -1
    desc: "Chill someone's limbs, making it difficult for them to move effectively. "
    duration: 1 round
    effect: Debuf
    level: 2
    line_of_sight: true
    name: Chilled Limbs
    range: Short
    rounds: 1
    school: Water
    target_num: 1
    target_optional: true
  Shape Water:
    area: 5 cubic feet
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can influence up to 5 cubic feet of preexisting water, moving and shaping it into simple non-weaponized shapes that animates at their direction. The caster can control the flow, density, and dispersion of water to form dry spots, move puddles, or reroute small streams. When the spell ends, the water returns to its natural state in its current location."
    duration: 1 hour
    effect: Creation
    level: 2
    line_of_sight: true
    name: Shape Water
    range: Short
    roll: true
    school: Water
  Shape Ice:
    area: 1 cubic foot
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can create or inpfluence up to 1 cubic foot of ice and form it into simple non-weaponized shapes that animate at their direction. Ice returns to its natural - but not necessarily original - state when the spell ends. If the ice was created from water, it will remain ice until it naturally melts."
    duration: 1 hour
    effect: Creation
    level: 2
    line_of_sight: true
    name: Shape Ice
    range: Short
    roll: true
    school: Water
  #Level 3
  Endure Cold:
    available: true
    casting_time: 1 round
    desc: Caster is immune to the negative effects of extreme cold.
    duration: 10 minutes
    effect: Buff
    is_potion: true
    level: 3
    name: Endure Cold
    range: Self
    school: Water
    rounds: 60
  Ice Talons:
    available: false
    casting_time: 1 round
    desc: The caster's fingertips become ice talons capable of inflicting damage. Talons can be broken off and thrown for a ranged attack.
    duration: 1 round
    effect: Creation
    fs3_attack: true
    is_potion: true
    level: 3
    name: Ice Talons
    range: Self
    school: Water
    weapon: Ice Talons
  Water Breathing:
    available: true
    casting_time: 1 round
    desc: Create a bubble of air in water, drawing oxygen from the surrounding water to replenish your breathing supply underwater.
    duration: 1 hour
    effect: Other
    is_potion: true
    level: 3
    name: Water Breathing
    range: Self
    roll: true
    school: Water
  Water Cannon:
    available: true
    casting_time: 1 round
    desc: The caster blasts a target with a powerful water attack, knocking them off their feet and incapacitating them for one round.
    effect: Stun
    is_stun: true
    rounds: 1
    level: 3
    line_of_sight: true
    name: Water Cannon
    range: Short
    school: Water
    target_num: 1
    target_optional: true
    weapon: Stun (Water)
  Water Walk:
    available: true
    casting_time: 1 round
    desc: The caster may tread on a liquid surface as if on solid ground.
    duration: 1 hour
    effect: Travel
    is_potion: true
    level: 3
    name: Water Walk
    range: Self
    roll: true
    school: Water
    target_num: 1
  #Level 4
  Cone Of Cold:
    area: 5 ft maximum width
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Frigid cold emanaes from the caster's hand and extends outward in a cone shape, doing minor cold damage to up to 3 targets. As the ice hits, it explodes, doing additional shrapnel damage.
    effect: AOE Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Cone Of Cold
    range: Short
    school: Water
    target_num: 3
    target_optional: true
    weapon: Cone Of Cold
  Ice Armor:
    armor: Ice
    available: true
    casting_time: 1 round
    desc: Caster weaponizes and protects their own body by augmenting it with thick sheets of ice that form into talons capping each finger. Increases defenses slightly and adds a bladed weapon.
    duration: 3 hours
    effect: Armor
    damage_type: Cold
    is_potion: true
    level: 4
    name: Ice Armor
    range: Self
    school: Water
    weapon: Ice Armor
  Ice Blast:
    available: false
    casting_time: 1 round
    damage_type: Cold
    desc: The caster sends a chunk of snowy ice hurtling at a single target.
    effect: Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Ice Blast
    range: Short
    school: Water
    target_num: 1
    target_optional: true
    weapon: Ice Blast
  Ice Weapon:
    available: true
    casting_time: 1 round
    desc: Augment one specified pre-existing weapon with a fine coating of freezing ice. Though less useful against armor, this weapon does incredible damage against unprotected skin, even through normal clothing.
    duration: 3 hours
    effect: Buff
    is_potion: true
    level: 4
    name: Ice Weapon
    range: Touch
    rounds: 100
    school: Water
    weapon_specials: Ice
    weapon: Spell
  Potions (Water):
    available: true
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    effect: Other
    level: 4
    name: Potions (Water)
    school: Water
  Water Whip:
    available: true
    casting_time: 1 round
    desc: Caster creates a whip out of water, lashing out at a target and doing damage.
    effect: Damage
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Water Whip
    range: Short
    school: Water
    target_num: 1
    target_optional: true
    weapon: Water Whip
  Exploding Ice:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Send a ball of ice hurtling at a point the caster can see. It explodes into jagged shards on impact, hitting up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Exploding Ice
    range: Long
    school: Water
    target_num: 3
    target_optional: true
    weapon: Exploding Ice
  Slick Ground:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    desc: Coat the ground in slick ice, making footing difficult up to 3 opponents and giving them a penalty to attack and defense.
    duration: 1 round
    effect: Debuff
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Slick Ground
    range: Long
    school: Water
    target_num: 3
    target_optional: true
    weapon: Slick Ground
  Familiar (Water):
    available: true
    desc: "A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. \n\nFamiliars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles."
    effect: Other
    level: 6
    name: Familiar (Water)
    roll: true
    school: Water
    casting_time: 3 hours
    range: Short
    line_of_sight: true
  Liquid Form:
    available: true
    casting_time: 1 round
    defense_mod: 10
    desc: "The caster's body becomes clear liquid and cannot be hit by attacks.\n\n While in liquid form, the caster can pass through small holes or narrow openings, even mere cracks, with anything they were carrying at the time the spell was cast.  "
    duration: 5 rounds
    effect: Defense
    level: 6
    name: Liquid Form
    range: Self
    roll: true
    rounds: 4
    school: Water
    target_num: 1
  Shatter:
    available: true
    casting_time: 1 round
    damage_type: Cold
    desc: Ice encases a portion of a target's body completely, cooling it rapidly and doing immense damage. In extreme cases, limbs may freeze completely, or even shatter.
    effect: Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Shatter
    range: Long
    school: Water
    target_num: 1
    target_optional: true
    weapon: Shatter
  Energize Dimensional Anchor (Water):
    available: false
    casting_time: 2 minutes
    desc: Provide necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently open or close an interdimensional portal.
    effect: Travel
    level: 7
    name: Dimensional Anchor
    range: Touch
    roll: true
    school: Water
  Ice Storm:
    area: 20 yard radius
    available: false
    casting_time: 1 round
    damage_type: Cold
    desc: Jagged shards of ice fall from the sky, doing damage to up to 3 targets within its range. When they hit, they explode, doing further shrapnel damage.
    duration: 1 round
    effect: AOE Damage
    fs3_attack: true
    level: 7
    line_of_sight: true
    name: Ice Storm
    range: Long
    school: Water
    target_num: 3
    target_optional: true
    weapon: Ice Storm
  Ice Wall:
    area: 20 yards long, 5 yards thick, 10 yards tall
    available: true
    casting_time: 1 round
    desc: "The caster summons a single, solid wall of ice no greater than 20 yards long, 5 yards thick, 10 yards tall. It remains until melted or destroyed."
    effect: Defense
    fs3_attack: false
    level: 7
    line_of_sight: true
    name: Ice Wall
    range: Long
    school: Water
    effect: Defense
  #Level 8
  Land Of Ice:
    area: Up to 1 square mile
    available: false
    casting_time: 1 round
    damage_type: Cold
    desc: Rapidly drop the temperature of an area you can see, causing all moisture to freeze. Jagged balls of ice form in mid air and explode, adding to the damage done to anyone in its path.
    effect: AOE Damage
    fs3_attack: true
    level: 8
    line_of_sight: true
    name: Land Of Ice
    range: Massive
    school: Water
    target_num: 100
    target_optional: true
    weapon: Land Of Ice
