spells:
  Create Crystal:
    available: true
    casting_time: 1 round
    desc: The caster is able to create a permanent shard of crystal of moderate value. The shard may be no larger than 2 inches, but may be very hard and sharp. Colors may vary.
    effect: Creation
    level: 1
    line_of_sight: true
    name: Create Crystal
    range: Short
    roll: true
    school: Earth
  Rock Dance:
    available: true
    casting_time: 1 round
    desc: Send half a dozen pebbles and stones smaller than your fist dancing according to your will.
    duration: 10 minutes
    effect: Other
    level: 1
    line_of_sight: true
    name: Rock Dance
    range: Short
    roll: true
    school: Earth
  #Level 2
  Dustup:
    attack_mod: -1
    available: true
    casting_time: 1 round
    defense_mod: -1
    desc: "The caster kicks up a small cloud of dirt around a target, briefly obscuring their vision and making it harder for them to attack or defend."
    duration: 1 round
    effect: Debuff
    level: 2
    line_of_sight: true
    name: Dustup
    range: Short
    rounds: 1
    school: Earth
    target_num: 1
    target_optional: true
    effect: Debuff
  Shape Stone:
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can cause up to 1 cubic foot of pre-existing rock or stone to form into simple non-weaponized shapes that animate at their direction. Rock or stone returns to its natural - but not necessarily original - state when the spell ends. "
    duration: 1 hour
    effect: Creation
    level: 2
    line_of_sight: true
    range: Short
    roll: true
    school: Earth
  Earth Bolt:
    area: Direct line from caster, 5 yards wide
    available: true
    casting_time: 1 round
    desc: Geomantic force travels through the earth in a straight line, causing rocks to fly into the air and hit up to 3 creatures along its path for one round.
    effect: AOE Damage
    fs3_attack: true
    level: 3
    line_of_sight: true
    name: Earth Bolt
    range: Short
    school: Earth
    target_num: 3
    target_optional: true
    weapon: Earth Bolt
  Floating Earth:
    area: 5 yard radius
    available: true
    casting_time: 1 round
    desc: Create a chunk of earth capable of bearing weight up to 250 lbs and propelling itself through the air at speeds up to 35 mph. Must remain in range or it dissipates.
    duration: 1 hour
    effect: Travel
    level: 3
    line_of_sight: true
    name: Floating Earth
    range: Short
    roll: true
    school: Earth
  Stone Fists:
    available: false
    casting_time: 1 round
    desc: The caster's hands become stone fists capable of inflicting damage.
    duration: 1 round
    effect: Damage
    fs3_attack: true
    is_potion: true
    level: 3
    name: Stone Fists
    range: Self
    school: Earth
    weapon: Stone Fists
  Stone Slam:
    available: true
    casting_time: 1 round
    desc: Slam a stone the size of a basketball into an opponent with force.
    effect: Damage
    fs3_attack: true
    level: 3
    line_of_sight: true
    name: Stone Slam
    range: Short
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Stone Slam
  #Level 4
  Crystalline Armor:
    armor: Crystalline
    available: false
    casting_time: 1 round
    desc: The caster's skin becomes as hard as densely formed crystal to increase defenses significantly. Colors may vary.
    effect: Armor
    duration: 3 hours
    is_potion: true
    level: 4
    name: Crystalline Armor
    range: Self
    school: Earth
  Diamond Weapon:
    available: false
    casting_time: 1 round
    desc: Augment one specified pre-existing weapon with diamond, making it far sharper and increasing its penetration.
    duration: 3 hours
    effect: Buff
    is_potion: true
    level: 4
    name: Diamond Weapon
    range: Touch
    rounds: 100
    school: Earth
    target_num: 1
    target_optional: true
    weapon_specials: Diamond
    weapon: Spell
  Potions (Earth):
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    effect: Other
    level: 4
    name: Potions (Earth)
    school: Earth
    available: true
  Rock Skin:
    armor: Rock Skin
    available: true
    casting_time: 1 round
    desc: Caster weaponizes and protects their own body by augmenting it with stone and rock. Increases defenses slightly and adds a blunt weapon.
    duration: 3 hours
    effect: Armor
    is_potion: true
    level: 4
    name: Rock Skin
    range: Self
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Rock Skin
  Seismic Sense:
    area: 5 yard radius
    available: true
    casting_time: 1 round
    desc: For the duration of the spell, the caster can detect vibrations in the ground to roughly perceive objects, people, and other aspects of their environment within 10 yards of their person. Vibrations can be sensed underground, past objects that would normally block line of sight, and through invisibility, darkness or any other conditions that effect eyesight. The caster is not required to make perception checks to notice hidden beings within range. Cannot be used on things that have no physical contact with the ground.
    duration: 10 minutes
    effect: Other
    level: 4
    line_of_sight: false
    name: Seismic Sense
    range: Short
    roll: true
    school: Earth
  #Level 5
  Earth Shudder:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    desc: Cause the earth to shudder, distracting up to 3 enemies within its range
     and giving them a penalty to attack and defense.
    duration: 1 round
    effect: Debuff
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Earth Shudder
    range: Long
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Earth Shudder
  Stalagmite:
    available: false
    casting_time: 1 round
    desc: A jagged piece of earth juts up beneath an enemy, doing damage.
    effect: Damage
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Stalagmite
    range: Long
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Stalagmite
  #Level 6
  Familiar (Earth):
    desc: "A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. \n\nFamiliars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles."
    effect: Other
    level: 6
    name: Familiar (Earth)
    roll: true
    school: Earth
    casting_time: 3 hours
    range: Short
    line_of_sight: true
    available: true
  Stone Daggers:
    available: false
    casting_time: 1 round
    desc: A myriad of tiny, sharp stone daggers spring from the earth and fly toward the target with speed and force, automatically seeking weak spots in the foe's armor.
    effect: Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Stone Daggers
    range: Long
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Stone Daggers
  Energize Dimensional Anchor (Earth):
    available: false
    casting_time: 2 minutes
    desc: Provide necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently close an interdimensional portal.
    effect: Travel
    level: 7
    name: Dimensional Anchor
    range: Touch
    roll: true
    school: Earth
  Exploding Earth:
    area: 15 yard radius
    available: false
    casting_time: 1 round
    desc: A ball of jagged earth and stone flies toward a point the caster can see, exploding on impact and hitting up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 7
    line_of_sight: true
    name: Exploding Earth
    range: Long
    school: Earth
    target_num: 3
    target_optional: true
    weapon: Exploding Earth
  #Level 8
  Massive Quake:
    area: Up to 1 square mile
    available: false
    casting_time: 1 round
    desc: Make the earth quake in a location that you can see. It levels structures and causes jagged pieces of earth to rise at random, doing immense damage to anything in its radius.
    effect: AOE Damage
    fs3_attack: true
    level: 8
    line_of_sight: true
    name: Massive Quake
    range: Massive
    school: Earth
    target_num: 100
    target_optional: true
    weapon: Massive Quake
