spells:
  Create Crystal:
    available: true
    casting_time: 1 round
    desc: The caster is able to create a permanent shard of crystal of moderate value. The shard may be no larger than 2 inches, but may be very hard and sharp. Colors may vary.
    effect: Creation
    level: 1
    line_of_sight: true
    name: Create Crystal
    range: Short
    roll: true
    school: Earth
  Glitterdust:
    available: true
    attack_mod: -1
    casting_time: 1 round
    desc: A puff of prismatic mineral particles overtakes a target, acting as a temporary irritant to the eyes and respiratory system.
    effect: Debuff
    level: 1
    line_of_sight: true
    name: Glitterdust
    range: Short
    roll: true
    school: Earth
  Rock Dance:
    available: true
    casting_time: 1 round
    desc: Send half a dozen pebbles and stones smaller than your fist dancing according to your will.
    duration: 10 minutes
    effect: Other
    level: 1
    line_of_sight: true
    name: Rock Dance
    range: Short
    roll: true
    school: Earth
  #Level 2
  Dustup:
    attack_mod: -1
    available: true
    casting_time: 1 round
    defense_mod: -1
    desc: "The caster kicks up a small cloud of dirt around a target, briefly obscuring their vision and making it harder for them to attack or defend."
    duration: 1 round
    effect: Debuff
    level: 2
    line_of_sight: true
    name: Dustup
    range: Short
    rounds: 1
    school: Earth
    target_num: 1
    target_optional: true
    effect: Debuff
  Glow Stone:
    available: true
    casting_time: 1 round
    desc: "The caster imbues up to 1 cubic foot of pre-existing rock or gemstone with the ability to fluoresce, making it able emit a soft glow in the dark after being charged in the light for a short period of time. The light from the stone is dim, equivalent to a small candle flame (12 lumens)."
    duration: 1 hour
    effect: Creation
    level: 2
    name: Glow Stone
    range: Touch
    roll: true
    school: Earth
  Shape Stone:
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can cause up to 1 cubic foot of pre-existing rock or stone to form into simple non-weaponized shapes that animate at their direction. Rock or stone returns to its natural - but not necessarily original - state when the spell ends. "
    duration: 1 hour
    effect: Creation
    level: 2
    line_of_sight: true
    name: Shape Stone
    range: Short
    roll: true
    school: Earth
  Tremor:
    attack_mod: -1
    available: false
    casting_time: 1 round
    desc: "The earth shudders beneath a target's feet, making it difficult for them to aim."
    duration: 2 rounds.
    effect: Debuff
    level: 2
    line_of_sight: true
    name: Tremor
    range: Short
    rounds: 2
    school: Earth
    target_optional: true
    target_num: 1
  #Level 3
  Earth Bolt:
    area: Direct line from caster, 5 yards wide
    available: true
    casting_time: 1 round
    desc: Geomantic force travels through the earth in a straight line, causing rocks to fly into the air and hit up to 3 creatures along its path for one round.
    effect: AOE Damage
    fs3_attack: true
    level: 3
    line_of_sight: true
    name: Earth Bolt
    range: Short
    school: Earth
    target_num: 3
    target_optional: true
    weapon: Earth Bolt
  Floating Earth:
    area: 5 yard radius
    available: true
    casting_time: 1 round
    desc: Create a chunk of earth capable of bearing weight up to 250 lbs and propelling itself through the air at speeds up to 35 mph. Must remain in range or it dissipates.
    duration: 1 hour
    effect: Travel
    level: 3
    line_of_sight: true
    name: Floating Earth
    range: Short
    roll: true
    school: Earth
  Stone Fists:
    available: true
    casting_time: 1 round
    desc: The caster's hands become stone fists capable of inflicting damage.
    duration: 30 minutes
    effect: Damage
    is_potion: true
    level: 3
    name: Stone Fists
    range: Self
    school: Earth
    weapon: Stone Fists
  Stone Slam:
    available: true
    casting_time: 1 round
    desc: Slam a stone the size of a basketball into an opponent with force.
    effect: Damage
    fs3_attack: true
    level: 3
    line_of_sight: true
    name: Stone Slam
    range: Short
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Stone Slam
  Touchstone:
    area: 40 mile radius
    available: true
    casting_time: 1 round
    desc: "The caster creates a link between themselves and a rock, gem, or piece of unalloyed metal, allowing them to always sense its location and direction from their person. If the touchstone is moved, the caster will feel the change in its location and be able to track it. The feeling of the link becomes vaguer the more distant the touchstone is, but the caster can always tell the direction of the touchstone as long as they are in range for the duration of the spell. Only one touchstone can be active at a time."
    duration: 24 hours
    effect: Other
    is_potion: true
    level: 3
    name: Touchstone
    range: Touch
    roll: true
    school: Earth
  #Level 4
  Crystalline Armor:
    armor: Crystalline
    available: true
    casting_time: 1 round
    desc: The caster's skin becomes as hard as densely formed crystal to increase defenses significantly. Colors may vary.
    effect: Armor
    duration: 3 hours
    is_potion: true
    level: 4
    name: Crystalline Armor
    range: Self
    school: Earth
  Diamond Weapon:
    available: true
    casting_time: 1 round
    desc: Augment one specified pre-existing weapon with diamond, making it far sharper and increasing its penetration.
    duration: 3 hours
    effect: Buff
    is_potion: true
    level: 4
    name: Diamond Weapon
    range: Touch
    rounds: 100
    school: Earth
    target_num: 1
    target_optional: true
    weapon_specials: Diamond
    weapon: Spell
  Earth Shudder:
    area: 10 yard radius
    available: true
    casting_time: 1 round
    desc: Cause the earth to shudder, distracting up to 3 enemies within its range
     and giving them a penalty to attack.
    duration: 1 round
    effect: Debuff
    fs3_attack: true
    level: 4
    line_of_sight: true
    name: Earth Shudder
    range: Long
    school: Earth
    target_num: 3
    target_optional: true
    weapon: Earth Shudder
  Potions (Earth):
    desc: The caster has learned the art of potion-making and can craft potions in any school. This is not a spell in the same sense of most, but rather an art learned through study. It takes time, effort, and materials to brew a potion.
    effect: Other
    level: 4
    name: Potions (Earth)
    school: Earth
    available: true
  Rock Skin:
    armor: Rock Skin
    available: true
    casting_time: 1 round
    desc: Caster weaponizes and protects their own body by augmenting it with stone and rock.
    duration: 3 hours
    effect: Armor
    is_potion: true
    level: 4
    name: Rock Skin
    range: Self
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Rock Skin
  Seismic Sense:
    area: 5 yard radius
    available: true
    casting_time: 1 round
    desc: For the duration of the spell, the caster can detect vibrations in the ground to roughly perceive objects, people, and other aspects of their environment within 10 yards of their person. Vibrations can be sensed underground, past objects that would normally block line of sight, and through invisibility, darkness or any other conditions that effect eyesight. The caster is not required to make perception checks to notice hidden beings within range. Cannot be used on things that have no physical contact with the ground.
    duration: 10 minutes
    effect: Other
    level: 4
    line_of_sight: false
    name: Seismic Sense
    range: Self
    roll: true
    school: Earth
  Terramancy:
    available: true
    casting_time: 1 round
    desc: "For the duration of the spell, the caster can move around and shape up to a total of 5 cubic feet of pre-existing dirt, rock, or stone. The caster can sculpt detailed, non-weaponized shapes that animate at their direction. Earth returns to its natural, but not necessarily original, state when the spell ends. "
    duration: 15 minutes
    effect: Creation
    level: 4
    line_of_sight: true
    name: Terramancy
    range: Short
    roll: true
    school: Earth
  #Level 5
  Grounding:
    available: true
    attack_mod: 2
    casting_time: 1 round
    desc: The caster becomes more connected to the earth. They pull a cloud of dust and rocks around themselves and gain more solid footing on the ground, increasing their ability to attack and defend.
    defense_mod: 2
    duration: 6 rounds
    effect: Buff
    level: 5
    name: Grounding
    range: Self
    rounds: 6
    school: Earth
    target_num: 1
  Stalagmite:
    available: true
    casting_time: 1 round
    desc: A jagged piece of earth juts up beneath an enemy, doing damage.
    effect: Damage
    fs3_attack: true
    level: 5
    line_of_sight: true
    name: Stalagmite
    range: Long
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Stalagmite
  Stone Shackles:
    available: true
    casting_time: 1 round
    desc: The caster subdues the target with rock bindings, entrapping their hands and feet to immobilize them briefly.
    duration: 2 rounds
    effect: Stun
    fs3_attack: true
    is_stun: true
    level: 5
    line_of_sight: true
    name: Stone Shackles
    range: Long
    rounds: 2
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Stun (Earth)
  #Level 6
  Diamond Armor:
    armor: Diamond
    available: false
    casting_time: 1 round
    desc: The caster protects the target's body by augmenting it with a layer of hard diamond armor. Coloring may vary.
    duration: 8 hours
    effect: Armor
    level: 6
    name: Diamond Armor
    range: Touch
    school: Earth
  Dust Devils:
    attack_mod: -2
    available: false
    casting_time: 1 round
    defense_mod: -2
    desc: "The caster swirls small clouds of dirt around up to three targets, obscuring their vision and making it harder for them to attack or defend."
    duration: 1 round
    effect: Debuff
    level: 6
    line_of_sight: true
    name: Dust Devils
    range: Short
    rounds: 3
    school: Earth
    target_num: 3
    target_optional: true
    effect: Debuff
  Familiar (Earth):
    desc: "A familiar is a spirit associated or allied with a school of magic that has taken residence in a physical vessel with the shape of an animal. It functions as a companion, assistant, and guardian. \n\nFamiliars may be capable of some or all of the following: sharing telepathic or empathic communication, providing knowledge of the arcane, sharing senses, lending physical aid as spies or fighters, delivering spells at a distance of up to three miles."
    effect: Other
    level: 6
    name: Familiar (Earth)
    roll: true
    school: Earth
    casting_time: 3 hours
    range: Short
    line_of_sight: true
    available: true
  Golem:
    desc: "The caster creates a golem made of rock mixed with sand, dirt and/or clay from the environment. It is bound to do the caster's bidding, able to perform simple tasks and come to the caster's aid in battle. It cannot cast spells. When the spell ends, the golem crumbles away.\n\nIn combat, the golem should be represented by an NPC of level three with Rock Skin."
    effect: Other
    duration: 10 minutes
    level: 6
    name: Golem
    roll: true
    school: Earth
    casting_time: 1 round
    range: Short
    line_of_sight: true
    available: false
  Quicksand:
    area: 2.5 ft radius
    available: true
    casting_time: 1 round
    desc: "The caster turns a 5-foot diameter patch of dirt into quicksand, making it possible to sink something easily into the earth at that spot. If cast on the ground below a target, the target sinks in, immobilizing them until they can climb back out or an ally uses a round to attempt to rescue them. Targets submerged in the ground cannot be attacked."
    duration: 3 rounds
    effect: Stun
    fs3_attack: true
    is_stun: true
    rounds: 3
    level: 6
    line_of_sight: true
    name: Quicksand
    range: Short
    school: Earth
    target_num: 3
    target_optional: true
    weapon: Stun (Earth)
  Stone Daggers:
    available: true
    casting_time: 1 round
    desc: A myriad of tiny, sharp stone daggers spring from the earth and fly toward the target with speed and force, automatically seeking weak spots in the foe's armor.
    effect: Damage
    fs3_attack: true
    level: 6
    line_of_sight: true
    name: Stone Daggers
    range: Long
    school: Earth
    target_num: 1
    target_optional: true
    weapon: Stone Daggers
  Energize Dimensional Anchor (Earth):
    available: true
    casting_time: 2 minutes
    desc: "Provide the necessary magical energy of the appropriate School to a Dimensional Anchor spell, enabling the linked casters to permanently open or close an interdimensional portal.\n\nIf cast on an open portal, the caster can sense if the spell's School is the necessary magical energy to enable opening or closing the portal, as well as the magical coordinates of the portal's existence in the magical universe."
    effect: Travel
    level: 7
    name: Energize Dimensional Anchor (Earth)
    range: Touch
    roll: true
    school: Earth
  Exploding Earth:
    area: 15 yard radius
    available: true
    casting_time: 1 round
    desc: A ball of jagged earth and stone flies toward a point the caster can see, exploding on impact and hitting up to 3 targets.
    effect: AOE Damage
    fs3_attack: true
    level: 7
    line_of_sight: true
    name: Exploding Earth
    range: Long
    school: Earth
    target_num: 3
    target_optional: true
    weapon: Exploding Earth
  #Level 8
  Massive Quake:
    area: Up to 1 square mile
    available: false
    casting_time: 1 round
    desc: Make the earth quake in a location that you can see. It levels structures and causes jagged pieces of earth to rise at random, doing immense damage to anything in its radius.
    effect: AOE Damage
    fs3_attack: true
    level: 8
    line_of_sight: true
    name: Massive Quake
    range: Massive
    school: Earth
    target_num: 100
    target_optional: true
    weapon: Massive Quake
