---
swade:
    skills:
    - 
      name: Academics
      description:  Know something of value or importance from years gone by, including potentially lost modern-day ideas.
      linked_attribute: Smarts
    - 
      name: Athletics
      description:  Combines an individual’s coordination with learned skills such as climbing, jumping, balancing, biking, wrestling, skiing, swimming, throwing, or catching.
      linked_attribute: Agility
    - 
      name: Battle
      description: An individual’s command of strategy and tactics.
      linked_attribute: Smarts
    - 
      name: Boating
      description:  handle most any boat or ship common to their seting. They also know how to handle common tasks associated with their vessel
      linked_attribute: Agility
    - 
      name: Common Knolwedge
      description:  Covers the non-critical, non-emergency operation of common electronics, computers, vehicles, and other gear. It also allows characters to identify the general type of supernatural forces encountered—such as elemental, faerie, demon, undead, etc.
      linked_attribute: Smarts
    - 
      name: Driving
      description:  Control any powered ground vehicle common to his seting.
      linked_attribute: Agility
    - 
      name: Electronics
      description: Using advanced communications equipment, sensors, and almost all non-weapon systems found on Environmental Body Armor and vehicles.
      linked_attribute: Smarts
    - 
      name: Fighting
      description: Hand-to-hand (melee) atacks, whether it’s with fsts, axes, laser swords, or martial arts. 
      linked_attribute: Agility
    - 
      name: Gambling
      description: Games of Chance
      linked_attribute: Smarts
    - 
      name: Hacking
      description: For programming, building, and hacking into them.
      linked_attribute: Smarts
    - 
      name: Healing
      description: Healing has multiple uses, from treating Wounds to diagnosing diseases and analyzing certain kinds of forensic evidence.
      linked_attribute: Smarts
    - 
      name: Intimidation
      description: Intimidation is the art of frightening an opponent so that he backs down, reveals information, or fees.
      linked_attribute: Spirit
    - 
      name: Language
      description: Choices include Chinese, Demongogian, Dragonese, Euro, Faerie Speak, Gobblely, Japanese, Spanish and Techno-Can
      linked_attribute: Smarts
    - 
      name: Notice
      description: General awareness and alertness. It’s used to sense sights, sounds, tastes, and smells, spot clues, detect ambushes, spot hidden weapons on a foe, or tell if a rival is lying, frightened, happy, etc.
      linked_attribute: Smarts
    - 
      name: Occult
      description: Understanding the principles of all supernatural or arcane powers, items, and creatures. It also covers knowledge on dealing with ley lines and Rifts.
      linked_attribute: Smarts
    - 
      name: Performance
      description: A good entertainer can lift the spirits, rally a crowd to action, or simply earn a few bucks from the locals.
      linked_attribute: Spirit
    - 
      name: Persuasion
      description: Ability to convince others to do what you want through reason, cajoling, deception, rewards, or other friendly means. 
      linked_attribute: Spirit
    - 
      name: Piloting
      description: Power armor, robot vehicles, jet packs, hovercycles and advanced hovercraft are all operated using Piloting, whether maneuvering in the air, on the ground, etc.
      linked_attribute: Agility
    - 
      name: Repair
      description: The mechanical aspects of machines, as well as the nature and elements of physical structures, fall under this skill.
      linked_attribute: Smarts
    - 
      name: Pisonics
      description: This is the skill “psions” or “psis” use to activate and control their psionic abilities.
      linked_attribute: Smarts
    - 
      name: Research
      description: Make good use of libraries, newspaper morgues, the internet, or other written sources of information.
      linked_attribute: Smarts
    - 
      name: Riding
      description: Allows a hero to mount, control, and ride any beast or beast-drawn vehicle common to his seting.
      linked_attribute: Agility
    - 
      name: Science
      description: Represents a broad-based knowledge of physics, chemistry, and biology, which is especially important when dealing with advanced biotechnology and alien forms of life or technology.
      linked_attribute: Smarts
    - 
      name: Shooting
      description: All atempts to hit a target with a ranged weapon such as a bow, pistol, or rocket launcher
      linked_attribute: Agility
    - 
      name: Spellcasting
      description: Mages, wizards, warlocks, and witches use Spellcasting to cast spells. 
      linked_attribute: Smarts
    - 
      name: Stealth
      description: Ability to hide and move quietly.
      linked_attribute: Agility
    - 
      name: Survival
      description: Allows a character to find food, water, or shelter in hostile environments. 
      linked_attribute: Smarts
    - 
      name: Taunt
      description: Atacks a person’s pride through ridicule, cruel jests, or oneupmanship.
      linked_attribute: Smarts
    - 
      name: Thievery
      description: Lockpicking, safecracking, picking pockets, sleight of hand, setting and disabling traps and similar acts of misdirection, sabotage, subterfuge, and manipulation
      linked_attribute: Agility