---
swrifts:
    init:
        traits:
            iconicf: None
            race: None
            rank: Novice  
        counters:
            bennies_current: 3
            bennies_max: 3
            conviction: 0
            conviction_current: 0
            damage: 0
            pp_max: 0
            pp_current: 0
            ppe_max: 0
            ppe_current: 0
            isp_max: 0
            isp_current: 0
            pp_max: 0
            pp_current: 0
            burn: 8
            strain: 0
        stats:
            Agility: 1
            Smarts: 1
            Spirit: 1
            Strength: 1
            Vigor: 1
        stat_max:
            Agility: 5
            Smarts: 5
            Spirit: 5
            Strength: 5
            Vigor: 5
        dstats:
            Pace: 6
            Running: 2
            Parry: 3
            Toughness: 3  
            Size: 3
        chargen_points:
            stats_points: 5
            skills_points: 15
            hind_points: 0
            hj_slots:  2
            magic_slots: 0
            psionic_slots: 0
            miracle_slots: 0
            gifted_slots: 0
            edge_slots: 0
        skills:
            Academics: 0
            Athletics: 1
            Battle: 0
            Boating: 0
            Common Knowledge: 1
            Driving: 0
            Electronics: 0
            Faith: 0
            Fighting: 0
            Gambling: 0
            Hacking: 0
            Healing: 0
            Intimidation: 0
            Language: 0
            Notice: 1
            Occult: 0
            Performance: 0
            Persuasion: 1
            Piloting: 0
            Psionics: 0
            Repair: 0
            Research: 0
            Riding: 0
            Science: 0
            Shooting: 0
            Spellcasting: 0
            Stealth: 1
            Survival: 0
            Taunt: 0
            Thievery: 0
            CHOICE: 0
        chargen_min:
            Agility: 1
            Smarts: 1
            Spirit: 1
            Strength: 1
            Vigor: 1
            Academics: 0
            Athletics: 1
            Battle: 0
            Boating: 0
            Common Knowledge: 1
            Driving: 0
            Electronics: 0
            Fighting: 0
            Gambling: 0
            Hacking: 0
            Healing: 0
            Intimidation: 0
            Language: 0
            Notice: 1
            Occult: 0
            Performance: 0
            Persuasion: 1
            Piloting: 0
            Repair: 0
            Research: 0
            Riding: 0
            Science: 0
            Shooting: 0
            Stealth: 1
            Survival: 0
            Taunt: 0
            Thievery: 0
        advances:
            n1: "-"
            n2: "-"
            n3: "-"
            s1: "-"
            s2: "-"
            s3: "-"
            v1: "-"
            v2: "-"
            v3: "-"
            h1: "-"
            h2: "-"
            h3: "-"
            l1: "-"
            l2: "-"
            l3: "-"