---
website:
  allow_html_in_markdown: true
  character_gallery_group: Major School
  character_gallery_subgroup: nil
  left_sidebar: false
  max_upload_size_kb: 5000
  restricted_pages:
  - home
  - policies
  - admin
  sitemap_update_cron:
    hour:
    - 2
    minute:
    - 17
  top_navbar:
  - title: About Us
    menu:
    - page: wiki-page
      title: About Spirit Lake
      id: about_us
    - page: wiki-page
      title: World Intro
      id: world_intro
    - page: wiki-page
      title: Policies
      id: policies
    - page: wiki-page
      title: Join Us
      id: join_us
    - page: wiki-page
      title: Staff Team
      id: staff
  - title: Play
    menu:
    - page: chargen
      title: Create a Character
    - page: roster
      title: Pre-Made Characters
    - divider: true
    - page: scenes-live
      title: Active Scenes
    - page: scenes-play
      title: My Scenes
    - page: scene-create
      title: Start New Scene
    - page: combats
      title: Combats
    - divider: true
    - page: play
      title: Play via Web Client
  - title: Game
    menu:
    - page: wiki-page
      title: Getting Started
      id: getting_started
    - page: wiki-page
      title: Guides
      id: guide
    - page: help
      title: Help
    - divider: true
    - page: chat
      title: Chat
    - page: forum
      title: Forum
    - page: events
      title: Events
    - page: jobs
      title: Requests
    - page: who
      title: Who's Online
  - title: World
    menu:
    - page: wiki-page
      title: Grand Lake
      id: grand_lake
    - page: wiki-page
      title: Magic
      id: magic
    - page: wiki-page
      title: Schools
      id: schools
    - page: wiki-page
      title: Magical Items
      id: magical_items
    - page: wiki-page
      title: Magical Orders
      id: magical_orders
    - page: wiki-page
      title: Portals
      id: portals
    - page: wiki-page
      title: Creatures
      id: creatures
    - page: wiki-page
      title: Familiars
      id: familiars
  - title: Story
    menu:
    - page: characters
      title: Characters
    - page: scenes
      title: Scenes
    - page: plots
      title: Plots
    - divider: true
    - page: wiki-page
      title: Under-Library
      id: underlibrary
    - page: wiki-page
      title: Hooks & Hopes
      id: hooks__amp__hopes
    - page: wiki-page
      title: Player Run Plots
      id: player_run_plots
    - page: secrets
      title: Secrets
  - title: Directory
    menu:
    - page: spells
      title: Spells
    - page: portals
      title: Portals
    - page: creatures
      title: Creatures
    - page: characters
      title: Characters
    - divider: true
    - page: players
      title: Players
    - page: census
      title: Census
    - page: actors
      title: Actors
    - page: locations
      title: Locations
    - divider: true
    - page: files
      title: Files
  - title: System
    menu:
    - page: wiki-page
      title: Combat Guide
      id: combat_guide
    - page: wiki-page
      title: Combat Organizer's Guide
      id: combat_org_guide
    - page: wiki-page
      title: Magic System
      id: magic_system
    - page: wiki-page
      title: Luck Points
      id: luck_points
    - page: wiki-page
      title: XP
      id: xp
    - divider: true
    - page: fs3skills-abilities
      title: Abilities List
    - page: fs3combat-gear
      title: Gear List
    - page: spells
      title: Spell List
    - page: groups
      title: Groups List
    - divider: true
    - target: blank
      title: FS3 Player's Guide <i class="fa fa-external-link-alt" aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3
    - target: blank
      title: FS3 Combat Quick Reference <i class="fa fa-external-link-alt" aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3/combat-quickref.html
    - target: blank
      title: FS3 Interactive Combat Walkthrough <i class="fa fa-external-link-alt"
        aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3/combat-walkthrough.html
  website_code_path: "/home/ares/ares-webportal"
  wiki_aliases:
    main: home
