---
website:
  achievements:
    wiki_create:
      type: portal
      message: Created a wiki page.
    wiki_edit:
      type: portal
      message: Edited a wiki page.
  allow_html_in_markdown: true
  auto_wiki_export: false
  character_gallery_group: Organization
  character_gallery_subgroup: Mythic
  left_sidebar: false
  max_folder_size_kb: 2000
  max_upload_size_kb: 3000
  permissions:
    manage_theme: Edit web portal CSS and colors.
    manage_wiki: Create and delete restricted wiki pages.
  restricted_pages:
  - home
  sitemap_update_cron:
    hour:
    - 2
    minute:
    - 17
  top_navbar:
  - title: Intro
    menu:
    - title: Join Us
      route: wiki-page
      id: join_us
    - title: Create a Character
      route: chargen
    - title: Roster Characters
      route: roster
    - divider: true
    - title: About Shattered
      route: wiki-page
      id: ooc:about_us
    - divider: true
    - title: Getting Started
      route: wiki-page
      id: guide:getting_started
  - title: Game
    menu:
    - title: Policies
      route: wiki-page
      id: ooc:policies
    - title: Staff Team
      route: wiki-page
      id: ooc:staff
    - divider: true
    - title: Guides
      route: wiki-page
      id: guide
    - divider: true
    - title: Who's Online
      route: who
    - title: Forum
      route: forum
    - title: Events
      route: events
    - title: Game Help
      route: help
    - title: Wiki Menu
      route: wiki-page
      id: ooc:wiki_menu
  - title: World
    menu:
    - title: World Intro
      route: wiki-page
      id: home
    - title: Wardens
      route: wiki-page
      id: world:wardens
    - title: Mythics
      route: wiki-page
      id: world:mythics
    - title: Cryptids
      route: wiki-page
      id: world:cryptids
    - title: Spirits
      route: wiki-page
      id: world:spirits
    - divider: true
    - title: The Cradle
      route: wiki-page
      id: world:cradle
    - title: Beyond the Cradle
      route: wiki-page
      id: world:beyond_the_cradle
    - title: Weyr
      route: wiki-page
      id: world:weyr
    - title: Weyrling School
      route: wiki-page
      id: world:weyrling_school
    - title: Prism Passes
      route: wiki-page
      id: world:prism_passes
    - divider: true
    - title: Technology
      route: wiki-page
      id: world:technology
    - title: Laws & Morality
      route: wiki-page
      id: laws
    - title: Holidays
      route: wiki-page
      id: holidays
    - divider: true
    - title: FAQ
      route: wiki-page
      id: faq
  - title: Magic
    menu:
    - title: Magic
      route: wiki-page
      id: magic
    - title: "- Creation"
      route: school
      id: creation
    - title: "- Entropy"
      route: school
      id: entropy
    - title: "- Arcane"
      route: school
      id: arcane
    - title: "- Aether"
      route: school
      id: aether
    - divider: true
    - title: The Bond
      route: wiki-page
      id: world:bond
    - title: Telepathy
      route: wiki-page
      id: telepathy
    - title: Telekinesis
      route: wiki-page
      id: telekinesis
    - divider: true
    - title: Blood Magic
      route: wiki-page
      id: blood_magic
    - title: Potions
      route: wiki-page
      id: potions
  - title: Play
    menu:
    - title: Play
      route: play
    - title: Active Scenes
      route: scenes-live
    - title: Unshared Scenes
      route: scenes-unshared
    - title: Start New Scene
      route: scene-create
    - title: Combats
      route: combats
    - divider: true
    - title: Web Client
      route: client
  - title: Story
    menu:
    - title: Scenes
      route: scenes
    - title: Plots
      route: plots
    - divider: true
    - title: Hooks
      route: wiki-page
      id: ooc:hooks
    - title: Story So Far
      route: wiki-page
      id: ooc:story_so_far
  - title: Directory
    menu:
    - title: Characters
      route: characters
    - title: Roster Characters
      route: roster
    - title: NPCs
      route: wiki-page
      id: npc
    - title: Cryptids
      route: creatures
    - title: Spells
      route: spells
    - divider: true
    - title: Players
      route: players
    - title: Game Admin
      route: admins
    - title: Census
      route: census
    - title: Locations
      route: locations
    - title: Achievements
      route: achievements
    - divider: true
    - title: Files
      route: files
  - title: System
    menu:
    - title: Combat Guide
      route: wiki-page
      id: guide:combat_guide
    - title: Combat Tactics Guide
      route: wiki-page
      id: guide:combat_tactics
    - title: Combat Organizer's Guide
      route: wiki-page
      id: guide:combat_organizers_guide
    - title: Balancing Combat
      route: wiki-page
      id: guide:balancing_combat
    - divider: true
    - title: Spells
      route: spells
    - title: Magic
      route: wiki-page
      id: magic
    - divider: true
    - title: Luck Points
      route: wiki-page
      id: system:luck_points
    - title: XP
      route: wiki-page
      id: system:xp
    - divider: true
    - title: Plot System
      route: wiki-page
      id: system:plot_system
    - title: Player Run Plots
      route: wiki-page
      id: system:player_run_plots
    - title: One-Shot Adventures
      route: wiki-page
      id: system:one-shot_adventures
    - divider: true
    - title: Abilities & Skills
      route: wiki-page
      id: system:abilities_skills
    - title: Gear List
      route: fs3combat-gear
    - divider: true
    - target: blank
      title: FS3 Player's Guide <i class="fa fa-external-link-alt" aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3
    - target: blank
      title: FS3 Combat Quick Reference <i class="fa fa-external-link-alt" aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3/combat-quickref.html
    - target: blank
      title: FS3 Interactive Combat Walkthrough <i class="fa fa-external-link-alt"
        aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3/combat-walkthrough.html
  - title: Search
    menu:
    - title: Spells
      route: search-spells
    - title: Scenes
      route: search-scenes
    - title: Characters
      route: search-chars
    - title: Wiki
      route: search-wiki
    - title: Forum
      route: search-forum
    - title: Help
      route: search-help
    - title: Locations
      route: search-locations
    - title: Jobs & Requests
      route: search-jobs
  uploadable_extensions:
  - ".jpg"
  - ".png"
  - ".gif"
  - ".jpeg"
  website_code_path: "/home/ares/ares-webportal"
  wiki_aliases:
    main: world
    home: world
    history: world:history
    shattering: world:history
    cryptids: world:cryptids
    mythic: world:mythics
    cryptid: world:cryptids
    monsters: world:cryptids
    mythics: world:mythics
    shattered_monsters: world:cryptids
    creatures: world:cryptids
    bonding: world:bond
    bond: world:bond
    bonded: world:bond
    focus: world:bond
    locations: world:locations
    cradle: world:cradle
    cradle_s: world:cradle
    cradle's: world:cradle
    holidays: world:holidays
    weyr: world:weyr
    weyrs: world:weyr
    north_weyr: world:weyr
    mages: world:mages
    unbonded_magic: world:mages
    unbonded: world:mages
    unbonded_mages: world:mages
    prism_passes: world:prism_passes
    prism: world:prism_passes
    school: world:weyrling_school
    weyrling_school: world:weyrling_school
    crime: world:laws_morality
    laws: world:laws_morality
    legal: world:laws_morality
    morals: world:laws_morality
    moral: world:laws_morality
    spirits: world:spirits
    ghosts: world:spirits
    spirit: world:spirits
    ghost: world:spirits
    souls: world:spirits
    wardens: world:wardens
    warden: world:wardens
    technology: world:technology
    tech: world:technology
    magical: magic
    blood_magic: magic:blood_magic
    blood: magic:blood_magic
    potion: magic:potions
    potions: magic:potions
    telekinesis: magic:telekinesis
    telekinetic: magic:telekinesis
    telepathy: magic:telepathy
    telepathic: magic:telepathy
    telepathically: magic:telepathy
    alarm: magic:alarm
    nomad_alarm: magic:alarm
    app_staff: ooc:staff
    staff: ooc:staff
    storytellers: ooc:staff
    sts: ooc:staff
    admin: ooc:staff
    story_so_far: ooc:story_so_far
    hooks: ooc:hooks
    policies: ooc:policies
    faq: faq
    frequently_asked_questions: faq
    plot_system: system:plot_system
    player_run_plots: system:player_run_plots
    prp: system:player_run_plots
    prps: system:player_run_plots
    player-run-plots: system:player_run_plots
    luck_points: system:luck_points
    luck_point: system:luck_points
    one-shot_adventures: system:one-shot_adventures
    getting_started: guide:getting_started
    join_us: guide:join_us
    combat_guide: guide:combat_guide
    combat_organizers_guide: guide:combat_organizers_guide
    combat_tactics: guide:combat_tactics
    combat_tactics_guide: guide:combat_tactics
    gm_guide: guide:gm_guide
  wiki_export_cron:
    hour:
    - 3
    minute:
    - 37
  story: <div class="torn_container torn_left"><div></div> <div><p><a href="https://shatteredmu.com/forum/6/78">Changing
    of the Guard</a></p><p>It's been seventy years since the world Shattered, and
    the Cradle has been thriving for over five decades. The Wardens have grown with
    them, settling into their magic, their bond, and their sworn oath to protect the
    Cradle and its citizens.</p><p>Two months ago, the Wardens were shocked when Warden
    Commander Morrow and his bonded pegasus, Barak, rode into battle. Their deaths
    and the subsequent controversial election of Warden Commander Warner have thrown
    many Wardens into a state of uneasy change. Warner's views on the role of the
    Wardens in the Cradle is far different from Morrow's. What does this mean for
    the future of the Wardens?</p></div></div>
  hide_searchbox: false
