---
who:
  where_style: scene
  who_fields:
  - field: status
    width: 7
    title: Status
  - field: name
    width: 20
    title: Name
  - field: group
    value: major school
    width: 16
    title: Major School
  - field: group
    value: minor school
    width: 18
    title: Minor School
  - field: connected
    width: 7
    title: Conn
  - field: idle
    width: 4
    title: Idle
