weather:  
    temperatures: 
        - hot
        - warm
        - cool
        - cold
        - freezing
    
    conditions:
        - clear
        - fair
        - misty
        - overcast
        - drizzling
        - raining
        - storming
        - flurrying
        - snowing

    climates:
        polar:
            spring:
                temperature: cold cold cold cold cold freezing freezing freezing cool cool
                condition:  clear clear clear fair fair fair flurrying flurrying overcast snowing
                stability: 70
            summer:
                temperature: cold cold cold cold cold freezing freezing freezing cool cool
                condition:  clear clear clear fair fair fair flurrying flurrying overcast snowing
                stability: 70
            fall:
                temperature: cold cold cold cold cold freezing freezing freezing cool cool
                condition:  clear clear clear fair fair fair flurrying flurrying overcast snowing
                stability: 70
            winter:
                temperature: cold cold cold cold cold freezing freezing freezing cool cool
                condition:  clear clear clear fair fair fair flurrying flurrying overcast snowing
                stability: 70
        temperate:
            summer:
                temperature: hot hot hot hot hot warm warm warm cool cool
                condition:  clear clear clear fair fair fair drizzling drizzling overcast raining
                stability: 70
            spring:
                temperature: cool cool cool cool cool warm warm warm warm warm
                condition:  clear clear clear fair fair fair drizzling drizzling overcast raining
                stability: 70
            fall:
                temperature: cool cool cool cool cool cool cool freezing warm warm
                condition:  clear clear clear fair fair fair drizzling drizzling overcast raining
                stability: 70
            winter:
                temperature: cold cold cold cold cold cold cold cool cool freezing freezing
                condition:  clear clear clear fair fair fair flurrying flurrying overcast snowing
                stability: 70

    default_climate: temperate

    climate_for_area:
        Offstage: none
        North: polar
     
    weather_cron:
        minute: 
            - 00
