---
mail:
  shortcuts:
    mail/clear: mail/delete
    mail/unclear: mail/undelete
    mail/purge: mail/emptytrash
    mail/recall: mail/unsend
    mail/folder: mail/filter
    mail/fo: mail/filter
    mail/file: mail/archive
