---
demographics:
  census_fields:
  - field: name
    width: 28
    title: Name
  - field: demographic
    width: 10
    title: Gender
    value: gender
  - field: group
    width: 20
    title: Faction
    value: Faction
  - field: group
    width: 20
    title: Position
    value: Position
  demographics:
  - full name
  - callsign
  - gender
  - hair
  - eyes
  - skin
  - height
  - physique
  - played by
  - birthdate
  disable_auto_shortcuts: false
  editable_properties:
  - full name
  - callsign
  - gender
  - hair
  - physique
  genders:
    Male:
      possessive_pronoun: his
      subjective_pronoun: he
      objective_pronoun: him
      noun: man
    Female:
      possessive_pronoun: her
      subjective_pronoun: she
      objective_pronoun: her
      noun: woman
    Other:
      possessive_pronoun: their
      subjective_pronoun: they
      objective_pronoun: them
      noun: person
    Robot:
      possessive_pronoun: their
      subjective_pronoun: they
      objective_pronoun: them
      noun: robot
  groups:
    Faction:
      desc: Military faction.
      wiki: ''
      values:
        Navy: Join the fleet, see the worlds.
        Marines: Semper fi.
    Department:
      wiki: ''
      desc: The ship is divided into several departments.  See the wiki for details.
      values:
        Air Wing: Viper and Raptor crews and deckhands. (Officers and Enlisted)
        Marines: Boots on the ground. (Enlisted only)
        Support: Support personnel - Deck crew, medical. (Officers and Enlisted)
    Colony:
      desc: Your character's home world.
      wiki: ''
      values:
        Aerilon: Bread basket of the colonies.
        Aquaria: Cold, harsh world popular with tourists.
        Canceron: Crowded and hot, a developing nation.
        Caprica: Rich center of colonial culture and industry.
        Gemenon: Fundamentalist religion and isolationist people.
        Leonis: Old imperialist empire in decline, still known for culture and fashion.
        Libran: Neutral colony renowned for fostering inter-colonial cooperation.
        Picon: Water world famous for its beaches and strong navy.
        Sagittaron: Poor colony, oft-exploited, now carved into several protectorates.
        Scorpia: Lush jungles and bitter clan warfare. Home to shipyards constructing
          the Battlestars.
        Tauron: An up-and-coming socialist republic with a strong agricultural base
          and developing industries.
        Virgon: A monarchy in decline, clinging to old traditions.
    Position:
      desc: Job.
      wiki: ''
      values:
        Viper Pilot: Navy Viper pilot.
        Raptor Pilot: Navy Raptor pilot.
        Raptor ECO: Navy Raptor Electronic Countermeasures Officer
        Rifleman: Marine rifleman.
        Gunner: Marine support/heavy weapons specialist.
        Combat Engineer: Marine demolitions, construction, maintenance.
        Recon: Marine scout.
        Combat Medic: Marine medic.
        Doctor: Navy doc.
        Nurse: Navy nurse.
        Corpsman: Navy medic.
        Medical Support: Other medical personnel.
        Deck Crew: Air wing support/maintenance personnel.
        Other: Any other position.
  help_text:
    played by: "%xcplayedby <actor>%xn - Your 'dream casting' for your character."
    physique: "%xcphysique <build/body type>%xn - athletic, wiry, slim, pudgy, etc."
    gender: "%xcgender <male/female/other>%xn"
    hair: "%xchair <hair color>%xn"
    eyes: "%xceyes <eye color>%xn"
    skin: "%xcskin <complexion>%xn"
    birthdate: "%xcbirthdate <mm/dd/yyy>%xn or %xcage <years>%xn"
    callsign: "%xccallsign <callsign>%xn - Non-pilots may leave blank or enter a nickname."
    full name: "%xcfullname <name>%xn - Your character's full name."
  max_age: 65
  min_age: 18
  nickname_field: ''
  nickname_format: "%{name} (%{nickname})"
  private_properties: []
  required_properties:
  - played by
  - hair
  - eyes
  - skin
  - height
  - physique
  - full name
  - gender
  - birthdate
  shortcuts:
    groups: group
    colonies: group colony
    demographics: demographic
    birthday: birthdate
    actors: census played by
    actor: demographic/set played by=
    fullname: demographic/set full name=
    playedby: demographic/set played by=
  permissions:
    manage_demographics: Edit demographics on other players.
