---
login:
  allow_web_registration: true
  guest_role: guest
  activity_cron:
    minute:
    - 0
  blacklist_cron:
    day:
    - 1
    - 15
    hour:
    - 3
    minute:
    - 0
  notice_cleanup_cron:
    day:
    - 18
    hour:
    - 2
    minute:
    - 19
  notice_timeout_days: 60
  shortcuts:
    logout: quit
    con: connect
    newpassword: password/reset
    conn: connect
    kick: boot
    password/change: password/set
    motd: notice/motd
  allow_creation: true
  login_not_allowed_message: ''
  creation_not_allowed_message: ''
  portal_requires_registration: 
  guest_disabled_message: ''
