---
manage:
  shortcuts:
    ex: examine
    search: find
    name: rename
    nuke: destroy
    wall: announce
    about: version
    update: upgrade
  permissions:
    announce: Use the announce command.
    boot: Use the boot command.
    manage_game: Code and database-related tasks, including restarts and loads.
