---
profile:
  shortcuts:
    finger: profile
    info: profile
    profile/set: profile/add
    profile/update: profile/add
    nfo: profile
    alts: profile
    profile/remove: profile/delete
    relationships: relationship
    relationship/remove: relationship/delete
    relationship/update: relationship/add
    relationship/set: relationship/add
  achievements:
    profile_edit:
      type: portal
      message: Edited your character profile.
  backup_commands:
  - sheet
  - bg
  - profile
  - damage
  - relationships
  - outfits/all
  permissions:
    manage_profiles: Allows editing other characters' profiles.
