---
server:
  bind_address: ''
  certificate_file_path: "/home/ares/certs/fullchain.pem"
  engine_api_port: 4203
  hostname: localhost
  port: 4201
  private_key_file_path: "/home/ares/certs/privkey.pem"
  use_https: false
  web_portal_port: 4200
  websocket_port: 4202
